'use client';
import Link from 'next/link';
import {useState} from 'react';
import {api,STORE,getCartToken,setCartToken,getCurrency,mediaUrl,money,track} from '../lib/api';

function ToggleIcon({kind}:{kind:'heart'|'compare'|'eye'|'cart'}){const p:any={heart:<path d="M12 20.5 4.8 13.7C.7 9.8 2.8 4 7.5 4c2 0 3.4 1 4.5 2.4C13.1 5 14.5 4 16.5 4c4.7 0 6.8 5.8 2.7 9.7L12 20.5Z"/>,compare:<><path d="M7 4v16M17 4v16"/><path d="m3.5 7 3.5-3 3.5 3M13.5 17l3.5 3 3.5-3"/></>,eye:<><path d="M2.5 12s3.3-5 9.5-5 9.5 5 9.5 5-3.3 5-9.5 5-9.5-5-9.5-5Z"/><circle cx="12" cy="12" r="2.3"/></>,cart:<><path d="M3 4h2l2.2 10.2h9.7L20 7H6.2"/><circle cx="9" cy="19" r="1.2"/><circle cx="17" cy="19" r="1.2"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[kind]}</svg>}
function saved(key:string,id:string){if(typeof window==='undefined')return false;try{return JSON.parse(localStorage.getItem(key)||'[]').includes(id)}catch{return false}}
function toggleSaved(key:string,id:string){if(typeof window==='undefined')return false;let arr:string[]=[];try{arr=JSON.parse(localStorage.getItem(key)||'[]')}catch{};arr=arr.includes(id)?arr.filter(x=>x!==id):[...arr,id];localStorage.setItem(key,JSON.stringify(arr));return arr.includes(id)}

export default function ProductCard({p,currency='TRY'}:{p:any,currency?:string,key?:any}){
  const v=p.variants?.[0];const images=Array.isArray(p.images)?p.images:[];const first=images[0];const second=images[1];const[quick,setQuick]=useState(false);const[busy,setBusy]=useState(false);const[liked,setLiked]=useState(()=>saved('ticarti-wishlist',String(p.id)));const[compared,setCompared]=useState(()=>saved('ticarti-compare',String(p.id)));
  const discount=v?.comparePrice&&Number(v.comparePrice)>Number(v.price)?Math.round((1-Number(v.price)/Number(v.comparePrice))*100):0;
  const stock=v?.inventory?Math.max(0,Number(v.inventory.onHand||0)-Number(v.inventory.reserved||0)):null;const soldOut=stock!==null&&v?.inventory?.trackStock&&stock<1&&!v?.inventory?.allowBackorder;
  async function quickAdd(){if(!v?.id||busy)return;setBusy(true);try{let t=getCartToken();if(!t){const c=await api(`/storefront/${STORE}/carts`,{method:'POST',body:JSON.stringify({currency:getCurrency()})});t=c.token;setCartToken(t)}await api(`/storefront/carts/${t}/items`,{method:'POST',body:JSON.stringify({variantId:v.id,quantity:1})});track('add_to_cart',{item_id:p.id,item_name:p.title,variant_id:v.id,value:Number(v.price||0),currency,quantity:1});window.dispatchEvent(new Event('cart-change'))}finally{setBusy(false)}}
  return <article className="product-card" data-product-id={p.id}>
    <div className="product-card-media">
      <Link href={'/products/'+p.slug} aria-label={p.title} onClick={()=>track('select_item',{item_id:p.id,item_name:p.title,value:Number(v?.price||0),currency})}>
        {first?<picture className="product-card-image primary"><source srcSet={mediaUrl(first.url,'card','avif')} type="image/avif"/><source srcSet={mediaUrl(first.url,'card','webp')} type="image/webp"/><img loading="lazy" decoding="async" src={mediaUrl(first.url,'card','webp')} alt={first.alt||p.title}/></picture>:<span className="product-image-empty" aria-hidden="true"/>}
        {second&&<picture className="product-card-image secondary"><source srcSet={mediaUrl(second.url,'card','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(second.url,'card','webp')} alt={second.alt||p.title}/></picture>}
      </Link>
      <div className="product-card-badges">{soldOut?<span className="sold-out">TÜKENDİ</span>:discount>0&&<span className="sale">-%{discount}</span>}{p.featured&&<span>ÖNE ÇIKAN</span>}{first?.aiGenerated&&<span>AI</span>}</div>
      <div className="product-card-actions"><button type="button" className={liked?'active':''} onClick={()=>setLiked(toggleSaved('ticarti-wishlist',String(p.id)))} aria-label="Favoriye ekle"><ToggleIcon kind="heart"/></button><button type="button" className={compared?'active':''} onClick={()=>setCompared(toggleSaved('ticarti-compare',String(p.id)))} aria-label="Karşılaştır"><ToggleIcon kind="compare"/></button><button type="button" onClick={()=>setQuick(true)} aria-label="Hızlı görünüm"><ToggleIcon kind="eye"/></button></div>
      {v?.id&&<button type="button" disabled={busy||soldOut} className="product-card-quickadd" onClick={()=>void quickAdd()}><ToggleIcon kind="cart"/><span>{soldOut?'Tükendi':busy?'Ekleniyor':'Sepete ekle'}</span></button>}
    </div>
    <div className="product-card-copy">{p.brand?.name&&<small>{p.brand.name}</small>}<Link href={'/products/'+p.slug}><h3>{p.title}</h3></Link>{p.rating&&<div className="product-card-rating">★★★★★ <span>{p.reviewCount||''}</span></div>}<div className="price">{money(v?.price,currency)}{v?.comparePrice&&<span className="old">{money(v.comparePrice,currency)}</span>}</div>{Array.isArray(p.variants)&&p.variants.length>1&&<div className="product-card-swatches">{p.variants.slice(0,5).map((x:any)=><i key={x.id} title={x.title}/>)}</div>}</div>
    {quick&&<div className="quick-view-backdrop" role="dialog" aria-modal="true" aria-label={`${p.title} hızlı görünüm`} onClick={()=>setQuick(false)}><div className="quick-view" onClick={e=>e.stopPropagation()}><button className="quick-view-close" onClick={()=>setQuick(false)} aria-label="Kapat">×</button><div className="quick-view-media">{first&&<img src={mediaUrl(first.url,'detail','webp')} alt={first.alt||p.title}/>}</div><div className="quick-view-copy">{p.brand?.name&&<small>{p.brand.name}</small>}<h2>{p.title}</h2><div className="price">{money(v?.price,currency)}{v?.comparePrice&&<span className="old">{money(v.comparePrice,currency)}</span>}</div><p>{p.shortDescription||p.description||''}</p><div className="quick-view-buttons"><button className="btn" disabled={busy} onClick={()=>void quickAdd()}>Sepete ekle</button><Link className="btn alt" href={'/products/'+p.slug}>Ürüne git</Link></div></div></div></div>}
  </article>
}
