'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
const tabs=['Genel Bakış','Firmalar','Paketler','Temalar','Alan Adları','Uygulamalar','Kullanıcılar','Destek'];

export default function Page(){
  const router=useRouter(); const [restoring,setRestoring]=useState(true);
  const [token,setToken]=useState(''); const [tab,setTab]=useState(tabs[0]); const [data,setData]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{void restore()},[]);
  async function restore(){try{const r=await fetch(API+'/superadmin-auth/refresh',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-auth-client':'superadmin'},body:'{}'});if(!r.ok)return;const j=await r.json();if(j.accessToken)setToken(j.accessToken)}catch{}finally{setRestoring(false)}}
  useEffect(()=>{if(!restoring&&!token)router.replace('/login')},[restoring,token,router]);
  async function req(path:string,o:any={}){let r=await fetch(API+path,{...o,credentials:'include',headers:{'content-type':'application/json','authorization':`Bearer ${token}`,...o.headers}});if(r.status===401){const rr=await fetch(API+'/superadmin-auth/refresh',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-auth-client':'superadmin'},body:'{}'});if(rr.ok){const x=await rr.json();setToken(x.accessToken);r=await fetch(API+path,{...o,credentials:'include',headers:{'content-type':'application/json','authorization':`Bearer ${x.accessToken}`,...o.headers}})}}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Array.isArray(j.message)?j.message.join(', '):(j.message||'İşlem başarısız'));return j}

  useEffect(()=>{if(token)void load()},[token,tab]);
  async function load(){try{setError('');setData(null);let p='/superadmin/dashboard';if(tab==='Firmalar')p='/superadmin/tenants';if(tab==='Paketler')p='/superadmin/plans';if(tab==='Temalar')p='/superadmin/themes';if(tab==='Alan Adları')p='/superadmin/reserved-subdomains';if(tab==='Uygulamalar')p='/superadmin/apps';if(tab==='Kullanıcılar')p='/superadmin/users';if(tab==='Destek')p='/superadmin/support/tickets';setData(await req(p))}catch(e:any){setError(e.message)}}
  if(restoring||!token)return <div className="login"><div className="login-card"><h1>Super Admin</h1><p className="muted">Güvenli oturum kontrol ediliyor…</p></div></div>;
  return <div className="app"><aside className="sidebar"><div className="brand">Commerce HQ</div><div className="nav">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div></aside><main className="content"><div className="topbar"><div><h1 style={{margin:0}}>{tab}</h1><div className="muted">SaaS platform yönetimi</div></div><button className="btn secondary" onClick={async()=>{try{await fetch(API+'/superadmin-auth/logout',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-auth-client':'superadmin'},body:'{}'})}catch{}setToken('')}}>Çıkış</button></div>{error&&<div className="error">{error}</div>}<View tab={tab} data={data} req={req} reload={load}/></main></div>
}

function View({tab,data,req,reload}:any){
  if(!data)return <div className="panel">Yükleniyor…</div>;
  if(tab==='Genel Bakış')return <><div className="cards">{[['Firma / Site',data.metrics?.tenants],['Aktif firma',data.metrics?.activeTenants],['Ürün',data.metrics?.products],['Açık destek',data.metrics?.openTickets]].map(([a,b])=><div className="card" key={a as string}><div className="muted">{a}</div><div className="metric">{b}</div></div>)}</div><div className="panel"><h3>Platform GMV</h3><div className="metric">₺{Number(data.metrics?.gmV||0).toLocaleString('tr-TR')}</div><h3>Yeni firmalar</h3><Table rows={data.recentTenants||[]} cols={[['name','Firma / Site'],['status','Durum'],['_count.products','Ürün'],['createdAt','Kayıt']]}/></div></>;
  if(tab==='Firmalar')return <><TenantControl tenants={data} req={req} reload={reload}/><div className="panel"><Table rows={data} cols={[['name','Firma / Site'],['domain','Domain'],['status','Durum'],['_count.products','Ürün'],['_count.memberships','Kullanıcı'],['subscriptions.0.plan.name','Paket'],['createdAt','Kayıt']]}/></div></>;
  if(tab==='Paketler')return <><PlanForm req={req} reload={reload}/><div className="panel"><Table rows={data} cols={[['name','Paket'],['code','Kod'],['monthlyPrice','Aylık'],['maxStaff','Personel'],['maxProducts','Ürün'],['maxOrdersPerMonth','Aylık Sipariş'],['isActive','Aktif']]}/></div></>;
  if(tab==='Temalar')return <ThemeControl themes={data} req={req} reload={reload}/>;
  if(tab==='Alan Adları')return <ReservedSubdomainControl rows={data} req={req} reload={reload}/>;
  if(tab==='Uygulamalar')return <AppControl apps={data} req={req} reload={reload}/>;
  if(tab==='Kullanıcılar')return <div className="panel"><Table rows={data} cols={[['email','E-posta'],['name','Ad'],['createdAt','Kayıt']]}/></div>;
  if(tab==='Destek')return <><SupportControl tickets={data} req={req} reload={reload}/><div className="panel"><Table rows={data} cols={[['subject','Konu'],['tenant.name','Firma'],['priority','Öncelik'],['status','Durum'],['messages.length','Mesaj'],['updatedAt','Güncelleme']]}/></div></>;
  return null;
}


function ThemeControl({themes,req,reload}:any){
  const[plans,setPlans]=useState<any[]>([]);const[tenants,setTenants]=useState<any[]>([]);const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[edit,setEdit]=useState<any|null>(null);
  useEffect(()=>{Promise.all([req('/superadmin/plans'),req('/superadmin/tenants')]).then(([p,t])=>{setPlans(p);setTenants(t)}).catch((e:any)=>setErr(e.message))},[]);
  async function run(fn:()=>Promise<any>,ok:string){setMsg('');setErr('');try{await fn();setMsg(ok);await reload();return true}catch(e:any){setErr(e.message||'İşlem başarısız');return false}}
  return <>{msg&&<div className="success">{msg}</div>}{err&&<div className="error">{err}</div>}
    <div className="panel"><div className="toolbar"><div><h3 style={{margin:'0 0 6px'}}>Tema kataloğu</h3><p className="muted" style={{margin:0}}>Temayı aktif/pasif yapın, pakete dahil edin veya düşük paketlerde ayrıca satın alınabilir bırakın.</p></div><button className="btn" onClick={()=>setEdit({})}>Yeni tema</button></div></div>
    <div className="panel"><h3>Paket erişimi ve fiyatı</h3><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/themes/'+f.themeId+'/plan-pricing',{method:'POST',body:JSON.stringify({planId:f.planId,price:f.price===''?null:Number(f.price),currency:f.currency,included:f.included==='true',isActive:true})}),'Tema paket fiyatı kaydedildi.')}}><label>Tema<select name="themeId" required>{themes.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Paket<select name="planId" required>{plans.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Fiyat<input name="price" type="number" min="0" step="0.01" placeholder="Boş = tema temel fiyatı"/></label><label>Para birimi<select name="currency"><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Pakete dahil<select name="included"><option value="false">Hayır, ayrıca sat</option><option value="true">Evet, ücretsiz dahil</option></select></label><div className="full"><button className="btn">Kaydet</button></div></form></div>
    <div className="panel"><h3>Tema modüllerini aç / kapat</h3><p className="muted">Kapattığınız modül müşterinin tasarım kütüphanesinde görünmez. Mevcut mağazada eklenmiş içerik silinmez.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/themes/'+f.themeId+'/module-toggle',{method:'POST',body:JSON.stringify({type:f.type,enabled:f.enabled==='true'})}),'Modül erişimi güncellendi.')}}><label>Tema<select name="themeId" required>{themes.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Modül tipi<input name="type" placeholder="lookbook" required/></label><label>Durum<select name="enabled"><option value="true">Açık</option><option value="false">Kapalı</option></select></label><div className="full"><button className="btn">Uygula</button></div></form></div>
    <div className="panel"><h3>Mağazaya tema tanımla</h3><p className="muted">Ödeme kontrolünü atlayarak seçili mağazaya temayı lisanslar. Tema otomatik aktif edilmez.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/tenants/'+f.tenantId+'/themes/'+f.themeId+'/grant',{method:'POST',body:'{}'}),'Tema mağazaya tanımlandı.')}}><label>Mağaza<select name="tenantId" required>{tenants.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Tema<select name="themeId" required>{themes.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><div className="full"><button className="btn">Tema ver</button></div></form></div>
    <div className="panel"><table><thead><tr><th>Tema</th><th>Kategori</th><th>Temel fiyat</th><th>Paket kuralları</th><th>Kurulum</th><th>Durum</th><th></th></tr></thead><tbody>{themes.map((t:any)=><tr key={t.id}><td><b>{t.name}</b><div className="muted">{t.slug}</div></td><td>{t.category}</td><td>{Number(t.basePrice||0).toLocaleString('tr-TR')} {t.currency}</td><td>{t.planPrices?.length||0}</td><td>{t._count?.installations||0}</td><td>{t.isActive?'Aktif':'Pasif'}{t.isDefault?' · Varsayılan':''}</td><td><div className="sa-table-actions"><button className="btn secondary" onClick={()=>setEdit(t)}>Düzenle</button><button className="btn secondary" onClick={()=>void run(()=>req('/superadmin/themes/'+t.id,{method:'PATCH',body:JSON.stringify({isActive:!t.isActive})}),t.isActive?'Tema kapatıldı.':'Tema açıldı.')}>{t.isActive?'Kapat':'Aç'}</button></div></td></tr>)}</tbody></table></div>
    {edit!==null&&<div className="sa-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><div className="sa-modal"><div className="sa-modal-head"><div><h2>{edit?.id?'Temayı düzenle':'Yeni tema'}</h2><p className="muted">Müşterinin göreceği isim ve ticari ayarlar.</p></div><button className="btn secondary" onClick={()=>setEdit(null)}>Kapat</button></div><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));const payload={name:f.name,slug:f.slug,category:f.category,description:f.description,basePrice:Number(f.basePrice||0),currency:f.currency,billingType:'ONE_TIME',isFeatured:f.isFeatured==='true',isDefault:f.isDefault==='true',isActive:true,sortOrder:Number(f.sortOrder||0)};const ok=await run(()=>edit?.id?req('/superadmin/themes/'+edit.id,{method:'PATCH',body:JSON.stringify(payload)}):req('/superadmin/themes',{method:'POST',body:JSON.stringify(payload)}),edit?.id?'Tema güncellendi.':'Tema eklendi.');if(ok)setEdit(null)}}><label>Tema adı<input name="name" defaultValue={edit?.name||''} required/></label><label>Slug<input name="slug" defaultValue={edit?.slug||''} required={!edit?.id} readOnly={!!edit?.id}/></label><label>Kategori<input name="category" defaultValue={edit?.category||'GENEL'}/></label><label>Temel fiyat<input name="basePrice" type="number" min="0" step="0.01" defaultValue={edit?.basePrice??0}/></label><label>Para birimi<select name="currency" defaultValue={edit?.currency||'TRY'}><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Öne çıkan<select name="isFeatured" defaultValue={String(!!edit?.isFeatured)}><option value="false">Hayır</option><option value="true">Evet</option></select></label><label>Varsayılan<select name="isDefault" defaultValue={String(!!edit?.isDefault)}><option value="false">Hayır</option><option value="true">Evet</option></select></label><label>Sıra<input name="sortOrder" type="number" defaultValue={edit?.sortOrder??0}/></label><label className="full">Açıklama<textarea name="description" defaultValue={edit?.description||''}/></label><div className="full sa-modal-actions"><button type="button" className="btn secondary" onClick={()=>setEdit(null)}>Vazgeç</button><button className="btn">Kaydet</button></div></form></div></div>}
  </>;
}

function ReservedSubdomainControl({rows,req,reload}:any){
  const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  async function run(fn:()=>Promise<any>,ok:string){setMsg('');setErr('');try{await fn();setMsg(ok);await reload()}catch(e:any){setErr(e.message||'İşlem başarısız')}}
  return <>
    {msg&&<div className="success">{msg}</div>}{err&&<div className="error">{err}</div>}
    <div className="panel"><h3>Blokeli alt alan adları</h3><p className="muted">Bu listedeki adlar mağazalar tarafından <b>xxxx.ticarti.com</b> olarak seçilemez. Kilitli sistem kayıtları kapatılamaz.</p>
      <form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/reserved-subdomains',{method:'POST',body:JSON.stringify({value:f.value,reason:f.reason,isActive:true})}),'Alt alan adı bloke edildi.');e.currentTarget.reset()}}>
        <label>Alt alan adı<input name="value" placeholder="kampanya" required minLength={2} maxLength={63}/></label><label>Açıklama<input name="reason" placeholder="Platform kullanımı"/></label><div className="full"><button className="btn">Listeye ekle</button></div>
      </form>
    </div>
    <div className="panel"><table><thead><tr><th>Alt alan adı</th><th>Açıklama</th><th>Durum</th><th>Tür</th><th></th></tr></thead><tbody>{(rows||[]).map((x:any)=><tr key={x.id}><td><b>{x.value}.ticarti.com</b></td><td>{x.reason||'-'}</td><td>{x.isActive?'Blokeli':'Serbest'}</td><td>{x.locked?'Sistem':'Özel'}</td><td><div className="sa-table-actions"><button className="btn secondary" disabled={x.locked} onClick={()=>void run(()=>req('/superadmin/reserved-subdomains/'+x.id,{method:'PATCH',body:JSON.stringify({isActive:!x.isActive})}),x.isActive?'Alt alan adı serbest bırakıldı.':'Alt alan adı bloke edildi.')}>{x.isActive?'Serbest bırak':'Bloke et'}</button>{!x.locked&&<button className="btn secondary" onClick={()=>void run(()=>req('/superadmin/reserved-subdomains/'+x.id,{method:'DELETE'}),'Kayıt silindi.')}>Sil</button>}</div></td></tr>)}</tbody></table></div>
  </>;
}

function AppControl({apps,req,reload}:any){
  const[plans,setPlans]=useState<any[]>([]);const[tenants,setTenants]=useState<any[]>([]);const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[editor,setEditor]=useState<any|null>(null);
  useEffect(()=>{Promise.all([req('/superadmin/plans'),req('/superadmin/tenants')]).then(([p,t])=>{setPlans(p);setTenants(t)}).catch((e:any)=>setErr(e.message))},[]);
  async function run(fn:()=>Promise<any>,ok:string){setErr('');setMsg('');try{await fn();setMsg(ok);await reload();return true}catch(e:any){setErr(e.message);return false}}
  return <>
    {msg&&<div className="success">{msg}</div>}{err&&<div className="error">{err}</div>}
    <div className="panel"><div className="toolbar"><div><h3 style={{margin:'0 0 6px'}}>Uygulama kataloğu</h3><p className="muted" style={{margin:0}}>Kod yükleme yok. Uygulamanın mağaza kartını, açıklamasını, logosunu ve ekran görüntülerini buradan yönet.</p></div><button className="btn" onClick={()=>setEditor({})}>Yeni uygulama</button></div></div>

    <div className="panel"><h3>Pakete göre fiyat / dahil et</h3><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/apps/'+f.appId+'/plan-pricing',{method:'POST',body:JSON.stringify({planId:f.planId,price:f.price===''?null:Number(f.price),currency:f.currency,billingType:f.billingType,included:f.included==='true',isActive:true})}),'Paket fiyatı kaydedildi.')}}><label>Uygulama<select name="appId" required>{apps.map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Paket<select name="planId" required>{plans.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Fiyat<input name="price" type="number" min="0" step="0.01" placeholder="Boş = uygulama temel fiyatı"/></label><label>Para birimi<select name="currency"><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Ücret tipi<select name="billingType"><option value="MONTHLY">Aylık</option><option value="YEARLY">Yıllık</option><option value="ONE_TIME">Tek sefer</option><option value="FREE">Ücretsiz</option></select></label><label>Pakete dahil<select name="included"><option value="false">Hayır</option><option value="true">Evet</option></select></label><div className="full"><button className="btn">Paket fiyatını kaydet</button></div></form></div>

    <div className="panel"><h3>Mağazaya doğrudan uygulama ekle</h3><p className="muted">Bu işlem ödeme kontrolünü atlar ve uygulamayı doğrudan müşterinin Uygulamalarım ekranına ekler.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/tenants/'+f.tenantId+'/apps/'+f.appId+'/grant',{method:'POST',body:'{}'}),'Uygulama mağazaya eklendi.')}}><label>Firma / mağaza<select name="tenantId" required>{tenants.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Uygulama<select name="appId" required>{apps.map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><div className="full"><button className="btn">Uygulamayı ekle</button></div></form></div>

    <div className="panel"><h3>Uygulamalar</h3><table><thead><tr><th>Uygulama</th><th>Kategori</th><th>Temel fiyat</th><th>Paket fiyatları</th><th>Kurulum</th><th>Durum</th><th></th></tr></thead><tbody>{apps.map((a:any)=>{const market=a.settingsSchema?.marketplace||{};return <tr key={a.id}><td><div className="sa-app-cell">{market.logoUrl?<img src={market.logoUrl} alt=""/>:<span className="sa-app-fallback">APP</span>}<div><b>{a.name}</b><div className="muted">{a.slug}</div></div></div></td><td>{a.category}</td><td>{Number(a.basePrice||0).toLocaleString('tr-TR')} {a.currency}</td><td>{(a.planPrices||[]).length?(a.planPrices||[]).map((x:any)=><div key={x.id}>{x.plan?.name}: {x.included?'Dahil':x.price===null||x.price===undefined?'Temel fiyat':`${Number(x.price).toLocaleString('tr-TR')} ${x.currency||a.currency}`}</div>):'-'}</td><td>{a._count?.installs||0}</td><td>{a.isActive?'Aktif':'Pasif'}</td><td><div className="sa-table-actions"><button className="btn secondary" onClick={()=>setEditor(a)}>Düzenle</button><button className="btn secondary" onClick={()=>void run(()=>req('/superadmin/apps/'+a.id,{method:'PATCH',body:JSON.stringify({isActive:!a.isActive})}),a.isActive?'Uygulama pasife alındı.':'Uygulama aktifleştirildi.')}>{a.isActive?'Pasife al':'Aktifleştir'}</button></div></td></tr>})}</tbody></table></div>
    {editor!==null&&<AppEditorModal app={editor} onClose={()=>setEditor(null)} onSave={async payload=>{const ok=await run(()=>editor.id?req('/superadmin/apps/'+editor.id,{method:'PATCH',body:JSON.stringify(payload)}):req('/superadmin/apps',{method:'POST',body:JSON.stringify(payload)}),editor.id?'Uygulama güncellendi.':'Uygulama mağaza kataloğuna eklendi.');if(ok)setEditor(null)}}/>}
  </>;
}

function AppEditorModal({app,onClose,onSave}:any){
  const market=app?.settingsSchema?.marketplace||{};const[busy,setBusy]=useState(false);
  return <div className="sa-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="sa-modal"><div className="sa-modal-head"><div><h2>{app?.id?'Uygulamayı düzenle':'Yeni uygulama'}</h2><p className="muted">Eklenti mağazasında görünen tüm bilgileri burada hazırlayın.</p></div><button className="btn secondary" onClick={onClose}>Kapat</button></div><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await onSave({name:f.name,slug:f.slug,category:f.category,summary:f.summary,description:f.description,usageGuide:f.usageGuide,logoUrl:f.logoUrl,screenshots:f.screenshots,developer:f.developer||'WE DID IT',kind:f.kind,integrationType:f.integrationType||null,provider:f.provider||null,icon:f.icon||'iconoir:puzzle',basePrice:Number(f.basePrice||0),currency:f.currency||'TRY',billingType:f.billingType,isFeatured:f.isFeatured==='true',sortOrder:Number(f.sortOrder||0),isActive:true})}finally{setBusy(false)}}}>
      <label>Uygulama adı<input name="name" defaultValue={app?.name||''} required/></label><label>Slug<input name="slug" defaultValue={app?.slug||''} required={!app?.id} readOnly={!!app?.id} placeholder="ornek-uygulama"/></label>
      <label>Kategori<select name="category" defaultValue={app?.category||'Diğer'}><option>AI</option><option>Pazarlama</option><option>Pazaryeri</option><option>Kargo</option><option>Fatura & Muhasebe</option><option>Ödeme</option><option>CRM</option><option>Analitik</option><option>Diğer</option></select></label><label>Tür<select name="kind" defaultValue={app?.kind||'INTEGRATION'}><option value="INTEGRATION">Entegrasyon</option><option value="AI">AI</option><option value="TOOL">Araç</option></select></label>
      <label>Entegrasyon tipi<select name="integrationType" defaultValue={app?.integrationType||''}><option value="">Yok</option><option>MARKETPLACE</option><option>PAYMENT</option><option>SHIPPING</option><option>INVOICE</option><option>MARKETING</option><option>AI</option><option>SOCIAL</option><option>ANALYTICS</option><option>MESSAGING</option><option>CRM</option></select></label><label>Provider kodu<input name="provider" defaultValue={app?.provider||''} placeholder="trendyol, yurtici, ..."/></label>
      <label>Başlangıç fiyatı<input name="basePrice" type="number" min="0" step="0.01" defaultValue={app?.basePrice??0}/></label><label>Ücret tipi<select name="billingType" defaultValue={app?.billingType||'FREE'}><option value="FREE">Ücretsiz</option><option value="MONTHLY">Aylık</option><option value="YEARLY">Yıllık</option><option value="ONE_TIME">Tek sefer</option></select></label>
      <label>Para birimi<select name="currency" defaultValue={app?.currency||'TRY'}><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Geliştirici<input name="developer" defaultValue={app?.developer||'WE DID IT'}/></label>
      <label>İkon<input name="icon" defaultValue={app?.icon||'iconoir:puzzle'}/></label><label>Logo URL<input name="logoUrl" defaultValue={market.logoUrl||''} placeholder="https://.../logo.png"/></label>
      <label>Öne çıkan<select name="isFeatured" defaultValue={String(!!app?.isFeatured)}><option value="false">Hayır</option><option value="true">Evet</option></select></label><label>Sıra<input name="sortOrder" type="number" defaultValue={app?.sortOrder??0}/></label>
      <label className="full">Kısa açıklama<textarea name="summary" defaultValue={app?.summary||''} required/></label><label className="full">Detaylı açıklama<textarea name="description" defaultValue={app?.description||''}/></label><label className="full">Nasıl kullanılır?<textarea name="usageGuide" defaultValue={market.usageGuide||''} placeholder={'1. Uygulamayı ekleyin\n2. Ayarlardan hesabınızı bağlayın\n3. Senkronizasyonu başlatın'}/></label><label className="full">Ekran görüntüleri <span className="muted">(her satıra bir URL)</span><textarea name="screenshots" defaultValue={Array.isArray(market.screenshots)?market.screenshots.join('\n'):''} placeholder={'https://.../screen-1.jpg\nhttps://.../screen-2.jpg'}/></label>
      <div className="full sa-modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Vazgeç</button><button className="btn" disabled={busy}>{busy?'Kaydediliyor…':app?.id?'Değişiklikleri Kaydet':'Uygulamayı Ekle'}</button></div>
    </form></div></div>;
}

function TenantControl({tenants,req,reload}:any){const[plans,setPlans]=useState<any[]>([]);useEffect(()=>{req('/superadmin/plans').then(setPlans)},[]);return <div className="panel"><h3>Firma yönetimi</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));await req('/superadmin/tenants/'+f.tenantId,{method:'PATCH',body:JSON.stringify({status:f.status})});if(f.planId)await req('/superadmin/tenants/'+f.tenantId+'/subscription',{method:'POST',body:JSON.stringify({planId:f.planId,status:'ACTIVE'})});reload()}}><label>Firma<select name="tenantId" required>{tenants.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Durum<select name="status"><option>ACTIVE</option><option>TRIAL</option><option>SUSPENDED</option><option>CANCELLED</option></select></label><label>Paket<select name="planId"><option value="">Değiştirme</option>{plans.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="full"><button className="btn">Uygula</button></div></form></div>}

function PlanForm({req,reload}:any){const features=[['promotions','Gelişmiş promosyon'],['multiCurrency','Çoklu para birimi'],['loyalty','Sadakat'],['marketing','E-posta / SMS / Popup'],['privacy','KVKK / GDPR araçları'],['customDomain','Özel domain'],['api','API erişimi'],['prioritySupport','Öncelikli destek']];return <div className="panel"><h3>Paket oluştur</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const f:any=Object.fromEntries(fd);const enabled=new Set(fd.getAll('features').map(String));const featureMap=Object.fromEntries(features.map(([key])=>[key,enabled.has(key)]));await req('/superadmin/plans',{method:'POST',body:JSON.stringify({name:f.name,code:f.code,monthlyPrice:Number(f.monthlyPrice||0),yearlyPrice:Number(f.yearlyPrice||0),maxStaff:Number(f.maxStaff||3),maxProducts:Number(f.maxProducts||1000),maxOrdersPerMonth:f.maxOrdersPerMonth?Number(f.maxOrdersPerMonth):null,features:{...featureMap,coupons:true,reviews:true,pages:true}})});e.currentTarget.reset();reload()}}><label>Ad<input name="name" required/></label><label>Kod<input name="code" required/></label><label>Aylık fiyat<input name="monthlyPrice" type="number" min="0"/></label><label>Yıllık fiyat<input name="yearlyPrice" type="number" min="0"/></label><label>Personel limiti<input name="maxStaff" type="number" min="1" defaultValue="3"/></label><label>Ürün limiti<input name="maxProducts" type="number" min="1" defaultValue="1000"/></label><label>Aylık sipariş limiti<input name="maxOrdersPerMonth" type="number" min="1"/></label><div className="full"><b>Paket özellikleri</b><div className="feature-grid">{features.map(([key,label])=><label className="feature-check" key={key}><input type="checkbox" name="features" value={key} defaultChecked/>{label}</label>)}</div></div><div className="full"><button className="btn">Paketi oluştur</button></div></form></div>}
function SupportControl({tickets,req,reload}:any){return <div className="panel"><h3>Destek talebi yanıtla</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));await req('/superadmin/support/tickets/'+f.ticketId,{method:'PATCH',body:JSON.stringify({status:f.status,message:f.message})});e.currentTarget.reset();reload()}}><label>Talep<select name="ticketId" required>{tickets.map((t:any)=><option key={t.id} value={t.id}>{t.tenant?.name} — {t.subject}</option>)}</select></label><label>Durum<select name="status"><option>IN_PROGRESS</option><option>WAITING_CUSTOMER</option><option>RESOLVED</option><option>CLOSED</option></select></label><label className="full">Yanıt<textarea name="message" required/></label><div className="full"><button className="btn">Yanıtla</button></div></form></div>}

function get(o:any,path:string){return path.split('.').reduce((a,k)=>Array.isArray(a)&&/^\d+$/.test(k)?a[Number(k)]:a?.[k],o)}
function Table({rows,cols}:{rows:any[],cols:[string,string][]}){return <table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=>{let v=get(r,c[0]);if(c[0].includes('At')&&v)v=new Date(v).toLocaleString('tr-TR');if(typeof v==='boolean')v=v?'Evet':'Hayır';return <td key={c[0]}>{String(v??'-')}</td>})}</tr>)}</tbody></table>}
