'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import ProductCard from '../components/ProductCard';
import {api,STORE,getCurrency,getLocale,mediaUrl} from '../lib/api';

function cleanHtml(v:any){return String(v||'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/\son\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/javascript\s*:/gi,'')}
function take(v:any,n:any){return (Array.isArray(v)?v:[]).slice(0,Math.max(1,Number(n||8)))}

export default function Home(){
  const[d,setD]=useState<any>(null);const[e,setE]=useState('');const[draftSections,setDraftSections]=useState<any[]|null>(null);
  async function load(){api('/storefront/'+STORE+'?currency='+encodeURIComponent(getCurrency())+'&locale='+encodeURIComponent(getLocale())).then(setD).catch(x=>setE(x.message))}
  useEffect(()=>{load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[]);
  useEffect(()=>{const h=(event:any)=>{const detail=event?.detail;if(detail?.kind==='sections'&&Array.isArray(detail.sections))setDraftSections(detail.sections);if(detail?.kind==='section'&&detail.section)setDraftSections(current=>{const base=current||((d?.sections&&Array.isArray(d.sections))?d.sections:[]);const id=String(detail.section.id);return base.map((x:any)=>String(x.id)===id?detail.section:x)})};window.addEventListener('ticarti-design-draft',h as EventListener);return()=>window.removeEventListener('ticarti-design-draft',h as EventListener)},[d]);
  if(e)return <main className="container section"><div className="error">{e}</div></main>;if(!d)return <main className="container section">Mağaza yükleniyor…</main>;
  const persisted=Array.isArray(d.sections)?d.sections:[];const sections=draftSections||persisted;
  return <main className="home-modular"><div className="home-section-grid">{sections.filter((x:any)=>x.enabled!==false).map((section:any)=><div key={section.id} className="design-section-anchor" data-design-target={'section:'+section.id} data-design-label={String(section.settings?.title||section.sectionType||'Bölüm')}><HomeSection section={section} data={d}/></div>)}</div></main>;
}

function HomeSection({section,data}:{section:any;data:any}){
  const s=section.settings||{};const rawType=section.sectionType;const aliases:any={featured_collection:'products',featured_collection_row:'product_slider',product_grid:'products',product_list:'products',recommendations:'products',recently_viewed:'products',collection_list:'categories',popular_categories:'categories',media_text:'image_text',media_text_vertical:'image_text',rich_text:'html',custom_html:'html',testimonials:'reviews',testimonials_large:'reviews',brands_grid:'brands',brands_list:'brands',blog_posts:'blog',icon_features:'icon_columns',masonry_gallery:'gallery',shop_the_look:'lookbook',video_hero:'slider'};const type=aliases[rawType]||rawType;const style:any={'--home-col-d':Math.min(12,Math.max(1,Number(s.colDesktop||12))),'--home-col-t':Math.min(12,Math.max(1,Number(s.colTablet||12))),'--home-col-m':Math.min(12,Math.max(1,Number(s.colMobile||12))),textAlign:s.textAlign||'left',background:s.background&&s.background!=='transparent'?s.background:undefined};
  if(rawType==='slider'||rawType==='video_hero') return <ThemeSlider s={s} data={data} style={style}/>;
  if(rawType==='featured_collection_tabs'||rawType==='product_vertical_tabs')return <ProductTabs s={s} data={data} style={style} vertical={rawType==='product_vertical_tabs'}/>;
  if(rawType==='product_banner_list')return <ProductBannerList s={s} data={data} style={style}/>;
  if(['collection_spotlight','collection_text','collection_image_text'].includes(rawType))return <CategoryFeature s={s} data={data} style={style} mode={rawType}/>;
  if(rawType==='hover_image_list')return <HoverImageList s={s} data={data} style={style}/>;
  if(rawType==='media_collage')return <MediaCollage s={s} data={data} style={style}/>;
  if(rawType==='banner_text_outside'||rawType==='discount_banner')return <PromoBanner s={s} data={data} style={style} compact={rawType==='discount_banner'}/>;
  if(rawType==='lookbook'||rawType==='shop_the_look')return <Lookbook s={s} data={data} style={style}/>;
  if(rawType==='image_comparison')return <ImageComparison s={s} data={data} style={style}/>;
  if(rawType==='ticker_collection'){const items=take(data.categories,s.count||10);return <section className="home-module home-theme-ticker ticker-categories" style={style}><div className="home-theme-ticker-track">{[...items,...items].map((item:any,i:number)=><Link key={i} href={'/products?category='+item.slug}>{item.name}</Link>)}</div></section>}
  if(rawType==='tags'){const tags=Array.isArray(s.items)&&s.items.length?s.items:[{title:'Yeni Gelenler'},{title:'Çok Satanlar'},{title:'İndirimdekiler'},{title:'Editörün Seçimi'}];return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Popüler Aramalar"/><div className="home-tags">{tags.map((item:any,i:number)=><Link key={i} href={item.linkUrl||'/products?q='+encodeURIComponent(item.title||item.text||'')}>{item.title||item.text}</Link>)}</div></div></section>}
  if(rawType==='map')return <section className="home-module" style={style}><div className="container home-map"><div><ModuleHead s={s} fallback="Mağazamızı ziyaret edin"/><p>{s.content||data.store?.settings?.addressText||'Mağaza konum ve iletişim bilgileri.'}</p>{s.linkUrl&&<a className="btn" href={s.linkUrl} target="_blank" rel="noreferrer">Yol tarifi al</a>}</div><div className="home-map-canvas"><span>⌖</span><b>{s.locationTitle||data.store?.name}</b></div></div></section>;
  if(rawType==='free_shipping_bar')return <section className="home-module home-shipping-bar" style={style}><div className="container"><b>{s.title||'Ücretsiz kargo fırsatı'}</b><span>{s.content||'Belirlenen sepet tutarının üzerindeki siparişlerde ücretsiz teslimat.'}</span>{s.linkUrl&&<Link href={s.linkUrl}>Detaylar →</Link>}</div></section>;
  if(rawType==='banner_collage'){
    const items=Array.isArray(s.items)?s.items:[];const fallback=data.categories||[];const rows=(items.length?items:Array.from({length:6},()=>({}))).slice(0,6);
    return <section className={'home-module home-banner-collage variant-'+String(s.variant||'mosaic-6')} style={style}><div className="container"><ModuleHead s={s} fallback=""/><div className="home-banner-collage-grid">{rows.map((item:any,i:number)=>{const cat=fallback[i];const image=item.imageUrl||cat?.imageUrl;return <Link href={item.linkUrl||(cat?`/products?category=${cat.slug}`:'/products')} key={i} className="home-banner-tile" style={{backgroundImage:image?`linear-gradient(180deg,transparent 35%,rgba(0,0,0,.48)),url(${image})`:undefined}}><b>{item.title||cat?.name||'Koleksiyon'}</b>{item.buttonText&&<span>{item.buttonText}</span>}</Link>})}</div></div></section>
  }
  if(rawType==='ticker_text'){
    const items=Array.isArray(s.items)&&s.items.length?s.items:[{text:s.title||s.content||'Yeni sezon'}];
    return <section className={'home-module home-theme-ticker variant-'+String(s.variant||'marquee')} style={style}><div className="home-theme-ticker-track">{[...items,...items].map((item:any,i:number)=><span key={i}>{item.text||item.title}</span>)}</div></section>
  }
  if(rawType==='shoppable_feed'){
    const products=take(data.featured,s.count||8);return <section className="home-module home-shoppable-feed" style={style}><div className="container"><ModuleHead s={s} fallback="Görsel Akış"/><div className="home-shoppable-grid">{products.map((p:any)=>{const img=p.images?.[0]?.url;return <Link key={p.id} href={'/products/'+p.slug} className="home-shoppable-item">{img?<picture><source srcSet={mediaUrl(img,'card','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(img,'card','webp')} alt={p.title}/></picture>:<i/>}<span>{p.title}</span></Link>})}</div></div></section>
  }
  const hero=data.banners?.find((x:any)=>x.position==='home_hero');
  if(type==='hero'||type==='banner')return <section className={'home-module home-module-'+type} style={style}><div className="home-hero-module" style={{backgroundImage:(s.imageUrl||hero?.imageUrl)?`linear-gradient(90deg,rgba(20,24,30,.14),rgba(20,24,30,.04)),url(${s.imageUrl||hero.imageUrl})`:undefined}}><div className="container"><div className="home-hero-copy">{(s.subtitle||hero?.subtitle)&&<span>{s.subtitle||hero?.subtitle}</span>}{(s.title||hero?.title||data.store?.settings?.homeTitle)&&<h1>{s.title||hero?.title||data.store?.settings?.homeTitle}</h1>}{s.content&&<p>{s.content}</p>}{(s.buttonText||hero?.buttonText)&&(s.linkUrl||hero?.buttonUrl)&&<Link className="btn" href={s.linkUrl||hero?.buttonUrl}>{s.buttonText||hero?.buttonText}</Link>}</div></div></div></section>;
  if(type==='categories'||type==='category_slider')return <section className={'home-module '+(type==='category_slider'?'home-slider-module':'')} style={style}><div className="container"><ModuleHead s={s} fallback="Kategoriler"/><div className="home-category-list">{take(data.categories,s.count||10).map((c:any)=><Link key={c.id} href={'/products?category='+c.slug} className="home-category-card">{c.imageUrl&&<picture><source srcSet={mediaUrl(c.imageUrl,'category','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(c.imageUrl,'category','webp')} alt={c.name}/></picture>}<b>{c.name}</b></Link>)}</div></div></section>;
  if(type==='products'||type==='product_slider')return <section className={'home-module '+(type==='product_slider'?'home-slider-module':'')} style={style}><div className="container"><ModuleHead s={s} fallback="Ürünler"/><div className={'home-products '+(type==='product_slider'?'home-products-slider':'')}>{take(data.featured,s.count||8).map((p:any)=><ProductCard key={p.id} p={p} currency={data.store.currency}/>)}</div></div></section>;
  if(type==='featured_product'){const p=data.featured?.[0];return <section className="home-module" style={style}><div className="container">{p?<div className="home-featured-product"><div>{p.images?.[0]?.url&&<picture><source srcSet={mediaUrl(p.images[0].url,'detail','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(p.images[0].url,'detail','webp')} alt={p.title}/></picture>}</div><div><span>ÖNE ÇIKAN</span><h2>{s.title||p.title}</h2><p>{s.content||p.shortDescription||p.description}</p><Link className="btn" href={'/products/'+p.slug}>Ürünü incele</Link></div></div>:null}</div></section>}
  if(type==='reviews')return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Müşteriler ne diyor?"/><div className="home-review-grid">{take(data.reviews,s.count||4).map((r:any)=><article key={r.id}><div className="home-stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><p>{r.body||r.title}</p><b>{r.authorName||'Müşteri'}</b>{r.verifiedPurchase&&<small>Doğrulanmış alışveriş</small>}</article>)}</div></div></section>;
  if(type==='blog')return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Blog"/><div className="home-blog-grid">{take(data.blogPosts,s.count||3).map((b:any)=><Link href={'/blog/'+b.slug} key={b.id} className="home-blog-card">{b.featuredImageUrl?<picture><source srcSet={mediaUrl(b.featuredImageUrl,'card','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(b.featuredImageUrl,'card','webp')} alt={b.title}/></picture>:<i/>}<b>{b.title}</b><p>{b.excerpt}</p></Link>)}</div></div></section>;
  if(type==='brands')return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Markalar"/><div className="home-brand-list">{take(data.brands,s.count||10).map((b:any)=><Link key={b.id} href={'/products?brand='+b.slug}>{b.logoUrl?<img loading="lazy" decoding="async" src={mediaUrl(b.logoUrl,'thumb','webp')} alt={b.name}/>:<b>{b.name}</b>}</Link>)}</div></div></section>;
  if(type==='image_text')return <section className="home-module" style={style}><div className="container home-image-text"><div className="home-image-text-media">{s.imageUrl?<picture><source srcSet={mediaUrl(s.imageUrl,'detail','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(s.imageUrl,'detail','webp')} alt={s.title||''}/></picture>:null}</div><div><ModuleHead s={s} fallback=""/>{s.content&&<p>{s.content}</p>}{s.linkUrl&&<Link className="btn" href={s.linkUrl}>{s.buttonText||'İncele'}</Link>}</div></div></section>;
  if(type==='html')return <section className="home-module" style={style}><div className="container custom-html-block" dangerouslySetInnerHTML={{__html:cleanHtml(s.html||s.content)}}/></section>;
  if(type==='newsletter')return <section className="home-module" style={style}><div className="container home-newsletter"><div><ModuleHead s={s} fallback="Bültene katıl"/></div><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="E-posta adresiniz"/><button className="btn">Kaydol</button></form></div></section>;
  if(type==='instagram'||type==='twitter')return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback={type==='instagram'?'Instagram':'X / Twitter'}/><div className="home-social-feed">{s.handle&&<b>{s.handle}</b>}{s.content&&<p>{s.content}</p>}{s.linkUrl&&<a className="btn alt" href={s.linkUrl} target="_blank" rel="noreferrer">{s.buttonText||s.handle||'Profil'}</a>}</div></div></section>;
  if(type==='video')return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Video"/>{s.videoUrl?<video className="home-video" controls src={s.videoUrl}/>:null}</div></section>;
  if(type==='countdown')return <section className="home-module" style={style}><div className="container home-countdown"><ModuleHead s={s} fallback=""/>{s.endsAt&&<div><b>{new Date(s.endsAt).toLocaleString()}</b></div>}</div></section>;
  if(type==='trust_badges'){const items=Array.isArray(s.items)?s.items:[];return items.length?<section className="home-module" style={style}><div className="container home-trust-grid">{items.map((item:any,i:number)=><div key={i}>{item.title&&<b>{item.title}</b>}{item.text&&<span>{item.text}</span>}</div>)}</div></section>:null;}
  if(type==='announcement')return <section className="home-module" style={style}><div className="container home-announcement">{s.title&&<b>{s.title}</b>}{(s.content||s.subtitle)&&<span>{s.content||s.subtitle}</span>}</div></section>;
  if(type==='spacer')return <div className="home-module home-spacer" style={{...style,height:Math.max(20,Number(s.height||60))}}/>;
  if(type==='divider')return <div className="home-module" style={style}><div className="container"><hr/></div></div>;
  if(type==='promo_cards'){const items=Array.isArray(s.items)?s.items:[];return items.length?<section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback=""/><div className="home-promo-grid">{items.map((item:any,i:number)=><div key={i}>{item.title&&<b>{item.title}</b>}{item.text&&<span>{item.text}</span>}</div>)}</div></div></section>:null;}
  if(type==='accordion'){const items=Array.isArray(s.items)?s.items:[];return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Sık Sorulan Sorular"/><div className="home-accordion">{items.map((item:any,i:number)=><details key={i}><summary>{item.title||`Başlık ${i+1}`}</summary><div>{item.text||item.content||''}</div></details>)}</div></div></section>}
  if(type==='counter'){const items=Array.isArray(s.items)?s.items:[];return <section className="home-module" style={style}><div className="container home-counter-grid">{items.map((item:any,i:number)=><div key={i}><strong>{item.value||0}</strong><span>{item.title||item.label||''}</span></div>)}</div></section>}
  if(type==='icon_columns'){const items=Array.isArray(s.items)?s.items:[];return <section className="home-module" style={style}><div className="container home-icon-columns">{items.map((item:any,i:number)=><div key={i}><b>{item.title||''}</b><span>{item.text||''}</span></div>)}</div></section>}
  if(type==='gallery'||type==='collage'||type==='lookbook'){const source=Array.isArray(s.items)&&s.items.some((x:any)=>x?.imageUrl)?s.items:take(data.featured,s.count||8).map((p:any)=>({imageUrl:p.images?.[0]?.url,alt:p.title,linkUrl:'/products/'+p.slug}));return <section className={'home-module home-gallery-module variant-'+String(s.variant||'grid')} style={style}><div className="container"><ModuleHead s={s} fallback=""/><div className="home-gallery-grid">{source.map((item:any,i:number)=>item.imageUrl?(item.linkUrl?<Link href={item.linkUrl} key={i}><picture><source srcSet={mediaUrl(item.imageUrl,'card','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(item.imageUrl,'card','webp')} alt={item.alt||s.title||''}/></picture></Link>:<picture key={i}><source srcSet={mediaUrl(item.imageUrl,'card','avif')} type="image/avif"/><img loading="lazy" decoding="async" src={mediaUrl(item.imageUrl,'card','webp')} alt={item.alt||s.title||''}/></picture>):null)}</div></div></section>}
  if(type==='image_comparison')return <section className="home-module" style={style}><div className="container home-image-comparison">{s.beforeImage&&<img loading="lazy" decoding="async" src={mediaUrl(s.beforeImage,'detail','webp')} alt="Önce"/>}{s.afterImage&&<img loading="lazy" decoding="async" src={mediaUrl(s.afterImage,'detail','webp')} alt="Sonra"/>}</div></section>;
  if(type==='contact_form')return <section className="home-module" style={style}><div className="container home-contact-module"><ModuleHead s={s} fallback="İletişim"/><form onSubmit={e=>e.preventDefault()}><input placeholder="Ad Soyad"/><input type="email" placeholder="E-posta"/><textarea placeholder="Mesaj"/><button className="btn">Gönder</button></form></div></section>;
  return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback={type}/>{s.content&&<p>{s.content}</p>}</div></section>;
}

function ProductTabs({s,data,style,vertical=false}:{s:any;data:any;style:any;vertical?:boolean}){
  const categories=take(data.categories,Math.min(6,s.tabCount||4));const[active,setActive]=useState('all');
  const products=take(data.featured,s.count||10);const visible=active==='all'?products:products.filter((p:any)=>p.categories?.some((x:any)=>String(x.category?.slug||x.slug)===active));
  return <section className={'home-module home-product-tabs '+(vertical?'is-vertical':'')} style={style}><div className="container"><ModuleHead s={s} fallback="Öne Çıkanlar"/><div className="home-tab-layout"><div className="home-tab-buttons"><button className={active==='all'?'active':''} onClick={()=>setActive('all')}>Tümü</button>{categories.map((c:any)=><button key={c.id} className={active===c.slug?'active':''} onClick={()=>setActive(c.slug)}>{c.name}</button>)}</div><div className="home-products">{(visible.length?visible:products).map((p:any)=><ProductCard key={p.id} p={p} currency={data.store.currency}/>)}</div></div></div></section>;
}

function ProductBannerList({s,data,style}:{s:any;data:any;style:any}){
  const hero=s.imageUrl||data.banners?.find((x:any)=>x.position==='home_hero')?.imageUrl||data.categories?.[0]?.imageUrl;
  return <section className={'home-module home-product-banner variant-'+String(s.variant||'banner-left')} style={style}><div className="container"><ModuleHead s={s} fallback="Sizin İçin Seçtik"/><div className="home-product-banner-layout"><Link href={s.linkUrl||'/products'} className="home-product-banner-media" style={{backgroundImage:hero?`linear-gradient(180deg,transparent,rgba(0,0,0,.55)),url(${hero})`:undefined}}><span>{s.subtitle||'KOLEKSİYON'}</span><b>{s.bannerTitle||s.title||'Yeni seçki'}</b><em>{s.buttonText||'Keşfet'} →</em></Link><div className="home-products">{take(data.featured,s.count||6).map((p:any)=><ProductCard key={p.id} p={p} currency={data.store.currency}/>)}</div></div></div></section>;
}

function CategoryFeature({s,data,style,mode}:{s:any;data:any;style:any;mode:string}){
  const categories=take(data.categories,s.count||6);
  return <section className={'home-module home-category-feature '+mode+' variant-'+String(s.variant||'default')} style={style}><div className="container"><ModuleHead s={s} fallback="Koleksiyonlar"/><div className="home-category-feature-grid">{categories.map((c:any,i:number)=><Link key={c.id} href={'/products?category='+c.slug} className="home-category-feature-card"><div>{c.imageUrl?<img loading="lazy" decoding="async" src={mediaUrl(c.imageUrl,'category','webp')} alt={c.name}/>:<i/>}<span>{String(i+1).padStart(2,'0')}</span></div><b>{c.name}</b><small>Koleksiyonu gör →</small></Link>)}</div></div></section>;
}

function HoverImageList({s,data,style}:{s:any;data:any;style:any}){
  const categories=take(data.categories,s.count||5);const[active,setActive]=useState(0);const current=categories[active]||categories[0];
  return <section className="home-module home-hover-list" style={style}><div className="container"><ModuleHead s={s} fallback="Koleksiyonları keşfedin"/><div className="home-hover-list-layout"><div>{categories.map((c:any,i:number)=><Link onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} className={active===i?'active':''} key={c.id} href={'/products?category='+c.slug}><span>{String(i+1).padStart(2,'0')}</span><b>{c.name}</b><em>↗</em></Link>)}</div><div className="home-hover-list-media">{current?.imageUrl?<img key={current.id} src={mediaUrl(current.imageUrl,'detail','webp')} alt={current.name}/>:<i/>}</div></div></div></section>;
}

function MediaCollage({s,data,style}:{s:any;data:any;style:any}){
  const items=Array.isArray(s.items)&&s.items.length?s.items:take(data.categories,3).map((c:any)=>({imageUrl:c.imageUrl,title:c.name,linkUrl:'/products?category='+c.slug}));
  return <section className={'home-module home-media-collage variant-'+String(s.variant||'story')} style={style}><div className="container"><ModuleHead s={s} fallback="Marka Hikayesi"/><div className="home-media-collage-grid"><div className="home-media-collage-copy"><span>{s.subtitle||'HİKAYEMİZ'}</span><h3>{s.collageTitle||s.title||'Detaylarda saklı tasarım'}</h3><p>{s.content||'Koleksiyonunuzun hissini güçlü görseller ve dengeli boşluklarla anlatın.'}</p>{s.linkUrl&&<Link className="btn alt" href={s.linkUrl}>{s.buttonText||'Daha fazla'}</Link>}</div>{items.slice(0,3).map((item:any,i:number)=><Link key={i} href={item.linkUrl||'/products'}>{item.imageUrl?<img loading="lazy" decoding="async" src={mediaUrl(item.imageUrl,'detail','webp')} alt={item.title||''}/>:<i/>}<b>{item.title}</b></Link>)}</div></div></section>;
}

function PromoBanner({s,data,style,compact}:{s:any;data:any;style:any;compact?:boolean}){
  const image=s.imageUrl||data.banners?.[0]?.imageUrl||data.categories?.[0]?.imageUrl;
  return <section className={'home-module home-promo-banner '+(compact?'is-compact':'')} style={style}><div className="container"><div className="home-promo-banner-layout"><div className="home-promo-banner-media" style={{backgroundImage:image?`url(${image})`:undefined}}/><div className="home-promo-banner-copy"><span>{s.subtitle||'SINIRLI SÜRE'}</span><h2>{s.title||'Sezon fırsatını keşfedin'}</h2><p>{s.content||'Seçili ürünlerde özel fiyatlar ve yeni koleksiyonlar.'}</p>{s.endsAt&&<Countdown end={s.endsAt}/>}<Link className="btn" href={s.linkUrl||'/products'}>{s.buttonText||'Şimdi keşfet'}</Link></div></div></div></section>;
}

function Countdown({end}:{end:any}){const[left,setLeft]=useState('');useEffect(()=>{const update=()=>{const ms=Math.max(0,new Date(end).getTime()-Date.now());const d=Math.floor(ms/86400000);const h=Math.floor(ms/3600000)%24;const m=Math.floor(ms/60000)%60;const sec=Math.floor(ms/1000)%60;setLeft(`${d}G ${String(h).padStart(2,'0')}S ${String(m).padStart(2,'0')}D ${String(sec).padStart(2,'0')}SN`)};update();const id=window.setInterval(update,1000);return()=>window.clearInterval(id)},[end]);return <strong className="home-countdown-live">{left}</strong>}

function Lookbook({s,data,style}:{s:any;data:any;style:any}){
  const products=take(data.featured,s.count||4);const image=s.imageUrl||products[0]?.images?.[0]?.url||data.categories?.[0]?.imageUrl;const points=Array.isArray(s.items)&&s.items.length?s.items:products.slice(0,4).map((p:any,i:number)=>({x:[24,66,38,76][i],y:[30,26,68,72][i],productIndex:i}));
  return <section className="home-module home-lookbook" style={style}><div className="container"><ModuleHead s={s} fallback="Görünümü Keşfet"/><div className="home-lookbook-stage">{image&&<img loading="lazy" decoding="async" src={mediaUrl(image,'hero','webp')} alt={s.title||''}/>} {points.map((point:any,i:number)=>{const p=products[Number(point.productIndex??i)%Math.max(1,products.length)];return <div className="lookbook-point" style={{left:`${Number(point.x||50)}%`,top:`${Number(point.y||50)}%`}} key={i}><button aria-label={p?.title||'Ürünü gör'}>{i+1}</button>{p&&<Link href={'/products/'+p.slug}><b>{p.title}</b><span>Ürünü incele →</span></Link>}</div>})}</div></div></section>;
}

function ImageComparison({s,data,style}:{s:any;data:any;style:any}){
  const[value,setValue]=useState(50);const before=s.beforeImage||data.featured?.[0]?.images?.[0]?.url;const after=s.afterImage||data.featured?.[1]?.images?.[0]?.url||before;
  return <section className="home-module" style={style}><div className="container"><ModuleHead s={s} fallback="Detayları karşılaştırın"/><div className="home-image-comparison interactive">{before&&<img src={mediaUrl(before,'detail','webp')} alt={s.beforeLabel||'Önce'}/>}<div style={{width:`${value}%`}}>{after&&<img src={mediaUrl(after,'detail','webp')} alt={s.afterLabel||'Sonra'}/>}</div><input aria-label="Görsel karşılaştırma" type="range" min="0" max="100" value={value} onChange={e=>setValue(Number(e.target.value))}/><span style={{left:`${value}%`}}/></div></div></section>;
}

function ThemeSlider({s,data,style}:{s:any;data:any;style:any}){
  const slides=Array.isArray(s.items)&&s.items.length?s.items:[{title:s.title,subtitle:s.subtitle,content:s.content,buttonText:s.buttonText,linkUrl:s.linkUrl,imageUrl:s.imageUrl}];
  const[index,setIndex]=useState(0);
  useEffect(()=>{if(!s.autoplay||slides.length<2)return;const ms=Math.max(2500,Number(s.autoplaySeconds||5)*1000);const t=window.setInterval(()=>setIndex(x=>(x+1)%slides.length),ms);return()=>window.clearInterval(t)},[s.autoplay,s.autoplaySeconds,slides.length]);
  const go=(n:number)=>setIndex((n+slides.length)%slides.length);
  return <section className={'home-module home-theme-slider variant-'+String(s.variant||'wide')} style={style}>
    <div className="home-theme-slider-viewport">
      <div className="home-theme-slider-track" style={{transform:`translate3d(-${index*100}%,0,0)`}}>{slides.map((slide:any,i:number)=>{const image=slide.imageUrl||data.banners?.[i]?.imageUrl||data.categories?.[i]?.imageUrl;return <article className="home-theme-slide" key={i} style={{'--slide-height':`${Number(s.heightDesktop||560)}px`,backgroundImage:image?`linear-gradient(90deg,rgba(10,12,16,.38),rgba(10,12,16,.03)),url(${image})`:undefined} as any}>{slide.videoUrl&&<video className="home-theme-slide-video" src={slide.videoUrl} autoPlay muted loop playsInline/>}<div className="container"><div className="home-theme-slide-copy">{slide.subtitle&&<span>{slide.subtitle}</span>}<h1>{slide.title||data.store?.name}</h1>{slide.content&&<p>{slide.content}</p>}{(slide.buttonText||slide.linkUrl)&&<Link className="btn" href={slide.linkUrl||'/products'}>{slide.buttonText||'Keşfet'}</Link>}</div></div></article>})}</div>
      {slides.length>1&&<><button type="button" className="theme-slider-arrow prev" aria-label="Önceki slayt" onClick={()=>go(index-1)}>‹</button><button type="button" className="theme-slider-arrow next" aria-label="Sonraki slayt" onClick={()=>go(index+1)}>›</button></>}
    </div>
    {slides.length>1&&<div className="home-theme-slider-dots">{slides.map((_:any,i:number)=><button type="button" aria-label={`${i+1}. slayt`} className={i===index?'active':''} onClick={()=>go(i)} key={i}/>)}</div>}
  </section>
}

function ModuleHead({s,fallback}:{s:any;fallback:string}){const title=s.title||fallback;return (title||s.subtitle||s.linkUrl)?<div className="home-module-head"><div>{s.subtitle&&<span>{s.subtitle}</span>}{title&&<h2>{title}</h2>}</div>{s.linkUrl&&<Link href={s.linkUrl}>{s.buttonText||'Tümünü gör'} →</Link>}</div>:null}
