'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {api,getCartToken,money} from '../../lib/api';

type AccessMode='REQUIRED'|'SUGGESTED'|'GUEST';

export default function Cart(){
  const router=useRouter();
  const[c,setC]=useState<any>(null);const[code,setCode]=useState('');const[err,setErr]=useState('');const[busy,setBusy]=useState(false);const[gate,setGate]=useState(false);const[loggedIn,setLoggedIn]=useState(false);
  async function load(){const t=getCartToken();if(!t){setC({items:[],totals:{grandTotal:0,currency:'TRY'},store:{checkoutConfig:{customerAccessMode:'GUEST'}}});return}try{setC(await api('/storefront/carts/'+t))}catch(e:any){setErr(e.message)}}
  useEffect(()=>{void load();api('/storefront/customer/refresh',{method:'POST',credentials:'include',body:'{}'}).then(()=>setLoggedIn(true)).catch(()=>setLoggedIn(false));const h=()=>void load();window.addEventListener('currency-change',h);return()=>window.removeEventListener('currency-change',h)},[]);
  async function qty(id:string,q:number){try{setBusy(true);await api(`/storefront/carts/${getCartToken()}/items/${id}`,{method:'PATCH',body:JSON.stringify({quantity:q})});await load();window.dispatchEvent(new Event('cart-change'))}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  async function discount(){try{setBusy(true);await api(`/storefront/carts/${getCartToken()}/discount`,{method:'POST',body:JSON.stringify({code})});setCode('');await load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  function checkout(){const mode=(c?.store?.checkoutConfig?.customerAccessMode||'GUEST') as AccessMode;if(loggedIn||mode==='GUEST'){router.push('/checkout');return}setGate(true)}
  if(!c)return <main className="container section">Sepet hazırlanıyor…</main>;
  const cur=c.totals?.currency||c.currency||'TRY';const mode=(c?.store?.checkoutConfig?.customerAccessMode||'GUEST') as AccessMode;
  return <main className="cart-page"><div className="container"><div className="cart-title-row"><div><h1>Sepetiniz</h1><p>{c.items.length?`${c.items.reduce((a:number,x:any)=>a+x.quantity,0)} ürün`:'Sepetinizde ürün bulunmuyor.'}</p></div><Link href="/products" className="cart-continue">Alışverişe devam et</Link></div>{err&&<div className="error">{err}</div>}
    {!c.items.length?<div className="cart-empty"><div className="cart-empty-icon">🛍️</div><h2>Sepetiniz boş</h2><p>Beğendiğiniz ürünleri sepete eklediğinizde burada göreceksiniz.</p><Link className="btn" href="/products">Ürünleri keşfet</Link></div>:<div className="cart-layout">
      <section className="cart-list-card">
        {c.items.map((i:any)=><div className="cart-final-row" key={i.id}><Link href={`/products/${i.variant.product.slug}`} className="cart-product-image product-image-wrap"><img src={i.variant.product.images?.[0]?.url||'https://placehold.co/160'} alt={i.variant.product.title}/>{i.variant.product.images?.[0]?.aiGenerated&&<span className="product-ai-badge" title="AI ile oluşturuldu">AI</span>}</Link><div className="cart-product-info"><Link href={`/products/${i.variant.product.slug}`}><h3>{i.variant.product.title}</h3></Link><p>{i.variant.title}</p><button type="button" className="cart-remove" onClick={()=>void qty(i.id,0)} disabled={busy}>Kaldır</button></div><div className="cart-qty"><button type="button" disabled={busy||i.quantity<=1} onClick={()=>void qty(i.id,i.quantity-1)}>−</button><span>{i.quantity}</span><button type="button" disabled={busy} onClick={()=>void qty(i.id,i.quantity+1)}>+</button></div><strong className="cart-line-price">{money(Number(i.variant.price)*i.quantity,cur)}</strong></div>)}
        {c.promotionGifts?.map((g:any)=><div className="cart-final-row cart-gift" key={g.variantId}><div className="cart-product-image product-image-wrap"><img src={g.product?.images?.[0]?.url||'https://placehold.co/160'} alt=""/>{g.product?.images?.[0]?.aiGenerated&&<span className="product-ai-badge" title="AI ile oluşturuldu">AI</span>}</div><div className="cart-product-info"><h3>{g.title}</h3><p>Promosyon hediyesi</p></div><div className="cart-qty cart-qty-static">{g.quantity} adet</div><strong className="cart-line-price">{money(0,cur)}</strong></div>)}
      </section>
      <aside className="cart-summary-card"><h2>Sipariş özeti</h2><div className="cart-summary-line"><span>Ara toplam</span><b>{money(c.totals.subtotal,cur)}</b></div>{Number(c.totals.discountTotal)>0&&<div className="cart-summary-line discount"><span>İndirim</span><b>-{money(c.totals.discountTotal,cur)}</b></div>}<div className="cart-summary-line"><span>Kargo</span><span className="muted">Ödeme adımında</span></div><div className="cart-summary-total"><span>Toplam</span><b>{money(c.totals.grandTotal,cur)}</b></div>{c.totals.appliedPromotions?.length>0&&<div className="cart-promotions">{c.totals.appliedPromotions.map((p:any)=><span key={p.id}>✓ {p.name}</span>)}</div>}<div className="cart-coupon"><label>İndirim kodu</label><div><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Kupon kodu"/><button type="button" onClick={()=>void discount()} disabled={busy||!code.trim()}>Uygula</button></div></div><button type="button" className="cart-checkout-button" onClick={checkout}>Ödemeye geç</button><div className="cart-assurance"><span>🔒 Güvenli ödeme</span><span>↩ Kolay iade süreci</span></div></aside>
    </div>}
  </div>
  {gate&&<div className="cart-gate-backdrop" onMouseDown={()=>setGate(false)}><div className="cart-gate" onMouseDown={e=>e.stopPropagation()}><button className="cart-gate-close" onClick={()=>setGate(false)} aria-label="Kapat">×</button>{mode==='REQUIRED'?<><div className="cart-gate-badge">Hesap gerekli</div><h2>Ödeme için giriş yapın veya üye olun</h2><p>Bu mağaza ödeme öncesinde müşteri hesabı kullanılmasını zorunlu tutuyor. Sepetiniz korunacak.</p><Link className="btn cart-gate-primary" href="/account?mode=login&return=/checkout">Giriş yap</Link><Link className="btn secondary cart-gate-primary" href="/account?mode=register&return=/checkout">Üye ol</Link></>:<><div className="cart-gate-badge">Daha hızlı alışveriş</div><h2>Nasıl devam etmek istersiniz?</h2><p>Üye olarak siparişlerinizi ve adreslerinizi hesabınızdan takip edebilirsiniz. İsterseniz misafir olarak da devam edebilirsiniz.</p><div className="cart-gate-actions"><Link className="btn" href="/account?mode=login&return=/checkout">Giriş yap</Link><Link className="btn secondary" href="/account?mode=register&return=/checkout">Üye ol</Link></div><button className="cart-guest-button" onClick={()=>router.push('/checkout')}>Misafir olarak devam et</button></>}</div></div>}
  </main>
}
