'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import ProductCard from '../../../components/ProductCard';
import {api,STORE,getCartToken,setCartToken,money,getCurrency,getLocale,mediaUrl,track} from '../../../lib/api';

export default function Product(){
  const {slug}=useParams<{slug:string}>();const[p,setP]=useState<any>(null);const[v,setV]=useState('');const[err,setErr]=useState('');const[qty,setQty]=useState(1);const[activeImage,setActiveImage]=useState(0);const[busy,setBusy]=useState(false);const[liked,setLiked]=useState(false);const[tab,setTab]=useState<'description'|'details'|'reviews'>('description');const[lightbox,setLightbox]=useState(false);const[sizeChart,setSizeChart]=useState(false);const[related,setRelated]=useState<any[]>([]);
  async function load(){api(`/storefront/${STORE}/products/${slug}?currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`).then((x:any)=>{setP(x);setV(old=>old&&x.variants?.some((z:any)=>z.id===old)?old:(x.variants?.[0]?.id||''));track('view_item',{item_id:x.id,item_name:x.title,value:Number(x.variants?.[0]?.price||0),currency:x.displayCurrency});try{const a=JSON.parse(localStorage.getItem('ticarti-wishlist')||'[]');setLiked(a.includes(String(x.id)));const recent=JSON.parse(localStorage.getItem('ticarti-recent')||'[]').filter((id:string)=>id!==String(x.id));localStorage.setItem('ticarti-recent',JSON.stringify([String(x.id),...recent].slice(0,12)))}catch{};api(`/storefront/${STORE}/products?limit=8&currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`).then((r:any)=>setRelated((r.items||[]).filter((item:any)=>item.id!==x.id).slice(0,4))).catch(()=>{})}).catch(x=>setErr(x.message))}
  useEffect(()=>{void load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[slug]);
  const variant=p?.variants?.find((x:any)=>x.id===v)||p?.variants?.[0];const stock=Math.max(0,(variant?.inventory?.onHand||0)-(variant?.inventory?.reserved||0));
  const discount=variant?.comparePrice&&Number(variant.comparePrice)>Number(variant.price)?Math.round((1-Number(variant.price)/Number(variant.comparePrice))*100):0;
  const average=useMemo(()=>{const a=p?.reviews||[];return a.length?a.reduce((n:number,r:any)=>n+Number(r.rating||0),0)/a.length:0},[p?.reviews]);
  async function add(){if(!v||busy)return;setBusy(true);try{let t=getCartToken();if(!t){const c=await api(`/storefront/${STORE}/carts`,{method:'POST',body:JSON.stringify({currency:getCurrency()})});t=c.token;setCartToken(t)}await api(`/storefront/carts/${t}/items`,{method:'POST',body:JSON.stringify({variantId:v,quantity:qty})});track('add_to_cart',{item_id:p?.id,item_name:p?.title,variant_id:v,value:Number(variant?.price||0),currency:p?.displayCurrency,quantity:qty});window.dispatchEvent(new Event('cart-change'))}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  function toggleLike(){if(!p)return;let arr:string[]=[];try{arr=JSON.parse(localStorage.getItem('ticarti-wishlist')||'[]')}catch{};arr=arr.includes(String(p.id))?arr.filter(x=>x!==String(p.id)):[...arr,String(p.id)];localStorage.setItem('ticarti-wishlist',JSON.stringify(arr));setLiked(arr.includes(String(p.id)))}
  if(err&&!p)return <main className="container section"><div className="error">{err}</div></main>;if(!p)return <main className="container section">Ürün yükleniyor…</main>;
  const images=Array.isArray(p.images)?p.images:[];
  return <main className="product-page container">
    <div className="product-breadcrumb"><Link href="/">Anasayfa</Link><span>/</span><Link href="/products">Ürünler</Link><span>/</span>{p.title}</div>
    <div className="product-layout product-layout-advanced">
      <div className="product-gallery-shell"><div className="product-thumbs">{images.map((x:any,i:number)=><button key={x.id||i} className={activeImage===i?'active':''} onClick={()=>setActiveImage(i)}>{x.url&&<img src={mediaUrl(x.url,'thumb','webp')} alt=""/>}</button>)}</div><button className="product-gallery-main" onClick={()=>images.length&&setLightbox(true)} aria-label="Ürün görselini büyüt">{images.length?<picture><source srcSet={mediaUrl(images[activeImage]?.url,'detail','avif')} type="image/avif"/><img decoding="async" fetchPriority="high" src={mediaUrl(images[activeImage]?.url,'detail','webp')} alt={images[activeImage]?.alt||p.title}/></picture>:<span className="product-image-empty"/>}{discount>0&&<span className="product-detail-sale">-%{discount}</span>}<span className="product-zoom-hint">⌕ Büyüt</span></button></div>
      <div className="product-info product-info-advanced"><div className="product-meta-top"><span>{p.brand?.name||'Koleksiyon'}</span>{p.sku&&<span>SKU: {p.sku}</span>}</div><h1>{p.title}</h1>{p.reviews?.length>0&&<button className="product-rating" onClick={()=>setTab('reviews')}>{'★'.repeat(Math.round(average))}{'☆'.repeat(5-Math.round(average))}<span>{p.reviews.length} değerlendirme</span></button>}<div className="price product-detail-price">{money(variant?.price,p.displayCurrency)} {variant?.comparePrice&&<span className="old">{money(variant.comparePrice,p.displayCurrency)}</span>}</div><p className="product-short">{p.shortDescription||p.description}</p>
        {p.variants?.length>1&&<div className="product-variants"><div className="product-variant-head"><b>Seçenek</b><button onClick={()=>setSizeChart(true)}>Ölçü rehberi</button></div><div>{p.variants.map((x:any)=><button className={v===x.id?'active':''} key={x.id} onClick={()=>setV(x.id)}>{x.title}</button>)}</div></div>}
        <div className={`product-stock ${stock>0?'in':'out'}`}><i/>{stock>0?`Stokta · ${stock} adet`:'Stokta yok'}</div>
        <div className="product-buy-row"><div className="qty-control"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button onClick={()=>setQty(qty+1)}>+</button></div><button className="btn product-add-btn" disabled={busy||stock<1} onClick={()=>void add()}>{busy?'Ekleniyor…':'Sepete ekle'}</button></div>
        <div className="product-secondary-actions"><button onClick={toggleLike}>{liked?'♥ Favorilerde':'♡ Favorilere ekle'}</button><button onClick={()=>navigator.share?.({title:p.title,url:location.href})}>↗ Paylaş</button></div>
        <div className="product-benefits"><div><b>Güvenli ödeme</b><span>Ödeme bilgileriniz güvenle işlenir.</span></div><div><b>Hızlı teslimat</b><span>Teslimat seçenekleri ödeme adımında gösterilir.</span></div><div><b>Kolay iade</b><span>İade koşullarınızı inceleyebilirsiniz.</span></div></div>
        {stock>0&&<div className="product-pickup"><span>✓</span><div><b>Mağazadan teslim alınabilir</b><small>Uygun teslim noktaları ödeme adımında gösterilir.</small></div></div>}
      </div>
    </div>
    <section className="product-tabs"><div className="product-tab-head"><button className={tab==='description'?'active':''} onClick={()=>setTab('description')}>Açıklama</button><button className={tab==='details'?'active':''} onClick={()=>setTab('details')}>Ürün bilgileri</button><button className={tab==='reviews'?'active':''} onClick={()=>setTab('reviews')}>Değerlendirmeler ({p.reviews?.length||0})</button></div>{tab==='description'&&<div className="product-tab-body"><p>{p.description||p.shortDescription}</p></div>}{tab==='details'&&<div className="product-tab-body product-specs"><div><span>Marka</span><b>{p.brand?.name||'—'}</b></div><div><span>Stok</span><b>{stock}</b></div><div><span>Varyant</span><b>{variant?.title||'Standart'}</b></div></div>}{tab==='reviews'&&<div className="product-tab-body product-review-list">{p.reviews?.length?p.reviews.map((r:any)=><article key={r.id}><b>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</b><p>{r.body}</p><small>{r.authorName||'Müşteri'}</small></article>):<p>Henüz değerlendirme yok.</p>}</div>}</section>
    {related.length>0&&<section className="product-recommendations"><div className="product-recommendations-head"><span>SİZİN İÇİN</span><h2>Bunları da beğenebilirsiniz</h2></div><div className="home-products">{related.map((item:any)=><ProductCard key={item.id} p={item} currency={p.displayCurrency}/>)}</div></section>}
    <div className="product-sticky-buy"><div><b>{p.title}</b><span>{money(variant?.price,p.displayCurrency)}</span></div><button className="btn" disabled={busy||stock<1} onClick={()=>void add()}>Sepete ekle</button></div>
    {lightbox&&<div className="product-lightbox" role="dialog" aria-modal="true" onClick={()=>setLightbox(false)}><button onClick={()=>setLightbox(false)} aria-label="Kapat">×</button><button className="lightbox-prev" onClick={e=>{e.stopPropagation();setActiveImage((activeImage-1+images.length)%images.length)}}>‹</button><img onClick={e=>e.stopPropagation()} src={mediaUrl(images[activeImage]?.url,'hero','webp')} alt={images[activeImage]?.alt||p.title}/><button className="lightbox-next" onClick={e=>{e.stopPropagation();setActiveImage((activeImage+1)%images.length)}}>›</button></div>}
    {sizeChart&&<div className="size-chart-backdrop" role="dialog" aria-modal="true" onClick={()=>setSizeChart(false)}><div className="size-chart" onClick={e=>e.stopPropagation()}><button onClick={()=>setSizeChart(false)} aria-label="Kapat">×</button><span>ÖLÇÜ REHBERİ</span><h2>Doğru seçeneği bulun</h2><p>Ürün seçenekleri ve ölçüler satıcı tarafından tanımlanır. Ayrıntılı bilgi için ürün açıklamasını kontrol edin.</p><table><tbody><tr><th>Seçenek</th><th>Öneri</th></tr>{p.variants.map((x:any)=><tr key={x.id}><td>{x.title}</td><td>Ürün ölçüsünü açıklamada kontrol edin</td></tr>)}</tbody></table></div></div>}
  </main>
}
