'use client';

import {Icon} from '@iconify/react';

function statusLabel(v:string){const m:Record<string,string>={PENDING_PAYMENT:'Ödeme bekleniyor',PENDING:'Bekliyor',PAID:'Ödendi',PROCESSING:'Hazırlanıyor',FULFILLED:'Tamamlandı',CANCELLED:'İptal',REFUNDED:'İade',FAILED:'Başarısız',UNFULFILLED:'Hazırlanmadı',SHIPPED:'Kargoda',DELIVERED:'Teslim edildi'};return m[v]||v||'-'}
function statusClass(v:string){if(['PAID','FULFILLED','DELIVERED','APPROVED','ACTIVE'].includes(v))return'success';if(['CANCELLED','FAILED','REJECTED'].includes(v))return'danger';if(['PROCESSING','SHIPPED'].includes(v))return'info';return'warning'}
function money(v:any,currency?:string){const n=Number(v||0);if(currency){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency,maximumFractionDigits:2}).format(n)}catch{}}return new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(n)}
function date(v:any){if(!v)return'-';return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}

export default function AdminDashboard({data,onNavigate}:{data:any;onNavigate?:(tab:string)=>void}){
 const m=data?.metrics||{};const orders=Array.isArray(data?.recentOrders)?data.recentOrders:[];const months=Array.isArray(data?.monthlyRevenue)?data.monthlyRevenue:[];const currency=data?.currency||'TRY';
 const max=Math.max(1,...months.map((row:any)=>Number(row.amount||0)));
 const paid=orders.filter((o:any)=>o.paymentStatus==='PAID').length;const pending=Math.max(0,orders.length-paid);
 const guest=orders.filter((o:any)=>!o.customer).length;const known=Math.max(0,orders.length-guest);
 const stats=[
  {title:'Aylık Ciro',value:money(m.revenue,currency),sub:'Ödenmiş siparişler',icon:'iconoir:wallet',tone:'success',action:'Raporlar'},
  {title:'Siparişler',value:new Intl.NumberFormat('tr-TR').format(Number(m.orders||0)),sub:'Bu ay oluşan',icon:'iconoir:cart',tone:'info',action:'Siparişler'},
  {title:'Aktif Ürün',value:new Intl.NumberFormat('tr-TR').format(Number(m.products||0)),sub:'Satışta olan ürün',icon:'iconoir:box-iso',tone:'secondary',action:'Katalog'},
  {title:'Müşteriler',value:new Intl.NumberFormat('tr-TR').format(Number(m.customers||0)),sub:'Kayıtlı müşteri',icon:'iconoir:group',tone:'warning',action:'Müşteriler'},
 ];
 return <div className="rizz-ecom-dashboard">
   <div className="row g-3">
     <div className="col-xl-4">
       <div className="rizz-ecom-stat-stack">{stats.map((s,index)=><article className="card rizz-ecom-stat" key={s.title}><div className="card-body"><div className="rizz-ecom-stat-top"><span className={`rizz-ecom-stat-icon ${s.tone}`}><Icon icon={s.icon}/></span><div className="rizz-ecom-spark" aria-hidden="true">{[28,48,35,63,42,75,52,82,68,90].map((h,i)=><i key={i} style={{height:`${Math.max(18,Math.min(96,h+(index*4)))}%`}}/>)}</div></div><h6>{s.title}</h6><div className="rizz-ecom-stat-bottom"><div><strong>{s.value}</strong><small>{s.sub}</small></div><button type="button" className="btn btn-sm btn-light" onClick={()=>onNavigate?.(s.action)}>Görüntüle</button></div></div></article>)}</div>
     </div>
     <div className="col-xl-8">
       <section className="card h-100 rizz-ecom-income"><div className="card-header"><div><h5 className="card-title mb-1">Aylık Sipariş Cirosu</h5><small className="text-muted">Ödenmiş siparişlerin son 12 aylık toplamı</small></div><button type="button" className="btn btn-light btn-sm" onClick={()=>onNavigate?.('Raporlar')}><Icon icon="iconoir:stats-up-square" className="me-1"/>Raporu Aç</button></div><div className="card-body pt-0"><div className="rizz-ecom-income-chart monthly">{months.length?months.map((row:any,i:number)=><div className="rizz-ecom-income-col" key={row.key||i} title={`${row.label}: ${money(row.amount,currency)} · ${row.orders} sipariş`}><span>{Number(row.amount||0)>0?money(row.amount,currency):'—'}</span><div><i style={{height:`${Number(row.amount||0)>0?Math.max(7,(Number(row.amount||0)/max)*100):2}%`}}/></div><small>{row.label}</small></div>):<div className="rizz-ecom-empty">Aylık ciro verisi henüz oluşmadı.</div>}</div><div className="row g-2 mt-2"><div className="col-md-4"><div className="rizz-ecom-mini"><span>Bu Ay Ciro</span><strong>{money(m.revenue,currency)}</strong></div></div><div className="col-md-4"><div className="rizz-ecom-mini"><span>Bu Ay Sipariş</span><strong>{Number(m.orders||0)}</strong></div></div><div className="col-md-4"><div className="rizz-ecom-mini"><span>Düşük Stok</span><strong className={Number(m.lowStock||0)>0?'text-danger':''}>{Number(m.lowStock||0)}</strong></div></div></div></div></section>
     </div>
   </div>

   <div className="row g-3 mt-0">
     <div className="col-xl-8">
       <section className="card rizz-ecom-orders"><div className="card-header"><div><h5 className="card-title mb-1">Son Siparişler</h5><small className="text-muted">Sipariş, müşteri, ödeme ve toplam bilgisi</small></div><button type="button" className="btn btn-light btn-sm" onClick={()=>onNavigate?.('Siparişler')}>Tümünü Gör</button></div><div className="card-body pt-0"><div className="table-responsive"><table className="table align-middle mb-0"><thead className="table-light"><tr><th>Sipariş</th><th>Müşteri</th><th>Durum</th><th>Ödeme</th><th className="text-end">Tutar</th></tr></thead><tbody>{orders.length?orders.map((o:any)=><tr key={o.id||o.number}><td><strong>#{o.number}</strong><small>{date(o.createdAt)}</small></td><td><div className="rizz-ecom-customer"><span>{String(o.customer?.firstName||o.customer?.email||'M').slice(0,1).toUpperCase()}</span><div><b>{[o.customer?.firstName,o.customer?.lastName].filter(Boolean).join(' ')||'Misafir müşteri'}</b><small>{o.customer?.email||'-'}</small></div></div></td><td><span className={`badge bg-${statusClass(o.status)}-subtle text-${statusClass(o.status)}`}>{statusLabel(o.status)}</span></td><td><span className={`badge bg-${statusClass(o.paymentStatus)}-subtle text-${statusClass(o.paymentStatus)}`}>{statusLabel(o.paymentStatus)}</span></td><td className="text-end"><strong>{money(o.grandTotal,currency)}</strong></td></tr>):<tr><td colSpan={5} className="text-center text-muted py-5">Henüz sipariş yok.</td></tr>}</tbody></table></div></div></section>
     </div>
     <div className="col-xl-4">
       <section className="card h-100 rizz-ecom-customers"><div className="card-header"><h5 className="card-title mb-0">Müşteriler</h5><span className="rizz-ecom-avatars"><i>M</i><i>S</i><i>A</i><b>+{Math.max(0,Number(m.customers||0)-3)}</b></span></div><div className="card-body pt-0"><div className="rizz-ecom-donut" style={{background:`conic-gradient(var(--bs-primary) 0 ${orders.length?known/orders.length*100:50}%, #08b0e7 ${orders.length?known/orders.length*100:50}% ${orders.length?100:75}%, #eef1f5 0)`}}><div><strong>{Number(m.customers||0)}</strong><span>Toplam</span></div></div><div className="rizz-ecom-legend"><span><i className="primary"/>Kayıtlı sipariş <b>{known}</b></span><span><i className="info"/>Misafir sipariş <b>{guest}</b></span></div><button type="button" className="btn btn-light w-100 mt-3" onClick={()=>onNavigate?.('Müşteriler')}>Müşterileri Yönet</button></div></section>
     </div>
   </div>

   <div className="row g-3 mt-0">
     <div className="col-md-4"><section className="card rizz-ecom-bottom-card"><div className="card-header"><h5 className="card-title mb-0">Stok Durumu</h5></div><div className="card-body pt-0"><div className={`rizz-ecom-alert ${Number(m.lowStock||0)>0?'danger':'success'}`}><span><Icon icon={Number(m.lowStock||0)>0?'iconoir:warning-triangle':'iconoir:check-circle'}/></span><div><strong>{Number(m.lowStock||0)>0?`${m.lowStock} düşük stok kaydı`:'Stoklar sağlıklı'}</strong><small>{Number(m.lowStock||0)>0?'Kritik stokları kontrol edin.':'Kritik stok uyarısı yok.'}</small></div></div><button className="btn btn-light w-100" type="button" onClick={()=>onNavigate?.('Katalog')}>Kataloğu Aç</button></div></section></div>
     <div className="col-md-4"><section className="card rizz-ecom-bottom-card"><div className="card-header"><h5 className="card-title mb-0">Ödeme Özeti</h5></div><div className="card-body pt-0"><div className="rizz-ecom-progress-row"><span>Ödenen</span><b>{paid}</b></div><div className="progress"><div className="progress-bar" style={{width:`${orders.length?paid/orders.length*100:0}%`}}/></div><div className="rizz-ecom-progress-row mt-3"><span>Bekleyen / diğer</span><b>{pending}</b></div><div className="progress"><div className="progress-bar bg-warning" style={{width:`${orders.length?pending/orders.length*100:0}%`}}/></div></div></section></div>
     <div className="col-md-4"><section className="card rizz-ecom-bottom-card"><div className="card-header"><h5 className="card-title mb-0">Hızlı İşlemler</h5></div><div className="card-body pt-0"><div className="rizz-ecom-quick"><button onClick={()=>onNavigate?.('Katalog')}><span><Icon icon="iconoir:plus"/></span><div><b>Ürün ekle</b><small>Kataloğa yeni ürün</small></div><Icon icon="iconoir:nav-arrow-right"/></button><button onClick={()=>onNavigate?.('Promosyonlar')}><span><Icon icon="iconoir:percentage-circle"/></span><div><b>Promosyon oluştur</b><small>İndirim ve kampanya</small></div><Icon icon="iconoir:nav-arrow-right"/></button><button onClick={()=>onNavigate?.('Raporlar')}><span><Icon icon="iconoir:stats-report"/></span><div><b>Raporları incele</b><small>Mağaza performansı</small></div><Icon icon="iconoir:nav-arrow-right"/></button></div></div></section></div>
   </div>
 </div>
}
