'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Icon } from '@iconify/react';
import { useAdminSession } from './AdminSession';

const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
type Msg={role:'user'|'assistant';text:string;action?:any};
const suggestions=['Ürün ekle','Kategori ekle','Promosyon oluştur','Blog yazısı ekle','Ayarları aç'];

export default function AiAssistantDrawer(){const router=useRouter();const{session,refreshSession,installedApps,appsLoaded}=useAdminSession();const installed=installedApps.some(x=>x.app?.slug==='we-ai-assistant'&&x.enabled&&x.status==='ACTIVE');const[open,setOpen]=useState(false);const[assistantName,setAssistantName]=useState('AI Asistan');const[enabled,setEnabled]=useState(true);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Sana nasıl yardımcı olabilirim? Ürün, kategori veya promosyon oluşturabilir; yönetim ekranlarında yol gösterebilirim.'}]);
 useEffect(()=>{if(!session||!installed)return;let live=true;const run=async()=>{try{const r=await fetch(API+'/admin/ai/status',{credentials:'include',headers:{authorization:`Bearer ${session.accessToken}`,'x-tenant-id':session.tenantId}});if(!r.ok)return;const j=await r.json();if(live){setAssistantName(j?.config?.assistantName||'AI Asistan');setEnabled(j?.config?.assistantEnabled!==false)}}catch{}};void run();return()=>{live=false}},[session?.accessToken,session?.tenantId,installed]);
 async function api(path:string,body:any){if(!session)throw new Error('Oturum yok');const run=(token:string,tenant:string)=>fetch(API+path,{method:'POST',credentials:'include',headers:{'content-type':'application/json',authorization:`Bearer ${token}`,'x-tenant-id':tenant},body:JSON.stringify(body)});let active=session;let r=await run(active.accessToken,active.tenantId);if(r.status===401){const n=await refreshSession();if(!n)throw new Error('Oturum süresi doldu');active=n;r=await run(n.accessToken,n.tenantId)}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'AI işlemi başarısız');return j}
 async function send(value=text){const q=value.trim();if(!q||busy)return;setMessages(x=>[...x,{role:'user',text:q}]);setText('');setBusy(true);try{const r=await api('/admin/ai/assistant',{storeId:session?.storeId,message:q,history:messages.slice(-8)});setMessages(x=>[...x,{role:'assistant',text:r.message||'Tamam.',action:r.action||undefined}])}catch(e:any){setMessages(x=>[...x,{role:'assistant',text:e.message||'AI yanıt veremedi.'}])}finally{setBusy(false)}}
 async function execute(action:any){setBusy(true);try{const r=await api('/admin/ai/assistant/execute',{storeId:session?.storeId,action});setMessages(x=>[...x,{role:'assistant',text:'İşlem tamamlandı.'}]);if(r.href)router.push(r.href)}catch(e:any){setMessages(x=>[...x,{role:'assistant',text:e.message||'İşlem uygulanamadı.'}])}finally{setBusy(false)}}
 function voice(){const W:any=window;const C=W.SpeechRecognition||W.webkitSpeechRecognition;if(!C){setMessages(x=>[...x,{role:'assistant',text:'Bu tarayıcı sesli girişi desteklemiyor.'}]);return}const rec=new C();rec.lang='tr-TR';rec.interimResults=false;rec.onresult=(e:any)=>{const v=String(e.results?.[0]?.[0]?.transcript||'');setText(v);void send(v)};rec.start()}
 if(!appsLoaded||!installed)return null;
 return <><button type="button" className="ai-fab" onClick={()=>setOpen(true)} aria-label="AI Asistan"><Icon icon="iconoir:robot"/></button>{open&&<><div className="ai-drawer-backdrop" onClick={()=>setOpen(false)}/><aside className="ai-drawer"><div className="ai-drawer-head"><div className="d-flex align-items-center gap-2"><span className="ai-robot-mark"><Icon icon="iconoir:robot"/></span><div><b>{assistantName}</b><small>{enabled?'Commerce yönetim yardımcısı':'AI Asistan şu anda kapalı'}</small></div></div><button className="btn btn-sm btn-light" onClick={()=>setOpen(false)}><Icon icon="iconoir:xmark"/></button></div><div className="ai-drawer-suggestions">{suggestions.map(s=><button key={s} onClick={()=>void send(s)} disabled={!enabled||busy}>{s}</button>)}</div><div className="ai-chat">{messages.map((m,i)=><div key={i} className={'ai-msg '+m.role}><div>{m.text}</div>{m.action&&<div className="ai-action-card"><span>{m.action.label||m.action.type}</span><button className="btn btn-sm btn-primary" onClick={()=>void execute(m.action)} disabled={busy}>Uygula</button></div>}</div>)}{busy&&<div className="ai-msg assistant"><span className="spinner-border spinner-border-sm me-2"/>Düşünüyor…</div>}</div>{!enabled&&<div className="alert alert-warning m-3 py-2">AI Asistan kapalı. Uygulamalarım → WE AI Asistan → Asistan sekmesinden açabilirsiniz.</div>}<form className="ai-chat-input" onSubmit={e=>{e.preventDefault();void send()}}><button type="button" className="btn btn-light" onClick={voice} disabled={!enabled||busy} title="Konuş"><Icon icon="iconoir:microphone"/></button><textarea rows={2} value={text} onChange={e=>setText(e.target.value)} placeholder="Bir şey yazın veya konuşun…"/><button className="btn btn-primary" disabled={!enabled||busy||!text.trim()}><Icon icon="iconoir:send"/></button></form></aside></>}</>}
