'use client';

import { FormEvent, useMemo, useState } from 'react';
import { Icon } from '@iconify/react';
import { AiImageGenerator } from './AiTools';

export type AiPage='assistant'|'translation'|'images'|'prompts'|'credits'|'integration';
type Props={page:AiPage;data:any;sid:string;req:(p:string,o?:any)=>Promise<any>;reload:()=>Promise<void>};

export default function AiViewRouter(props:Props){if(props.page==='assistant')return <AssistantSettings {...props}/>;if(props.page==='translation')return <TranslationSettings {...props}/>;if(props.page==='images')return <ImageStudio {...props}/>;if(props.page==='prompts')return <PromptLibrary {...props}/>;if(props.page==='integration')return <AiIntegrationSettings {...props}/>;return <Credits {...props}/>}

function SaveNotice({msg,err}:{msg:string;err:string}){return <>{msg&&<div className="alert alert-success">{msg}</div>}{err&&<div className="alert alert-danger">{err}</div>}</>}

function AssistantSettings({data,req,reload}:Props){
  const cfg=data?.status?.config||{};const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMsg('');setErr('');try{await req('/admin/ai/settings',{method:'PATCH',body:JSON.stringify({...cfg,assistantEnabled:f.get('assistantEnabled')==='on',assistantName:String(f.get('assistantName')||'WE AI'),model:String(f.get('model')||'')})});setMsg('AI Asistan ayarları kaydedildi.');await reload()}catch(e:any){setErr(e.message||'Kaydedilemedi')}finally{setBusy(false)}}
  return <><SaveNotice msg={msg} err={err}/><div className="row g-3"><div className="col-xl-8"><form className="card" onSubmit={save}><div className="card-header"><h4 className="card-title mb-1">AI Asistan</h4><p className="text-muted mb-0">Sağ alttaki robot asistanın genel davranışını yönetin. AI sağlayıcı bağlantısı Entegrasyon sekmesindedir.</p></div><div className="card-body pt-0"><div className="row g-3"><div className="col-12"><div className="form-check form-switch"><input className="form-check-input" name="assistantEnabled" type="checkbox" id="aiAssistantEnabled" defaultChecked={cfg.assistantEnabled!==false}/><label className="form-check-label fw-semibold" htmlFor="aiAssistantEnabled">AI Asistan aktif</label></div></div><div className="col-md-6"><label className="form-label">Asistan adı</label><input className="form-control" name="assistantName" defaultValue={cfg.assistantName||'WE AI'}/></div><div className="col-md-6"><label className="form-label">Model tercihi</label><input className="form-control" name="model" defaultValue={cfg.model||''} placeholder="Boşsa sağlayıcı varsayılanı"/></div><div className="col-12 text-end"><button className="btn btn-primary" disabled={busy}>Kaydet</button></div></div></div></form></div><div className="col-xl-4"><div className="card"><div className="card-header"><h4 className="card-title mb-0">Asistan Yetenekleri</h4></div><div className="card-body pt-0"><div className="ai-capability"><Icon icon="iconoir:box-iso"/><div><b>Ürün ekleme</b><small>Taslak ürün oluşturur, siz onaylarsınız.</small></div></div><div className="ai-capability"><Icon icon="iconoir:folder"/><div><b>Kategori ekleme</b><small>Konuşarak kategori taslağı hazırlayın.</small></div></div><div className="ai-capability"><Icon icon="iconoir:percentage-circle"/><div><b>Promosyon</b><small>Promosyon taslağı oluşturun.</small></div></div><div className="ai-capability"><Icon icon="iconoir:microphone"/><div><b>Sesli kullanım</b><small>Tarayıcı destekliyorsa mikrofondan komut alınır.</small></div></div></div></div></div></div></>;
}

function TranslationSettings({data,req,reload}:Props){const cfg=data?.status?.config||{};const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');async function toggle(v:boolean){setBusy(true);setMsg('');setErr('');try{await req('/admin/ai/settings',{method:'PATCH',body:JSON.stringify({...cfg,translationEnabled:v})});setMsg(v?'AI Çeviri açıldı.':'AI Çeviri kapatıldı.');await reload()}catch(e:any){setErr(e.message||'Kaydedilemedi')}finally{setBusy(false)}}return <><SaveNotice msg={msg} err={err}/><div className="card"><div className="card-header"><h4 className="card-title mb-1">AI Çeviri</h4><p className="text-muted mb-0">Açık olduğunda çok dilli alanlarda “AI ile Çevir” butonu görünür ve boş hedef alanları doldurur.</p></div><div className="card-body pt-0"><div className="d-flex align-items-center justify-content-between border rounded p-3 mb-3"><div><b>AI Çeviri özelliği</b><div className="text-muted fs-12">Sayfalar, ürünler, kategoriler ve içerik bloklarında kullanılmak üzere ortak servis.</div></div><div className="form-check form-switch"><input className="form-check-input" type="checkbox" checked={!!cfg.translationEnabled} onChange={e=>void toggle(e.target.checked)} disabled={busy}/></div></div><div className="row g-3"><div className="col-md-4"><div className="ai-info-card"><Icon icon="iconoir:page"/><b>Sayfalar</b><span>Dile özel başlık, içerik, slug ve SEO.</span></div></div><div className="col-md-4"><div className="ai-info-card"><Icon icon="iconoir:box-iso"/><b>Ürün & Kategori</b><span>Başlık, açıklama ve SEO alanlarını çevirin.</span></div></div><div className="col-md-4"><div className="ai-info-card"><Icon icon="iconoir:design-pencil"/><b>Bloklar</b><span>İçerik bloklarının metinlerini hedef dile hazırlayın.</span></div></div></div></div></div></>}

function ImageStudio({data,sid,req,reload}:Props){const cfg=data?.status?.config||{};const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[last,setLast]=useState<any>(null);async function toggle(v:boolean){setBusy(true);try{await req('/admin/ai/settings',{method:'PATCH',body:JSON.stringify({...cfg,imageEnabled:v})});await reload()}catch(e:any){setErr(e.message||'Kaydedilemedi')}finally{setBusy(false)}}return <><SaveNotice msg={msg} err={err}/><div className="card"><div className="card-header d-flex justify-content-between align-items-center"><div><h4 className="card-title mb-1">AI Görsel Stüdyosu</h4><p className="text-muted mb-0">Ürün, kategori, blog ve kampanya görsellerini üretin.</p></div><div className="form-check form-switch"><input className="form-check-input" type="checkbox" checked={!!cfg.imageEnabled} onChange={e=>void toggle(e.target.checked)} disabled={busy}/></div></div><div className="card-body pt-0"><div className="d-flex flex-wrap gap-2 mb-3"><AiImageGenerator sid={sid} req={req} onGenerated={a=>{setLast(a);setMsg('Görsel medya kütüphanesine kaydedildi.')}} defaultUseCase="STUDIO" label="Yeni Görsel Oluştur"/></div>{last&&<div className="ai-last-image"><img src={last.publicUrl} alt="AI üretimi"/><div><b>{last.originalName}</b><small>Medya kütüphanesine eklendi · AI kaynak işareti aktif</small></div></div>}<div className="row g-3 mt-1">{[['STUDIO','Stüdyo','Temiz fon, ürün odaklı katalog görseli'],['LIFESTYLE','Kullanım','Ürünü gerçek kullanım senaryosunda gösterir'],['DETAIL','Detay','Doku, materyal ve yakın plan'],['HERO','Hero','Banner ve kampanya için geniş kompozisyon'],['CATEGORY','Kategori','Kategori kimliğini anlatan görsel'],['BLOG','Blog','Editoryal kapak görseli']].map(([k,t,d])=><div className="col-md-4" key={k}><div className="ai-info-card"><b>{t}</b><span>{d}</span></div></div>)}</div></div></div></>}

function PromptLibrary({data,req,reload}:Props){const initial=Array.isArray(data?.prompts?.items)?data.prompts.items:[];const[items,setItems]=useState<any[]>(initial);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');async function save(){setBusy(true);setMsg('');setErr('');try{await req('/admin/ai/prompts',{method:'PATCH',body:JSON.stringify({items})});setMsg('Prompt kütüphanesi kaydedildi.');await reload()}catch(e:any){setErr(e.message||'Kaydedilemedi')}finally{setBusy(false)}}return <><SaveNotice msg={msg} err={err}/><div className="card"><div className="card-header d-flex justify-content-between"><div><h4 className="card-title mb-1">Prompt Kütüphanesi</h4><p className="text-muted mb-0">Karakter, mağaza, ürün ve içerik bağlamlarını ayrı prompt profilleri olarak yönetin.</p></div><button className="btn btn-sm btn-primary" type="button" onClick={()=>setItems(x=>[...x,{id:'custom-'+Date.now(),category:'CUSTOM',name:'Yeni Prompt',prompt:''}])}><Icon icon="iconoir:plus"/> Prompt</button></div><div className="card-body pt-0">{items.map((p:any,i:number)=><div className="ai-prompt-row" key={p.id||i}><div className="row g-2"><div className="col-md-2"><select className="form-select" value={p.category} onChange={e=>setItems(x=>x.map((r,n)=>n===i?{...r,category:e.target.value}:r))}>{['CHARACTER','STORE','PRODUCT','CATEGORY','BLOG','PROMOTION','CUSTOM'].map(v=><option key={v}>{v}</option>)}</select></div><div className="col-md-3"><input className="form-control" value={p.name} onChange={e=>setItems(x=>x.map((r,n)=>n===i?{...r,name:e.target.value}:r))}/></div><div className="col-md-6"><textarea className="form-control" rows={2} value={p.prompt} onChange={e=>setItems(x=>x.map((r,n)=>n===i?{...r,prompt:e.target.value}:r))}/></div><div className="col-md-1 text-end"><button type="button" className="btn btn-outline-danger" onClick={()=>setItems(x=>x.filter((_,n)=>n!==i))}><Icon icon="iconoir:trash"/></button></div></div></div>)}<div className="text-end mt-3"><button className="btn btn-primary" onClick={()=>void save()} disabled={busy}>Promptları Kaydet</button></div></div></div></>}

function Credits({data,req}:Props){const c=data?.credits||{};const wallet=c.wallet||{};const[busy,setBusy]=useState('');const[err,setErr]=useState('');async function buy(code:string){setBusy(code);setErr('');try{const r=await req('/admin/ai/credits/purchase',{method:'POST',body:JSON.stringify({packageCode:code})});if(r.checkoutUrl)window.location.href=r.checkoutUrl}catch(e:any){setErr(e.message||'Satın alma başlatılamadı')}finally{setBusy('')}}return <><div className="row g-3 mb-3"><div className="col-md-4"><div className="card h-100"><div className="card-body"><span className="text-muted">Kalan kredi</span><div className="display-6 fw-semibold">{wallet.balance??0}</div></div></div></div><div className="col-md-4"><div className="card h-100"><div className="card-body"><span className="text-muted">Toplam satın alınan</span><div className="h3">{wallet.lifetimePurchased??0}</div></div></div></div><div className="col-md-4"><div className="card h-100"><div className="card-body"><span className="text-muted">Toplam kullanılan</span><div className="h3">{wallet.lifetimeUsed??0}</div></div></div></div></div>{err&&<div className="alert alert-warning">{err}</div>}<div className="row g-3 mb-3">{(c.packages||[]).map((p:any)=><div className="col-md-4" key={p.code}><div className="card h-100"><div className="card-body"><h4>{p.name}</h4><div className="display-6">{Number(p.credits).toLocaleString('tr-TR')}</div><small className="text-muted">AI kredisi</small><div className="h4 mt-3">{Number(p.price).toLocaleString('tr-TR')} {p.currency}</div><button className="btn btn-primary w-100 mt-2" onClick={()=>void buy(p.code)} disabled={busy===p.code}>{busy===p.code?'Yönlendiriliyor…':'Kredi Satın Al'}</button></div></div></div>)}</div><div className="card"><div className="card-header"><h4 className="card-title mb-0">Kredi Hareketleri</h4></div><div className="card-body pt-0"><div className="table-responsive"><table className="table table-centered"><thead><tr><th>Tarih</th><th>İşlem</th><th>Açıklama</th><th>Tutar</th><th>Bakiye</th></tr></thead><tbody>{(c.ledger||[]).map((r:any)=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString('tr-TR')}</td><td>{r.type}</td><td>{r.description||r.source||'—'}</td><td className={r.amount<0?'text-danger':'text-success'}>{r.amount}</td><td>{r.balanceAfter}</td></tr>)}{!(c.ledger||[]).length&&<tr><td colSpan={5} className="text-center text-muted py-4">Henüz kredi hareketi yok.</td></tr>}</tbody></table></div></div></div></>}


const aiTabs:{key:AiPage;label:string;icon:string}[]=[
  {key:'assistant',label:'Asistan',icon:'iconoir:robot'},
  {key:'translation',label:'Çeviri',icon:'iconoir:translate'},
  {key:'images',label:'Görsel',icon:'iconoir:media-image'},
  {key:'prompts',label:'Prompt',icon:'iconoir:chat-lines'},
  {key:'credits',label:'Kredi',icon:'iconoir:credit-card'},
  {key:'integration',label:'Entegrasyon',icon:'iconoir:link'},
];

export function AiAppView({data,sid,req,reload}:{data:any;sid:string;req:(p:string,o?:any)=>Promise<any>;reload:()=>Promise<void>}){
  const[tab,setTab]=useState<AiPage>('assistant');
  return <>
    <div className="card mb-3"><div className="card-body"><div className="d-flex flex-wrap align-items-center justify-content-between gap-3"><div className="d-flex align-items-center gap-3"><span className="plugin-icon"><Icon icon="iconoir:robot"/></span><div><h3 className="mb-1">WE AI Asistan</h3><p className="text-muted mb-0">Asistan, çeviri, görsel üretimi, prompt ve kredi tek uygulama altında.</p></div></div><span className="badge bg-success-subtle text-success">Kurulu</span></div></div></div>
    <div className="card"><div className="card-header border-bottom-0 pb-0"><ul className="nav nav-tabs card-header-tabs ai-app-tabs">{aiTabs.map(x=><li className="nav-item" key={x.key}><button type="button" className={'nav-link '+(tab===x.key?'active':'')} onClick={()=>setTab(x.key)}><Icon icon={x.icon} className="me-1"/>{x.label}</button></li>)}</ul></div><div className="card-body"><AiViewRouter page={tab} data={data} sid={sid} req={req} reload={reload}/></div></div>
  </>;
}

function AiIntegrationSettings({data,req,reload}:Props){
  const cfg=data?.status?.config||{};
  const[mode,setMode]=useState(cfg.providerMode||'WE');
  const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMsg('');setErr('');try{await req('/admin/ai/settings',{method:'PATCH',body:JSON.stringify({...cfg,providerMode:mode,model:String(f.get('model')||cfg.model||''),ownName:String(f.get('ownName')||'Kendi AI Sağlayıcım'),ownCredentials:mode==='OWN'?{baseUrl:String(f.get('baseUrl')||''),apiKey:String(f.get('apiKey')||''),model:String(f.get('model')||'')}:undefined})});setMsg('AI entegrasyon ayarları kaydedildi.');await reload()}catch(e:any){setErr(e.message||'Kaydedilemedi')}finally{setBusy(false)}}
  return <><SaveNotice msg={msg} err={err}/><form onSubmit={save}><div className="mb-3"><h4>Entegrasyon</h4><p className="text-muted">WE AI kredisi kullan veya kendi OpenAI-compatible sağlayıcını bağla.</p></div><div className="row g-3"><div className="col-md-6"><button type="button" className={'ai-provider-choice '+(mode==='WE'?'active':'')} onClick={()=>setMode('WE')}><Icon icon="iconoir:sparks"/><b>WE AI</b><small>Platform kredisi · Bakiye: {data?.status?.wallet?.balance??0}</small></button></div><div className="col-md-6"><button type="button" className={'ai-provider-choice '+(mode==='OWN'?'active':'')} onClick={()=>setMode('OWN')}><Icon icon="iconoir:key"/><b>Kendi AI Sağlayıcım</b><small>Kendi API hesabını kullan.</small></button></div><div className="col-md-6"><label className="form-label">Model</label><input className="form-control" name="model" defaultValue={cfg.model||''}/></div>{mode==='OWN'&&<><div className="col-md-6"><label className="form-label">Bağlantı adı</label><input className="form-control" name="ownName" defaultValue="Kendi AI Sağlayıcım"/></div><div className="col-md-6"><label className="form-label">Base URL</label><input className="form-control" name="baseUrl" placeholder="https://api.openai.com/v1"/></div><div className="col-md-6"><label className="form-label">API Key</label><input className="form-control" name="apiKey" type="password" autoComplete="new-password" placeholder={data?.status?.ownProviderConnected?'Bağlantı mevcut — değiştirmek için yeni anahtar girin':'sk-...'}/></div></>}<div className="col-12 text-end"><button className="btn btn-primary" disabled={busy}>Entegrasyonu Kaydet</button></div></div></form></>;
}
