'use client';
import { useEffect, useMemo, useState } from 'react';
import { Icon } from '@iconify/react';
import { AiImageGenerator, AiTranslateButton } from './AiTools';
import { slugifyTR } from './slug';

type Fields={title:string;slug:string;description:string;seoTitle:string;seoDescription:string};
export function CatalogTranslations({sid,req,store,source,onChange,label='Çeviriler',initialRows=[]}:{sid:string;req:(p:string,o?:any)=>Promise<any>;store:any;source:Fields;onChange:(rows:any[])=>void;label?:string;initialRows?:any[]}){
 const locales=(Array.isArray(store?.locales)?store.locales:[]).filter((x:any)=>x.isEnabled!==false);const defaultLocale=locales.find((x:any)=>x.isDefault)?.locale||store?.locale||'tr-TR';const targets=locales.filter((x:any)=>x.locale!==defaultLocale);const[locale,setLocale]=useState(targets[0]?.locale||'');const[map,setMap]=useState<Record<string,Fields>>(()=>Object.fromEntries((Array.isArray(initialRows)?initialRows:[]).map((x:any)=>[String(x.locale),{title:String(x.fields?.title||''),slug:String(x.fields?.slug||''),description:String(x.fields?.description||''),seoTitle:String(x.fields?.seoTitle||''),seoDescription:String(x.fields?.seoDescription||'')}])));
 useEffect(()=>{onChange(Object.entries(map).map(([locale,fields])=>({locale,fields})))},[map]);
 if(!targets.length)return <div className="alert alert-light border mb-0"><Icon icon="iconoir:translate" className="me-1"/>Ek dil tanımlandığında {label.toLocaleLowerCase('tr-TR')} burada görünecek.</div>;
 const current=map[locale]||{title:'',slug:'',description:'',seoTitle:'',seoDescription:''};const set=(k:keyof Fields,v:string)=>setMap(x=>({...x,[locale]:{...current,[k]:v}}));
 return <div className="card border mb-0"><div className="card-header d-flex justify-content-between align-items-center"><div><h5 className="card-title mb-0">{label}</h5><small className="text-muted">Boş alanları AI ile hedef dile doldurun.</small></div><select className="form-select form-select-sm" style={{width:180}} value={locale} onChange={e=>setLocale(e.target.value)}>{targets.map((l:any)=><option value={l.locale} key={l.locale}>{l.label||l.locale}</option>)}</select></div><div className="card-body pt-0"><div className="d-flex justify-content-end mb-2"><AiTranslateButton sid={sid} req={req} sourceLocale={defaultLocale} targetLocale={locale} fields={source} onResult={r=>setMap(x=>({...x,[locale]:{...current,...r,slug:r.slug||slugifyTR(r.title||current.title)}}))}/></div><div className="row g-2"><div className="col-md-6"><input className="form-control" placeholder="Çevrilmiş başlık" value={current.title} onChange={e=>set('title',e.target.value)}/></div><div className="col-md-6"><input className="form-control" placeholder="Çevrilmiş slug" value={current.slug} onChange={e=>set('slug',e.target.value)}/></div><div className="col-12"><textarea className="form-control" rows={3} placeholder="Çevrilmiş açıklama" value={current.description} onChange={e=>set('description',e.target.value)}/></div><div className="col-md-6"><input className="form-control" placeholder="SEO başlığı" value={current.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></div><div className="col-md-6"><input className="form-control" placeholder="SEO açıklaması" value={current.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></div></div></div></div>
}

export function CategoryCreate({data,sid,post,req}:any){const[image,setImage]=useState<any>(null);const[name,setName]=useState('');const[slug,setSlug]=useState('');const[desc,setDesc]=useState('');const[seoTitle,setSeoTitle]=useState('');const[seoDescription,setSeoDescription]=useState('');const[translations,setTranslations]=useState<any[]>([]);const currentSlug=slug||slugifyTR(name);return <div className="panel"><div className="toolbar"><h3>Yeni kategori</h3><AiImageGenerator sid={sid} req={req} defaultUseCase="CATEGORY" onGenerated={setImage}/></div><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await post('/admin/categories',{storeId:sid,name,slug:currentSlug,description:desc,imageUrl:image?.publicUrl||null,parentId:f.get('parentId')||null,seoTitle,seoDescription,translations,isActive:true});setName('');setSlug('');setDesc('');setSeoTitle('');setSeoDescription('');setImage(null);setTranslations([]);(e.currentTarget as HTMLFormElement).reset()}}><label>Kategori adı<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Slug<input value={currentSlug} onChange={e=>setSlug(e.target.value)} required/></label><label>Üst kategori<select name="parentId"><option value="">Ana kategori</option>{(data.categories||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>SEO başlığı<input value={seoTitle} onChange={e=>setSeoTitle(e.target.value)}/></label><label className="full">Açıklama<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label><label className="full">SEO açıklaması<textarea value={seoDescription} onChange={e=>setSeoDescription(e.target.value)}/></label>{image&&<div className="full media-card ai-inline-preview"><img src={image.publicUrl} alt=""/><span>{image.source==='AI'?'AI üretimi':'Medya'}</span></div>}<div className="full"><CatalogTranslations sid={sid} req={req} store={data.settings||{}} source={{title:name,slug:currentSlug,description:desc,seoTitle,seoDescription}} onChange={setTranslations} label="Kategori Çevirileri"/></div><div className="full"><button className="btn">Kategoriyi oluştur</button></div></form></div>}
