'use client';

import {FormEvent,useState} from 'react';
import {Icon} from '@iconify/react';

type Props={data:any;sid:string;req:(path:string,options?:any)=>Promise<any>;reload:()=>Promise<void>};

export default function CustomerGroupsView({data,sid,req,reload}:Props){
  const rows=Array.isArray(data?.groups)?data.groups:[];
  const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy('new');setMsg('');setErr('');try{await req('/admin/customer-groups',{method:'POST',body:JSON.stringify({storeId:sid,name:f.get('name'),description:f.get('description'),color:f.get('color'),discountPercent:Number(f.get('discountPercent')||0),isDefault:f.get('isDefault')==='on'})});(e.currentTarget as HTMLFormElement).reset();setMsg('Müşteri grubu oluşturuldu.');await reload()}catch(x:any){setErr(x.message||'Grup oluşturulamadı')}finally{setBusy('')}}
  async function remove(id:string){if(!confirm('Bu müşteri grubunu silmek istiyor musunuz? Gruptaki müşteriler gruptan çıkarılır.'))return;setBusy(id);try{await req(`/admin/customer-groups/${id}?storeId=${encodeURIComponent(sid)}`,{method:'DELETE'});await reload()}catch(x:any){setErr(x.message||'Silinemedi')}finally{setBusy('')}}
  async function save(row:any,e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(row.id);setErr('');try{await req(`/admin/customer-groups/${row.id}`,{method:'PATCH',body:JSON.stringify({storeId:sid,name:f.get('name'),description:f.get('description'),color:f.get('color'),discountPercent:Number(f.get('discountPercent')||0),isDefault:f.get('isDefault')==='on'})});setMsg('Grup güncellendi.');await reload()}catch(x:any){setErr(x.message||'Kaydedilemedi')}finally{setBusy('')}}
  return <div className="customer-groups-page">
    {(msg||err)&&<div className={'alert '+(err?'alert-danger':'alert-success')}>{err||msg}</div>}
    <div className="card mb-3"><div className="card-header"><div><h4 className="card-title mb-1">Müşteri Grupları</h4><p className="text-muted mb-0">VIP, toptan, bayi veya özel müşteri segmentleri oluşturun.</p></div></div><div className="card-body pt-0"><form className="row g-2 align-items-end" onSubmit={create}><div className="col-md-3"><label className="form-label">Grup adı</label><input name="name" className="form-control" required placeholder="VIP Müşteri"/></div><div className="col-md-3"><label className="form-label">Açıklama</label><input name="description" className="form-control" placeholder="Sadık müşteriler"/></div><div className="col-md-2"><label className="form-label">İndirim %</label><input name="discountPercent" className="form-control" type="number" min="0" max="100" step="0.01" defaultValue="0"/></div><div className="col-md-2"><label className="form-label">Renk</label><input name="color" className="form-control form-control-color w-100" type="color" defaultValue="#16a34a"/></div><div className="col-md-2"><div className="form-check mb-2"><input className="form-check-input" type="checkbox" name="isDefault" id="cg-default"/><label className="form-check-label" htmlFor="cg-default">Varsayılan grup</label></div><button className="btn btn-primary w-100" disabled={busy==='new'}>{busy==='new'?'Ekleniyor…':'Grup Ekle'}</button></div></form></div></div>
    <div className="row g-3">{rows.map((row:any)=><div className="col-md-6 col-xl-4" key={row.id}><form className="card h-100" onSubmit={e=>void save(row,e)}><div className="card-body"><div className="d-flex justify-content-between align-items-start mb-3"><span className="customer-group-color" style={{background:row.color||'#16a34a'}}/><div className="text-end"><span className="badge bg-light text-body border">{row?._count?.customers||0} müşteri</span>{row.isDefault&&<span className="badge bg-success-subtle text-success ms-1">Varsayılan</span>}</div></div><label className="form-label">Grup adı</label><input name="name" className="form-control mb-2" defaultValue={row.name}/><label className="form-label">Açıklama</label><textarea name="description" className="form-control mb-2" rows={2} defaultValue={row.description||''}/><div className="row g-2"><div className="col-6"><label className="form-label">İndirim %</label><input name="discountPercent" type="number" min="0" max="100" step="0.01" className="form-control" defaultValue={Number(row.discountPercent||0)}/></div><div className="col-6"><label className="form-label">Renk</label><input name="color" type="color" className="form-control form-control-color w-100" defaultValue={row.color||'#16a34a'}/></div></div><div className="form-check form-switch mt-3"><input className="form-check-input" name="isDefault" type="checkbox" defaultChecked={!!row.isDefault}/><label className="form-check-label">Varsayılan müşteri grubu</label></div></div><div className="card-footer bg-white d-flex justify-content-between"><button type="button" className="btn btn-sm btn-outline-danger" onClick={()=>void remove(row.id)} disabled={busy===row.id}><Icon icon="iconoir:trash"/> Sil</button><button className="btn btn-sm btn-primary" disabled={busy===row.id}><Icon icon="iconoir:check"/> Kaydet</button></div></form></div>)}{!rows.length&&<div className="col-12"><div className="card"><div className="card-body text-center text-muted py-5">Henüz müşteri grubu oluşturulmadı.</div></div></div>}</div>
  </div>;
}
