'use client';

import {useMemo,useState} from 'react';
import {Icon} from '@iconify/react';

type Props={data:any;sid:string;req:(path:string,options?:any)=>Promise<any>;reload:()=>Promise<void>};
type MenuItem={id:string;label:string;url:string;type:string;badge?:string;imageUrl?:string;description?:string;columns?:number;children:MenuItem[]};

const uid=()=>`menu-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const emptyItem=():MenuItem=>({id:uid(),label:'Yeni bağlantı',url:'/',type:'link',columns:4,children:[]});
const LOCATIONS=[['header-main','Ana Menü'],['header-categories','Kategori Mega Menü'],['mobile-main','Mobil Menü'],['footer-main','Footer Menü']];

export default function MegaMenuStudio({data,sid,req,reload}:Props){
  const menus=Array.isArray(data?.menus)?data.menus:[];const[handle,setHandle]=useState('header-main');
  const selected=useMemo(()=>menus.find((m:any)=>m.handle===handle),[menus,handle]);
  const[items,setItems]=useState<MenuItem[]>(()=>normalize(selected?.items));const[name,setName]=useState(selected?.name||'Ana Menü');const[activeId,setActiveId]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[saving,setSaving]=useState(false);
  function choose(next:string){const row=menus.find((m:any)=>m.handle===next);setHandle(next);setName(row?.name||LOCATIONS.find(x=>x[0]===next)?.[1]||'Menü');setItems(normalize(row?.items));setActiveId('')}
  function patch(id:string,key:string,value:any){setItems(rows=>walk(rows,id,row=>({...row,[key]:value})))}
  function remove(id:string){setItems(rows=>removeById(rows,id));if(activeId===id)setActiveId('')}
  function addChild(parentId:string){setItems(rows=>walk(rows,parentId,row=>({...row,children:[...(row.children||[]),emptyItem()]})))}
  function move(id:string,direction:-1|1){setItems(rows=>moveById(rows,id,direction))}
  async function save(){setSaving(true);setErr('');setMsg('');try{await req('/admin/menus',{method:'POST',body:JSON.stringify({storeId:sid,name,handle,items})});setMsg('Mega menü kaydedildi.');await reload()}catch(e:any){setErr(e.message||'Menü kaydedilemedi')}finally{setSaving(false)}}
  const active=findById(items,activeId);
  return <div className="mega-menu-studio">
    {msg&&<div className="alert alert-success">{msg}</div>}{err&&<div className="alert alert-danger">{err}</div>}
    <div className="card mb-3"><div className="card-body"><div className="d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><h4 className="mb-1">Menü ve Mega Menü Tasarımı</h4><p className="text-muted mb-0">Çok kolonlu kategori menüleri, görsel promosyon alanları, rozetler ve mobil menü tek merkezden yönetilir.</p></div><button className="btn btn-primary" onClick={()=>void save()} disabled={saving}><Icon icon="iconoir:floppy-disk" className="me-1"/>{saving?'Kaydediliyor…':'Menüyü Kaydet'}</button></div></div></div>
    <div className="row g-3"><div className="col-xl-4"><div className="card"><div className="card-header"><h5 className="card-title mb-0">Menü Yapısı</h5></div><div className="card-body pt-0"><label className="form-label">Menü konumu</label><select className="form-select mb-3" value={handle} onChange={e=>choose(e.target.value)}>{LOCATIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><label className="form-label">Menü adı</label><input className="form-control mb-3" value={name} onChange={e=>setName(e.target.value)}/><div className="mega-menu-tree">{items.map((item,index)=><MenuTree key={item.id} item={item} depth={0} index={index} total={items.length} activeId={activeId} onSelect={setActiveId} onAdd={addChild} onRemove={remove} onMove={move}/>)}</div><button className="btn btn-outline-primary w-100 mt-3" onClick={()=>setItems(rows=>[...rows,emptyItem()])}><Icon icon="iconoir:plus" className="me-1"/>Üst Menü Ekle</button></div></div></div>
      <div className="col-xl-8">{active?<div className="card"><div className="card-header"><div><h5 className="card-title mb-1">Menü Öğesi</h5><small className="text-muted">Mega menü kolonunu, bağlantıyı ve görsel promosyonu yapılandırın.</small></div></div><div className="card-body pt-0"><div className="row g-3"><div className="col-md-6"><label className="form-label">Başlık</label><input className="form-control" value={active.label} onChange={e=>patch(active.id,'label',e.target.value)}/></div><div className="col-md-6"><label className="form-label">Tür</label><select className="form-select" value={active.type} onChange={e=>patch(active.id,'type',e.target.value)}><option value="link">Bağlantı</option><option value="mega">Mega Menü</option><option value="category">Kategori</option><option value="collection">Koleksiyon</option><option value="promo">Görsel Promosyon</option></select></div><div className="col-md-8"><label className="form-label">Bağlantı</label><input className="form-control" value={active.url} onChange={e=>patch(active.id,'url',e.target.value)} placeholder="/collections/yeni"/></div><div className="col-md-4"><label className="form-label">Rozet</label><input className="form-control" value={active.badge||''} onChange={e=>patch(active.id,'badge',e.target.value)} placeholder="YENİ"/></div><div className="col-md-4"><label className="form-label">Kolon genişliği</label><select className="form-select" value={active.columns||4} onChange={e=>patch(active.id,'columns',Number(e.target.value))}><option value="3">4 kolon</option><option value="4">3 kolon</option><option value="6">2 kolon</option><option value="12">Tam genişlik</option></select></div><div className="col-md-8"><label className="form-label">Görsel URL</label><input className="form-control" value={active.imageUrl||''} onChange={e=>patch(active.id,'imageUrl',e.target.value)} placeholder="Mega menü kampanya görseli"/></div><div className="col-12"><label className="form-label">Kısa açıklama</label><input className="form-control" value={active.description||''} onChange={e=>patch(active.id,'description',e.target.value)}/></div></div><div className="mega-menu-preview mt-4"><div><b>{active.label||'Başlık'}</b>{active.badge&&<span>{active.badge}</span>}<small>{active.description||'Menü açıklaması'}</small></div>{active.imageUrl&&<img src={active.imageUrl} alt=""/>}</div></div></div>:<div className="card"><div className="card-body text-center py-5"><Icon icon="iconoir:menu-scale" width="44" className="text-primary"/><h5 className="mt-3">Bir menü öğesi seçin</h5><p className="text-muted mb-0">Sol taraftan öğe seçerek bağlantı, kolon, görsel ve rozet ayarlarını düzenleyin.</p></div></div>}</div></div>
  </div>;
}

function normalize(value:any):MenuItem[]{return(Array.isArray(value)?value:[]).map((row:any)=>({id:String(row.id||uid()),label:String(row.label||row.title||'Bağlantı'),url:String(row.url||'/'),type:String(row.type||'link'),badge:row.badge||'',imageUrl:row.imageUrl||'',description:row.description||'',columns:Number(row.columns||4),children:normalize(row.children)}))}
function walk(rows:MenuItem[],id:string,fn:(row:MenuItem)=>MenuItem):MenuItem[]{return rows.map(row=>row.id===id?fn(row):({...row,children:walk(row.children||[],id,fn)}))}
function removeById(rows:MenuItem[],id:string):MenuItem[]{return rows.filter(row=>row.id!==id).map(row=>({...row,children:removeById(row.children||[],id)}))}
function findById(rows:MenuItem[],id:string):MenuItem|undefined{for(const row of rows){if(row.id===id)return row;const found=findById(row.children||[],id);if(found)return found}return undefined}
function moveById(rows:MenuItem[],id:string,direction:-1|1):MenuItem[]{const index=rows.findIndex(x=>x.id===id);if(index>=0){const to=index+direction;if(to<0||to>=rows.length)return rows;const next=[...rows];[next[index],next[to]]=[next[to],next[index]];return next}return rows.map(row=>({...row,children:moveById(row.children||[],id,direction)}))}
function MenuTree({item,depth,index,total,activeId,onSelect,onAdd,onRemove,onMove}:any){return <div className="mega-menu-node" style={{marginLeft:depth*14}}><div className={activeId===item.id?'active':''}><button className="mega-menu-node-main" type="button" onClick={()=>onSelect(item.id)}><Icon icon={item.type==='mega'?'iconoir:view-columns-3':item.type==='promo'?'iconoir:media-image':'iconoir:nav-arrow-right'}/><span>{item.label}</span>{item.badge&&<small>{item.badge}</small>}</button><button type="button" disabled={index===0} onClick={()=>onMove(item.id,-1)} title="Yukarı"><Icon icon="iconoir:arrow-up"/></button><button type="button" disabled={index===total-1} onClick={()=>onMove(item.id,1)} title="Aşağı"><Icon icon="iconoir:arrow-down"/></button><button type="button" onClick={()=>onAdd(item.id)} title="Alt öğe"><Icon icon="iconoir:plus"/></button><button type="button" onClick={()=>onRemove(item.id)} title="Sil"><Icon icon="iconoir:trash"/></button></div>{(item.children||[]).map((child:any,i:number)=><MenuTree key={child.id} item={child} depth={depth+1} index={i} total={item.children.length} activeId={activeId} onSelect={onSelect} onAdd={onAdd} onRemove={onRemove} onMove={onMove}/>)}</div>}
