'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {Icon} from '@iconify/react';
type Props={data:any;req:(path:string,options?:any)=>Promise<any>;reload:()=>Promise<void>};
export default function PlansView({data,req,reload}:Props){
 const catalog=data?.plans||data||{};const current=catalog.current;const plans=Array.isArray(catalog.plans)?catalog.plans:[];const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[payment,setPayment]=useState<any>(null);const[buyer,setBuyer]=useState({identityNumber:'',phone:'',address:'',city:'İstanbul',zipCode:'34000',country:'Turkey'});
 const deadline=current?.status==='TRIAL'?current?.trialEndsAt:current?.currentPeriodEnd;const days=deadline?Math.max(0,Math.ceil((new Date(deadline).getTime()-Date.now())/86400000)):null;
 const cards=useMemo(()=>plans.map((p:any,i:number)=>({...p,popular:(p.features as any)?.popular===true||i===Math.min(1,plans.length-1)})),[plans]);
 function choose(plan:any,billing:'MONTHLY'|'YEARLY'){setPayment({plan,billing});setErr('');setMsg('')}
 async function startPayment(){if(!payment)return;const key=payment.plan.id+payment.billing;setBusy(key);setErr('');try{const out=await req('/admin/billing/iyzico/checkout',{method:'POST',body:JSON.stringify({planId:payment.plan.id,billing:payment.billing,buyer})});window.open(out.paymentUrl,'_blank','noopener,noreferrer');setMsg('iyzico güvenli ödeme ekranı açıldı. Ödeme tamamlandığında paketiniz otomatik güncellenecek.');setPayment(null);await reload()}catch(x:any){setErr(x.message||'Ödeme başlatılamadı')}finally{setBusy('')}}
 const labels:Record<string,string>={promotions:'Promosyonlar',multiCurrency:'Çoklu para birimi',loyalty:'Sadakat',marketing:'Pazarlama: E-posta & SMS',privacy:'KVKK / GDPR',customDomain:'Özel alan adı',api:'API erişimi',prioritySupport:'Öncelikli destek',coupons:'Kuponlar',reviews:'Yorumlar',pages:'İçerik sayfaları'};
 return <div className="plans-v16-page">
  <div className="plans-v16-heading"><span><Icon icon="iconoir:sparks"/></span><div><small>LİSANS</small><h2>E-ticaret Paketleri</h2><p>Paket satın alma ve yükseltme işlemleri iyzico güvenli ödeme altyapısı ile tamamlanır.</p></div></div>
  {(msg||err)&&<div className={'alert '+(err?'alert-danger':'alert-success')}>{err||msg}</div>}
  <div className="plans-v16-current"><div><Icon icon="iconoir:shop"/><span>Aktif paket: <b>{current?.plan?.name||'Ücretsiz'}</b></span></div>{current?.status==='TRIAL'&&days!==null&&<span className="plans-v16-days">{days} gün kaldı</span>}</div>
  <div className="plans-v16-grid">{cards.map((plan:any)=>{const active=current?.planId===plan.id;const features=Object.entries(plan.features||{}).filter(([,v])=>v===true).map(([k])=>labels[k]||k);return <article key={plan.id} className={'plans-v16-card '+(plan.popular?'popular ':'')+(active?'active':'')}>
   {plan.popular&&<span className="plans-v16-ribbon">EN POPÜLER</span>}<div className="plans-v16-card-head"><Icon icon={plan.popular?'iconoir:crown':'iconoir:shop'}/><h3>{plan.name}</h3>{active&&<span className="badge bg-success-subtle text-success ms-auto">Aktif</span>}</div>
   <div className="plans-v16-price">₺{Number(plan.yearlyPrice||plan.monthlyPrice||0).toLocaleString('tr-TR')}<small>{plan.yearlyPrice?' / yıl':' / ay'}</small></div><p className="plans-v16-desc">{plan.description||'Tam e-ticaret mağazası'}</p><ul><li><Icon icon="iconoir:check"/> {plan.maxProducts>=999999?'Sınırsız ürün':`${Number(plan.maxProducts||0).toLocaleString('tr-TR')} ürün`}</li><li><Icon icon="iconoir:check"/> Sipariş & kargo yönetimi</li><li><Icon icon="iconoir:check"/> Ödeme entegrasyonları</li>{features.slice(0,6).map((x:string)=><li key={x}><Icon icon="iconoir:check"/> {x}</li>)}</ul>
   <div className="mt-auto d-grid gap-2">{active?<button className="btn btn-light border" disabled>Mevcut Paket</button>:<button className="btn btn-primary" disabled={!!busy} onClick={()=>choose(plan,'YEARLY')}>Yıllık Pakete Geç</button>}{!active&&Number(plan.monthlyPrice||0)>0&&<button className="btn btn-outline-primary" disabled={!!busy} onClick={()=>choose(plan,'MONTHLY')}>Aylık Öde · ₺{Number(plan.monthlyPrice).toLocaleString('tr-TR')}/ay</button>}</div>
  </article>})}</div>
  <div className="plans-v16-custom"><span><Icon icon="iconoir:palette"/></span><div><h4>Özel Tasarım Paketi</h4><p>Markanıza özel tasarım, gelişmiş entegrasyon ve danışmanlık için teklif alın.</p></div><Link href="/support" className="btn btn-primary ms-auto">Teklif Al</Link></div>
  {payment&&<div className="modal d-block commerce-store-modal" tabIndex={-1}><div className="modal-dialog modal-dialog-centered"><div className="modal-content"><div className="modal-header"><div><h5 className="modal-title">{payment.plan.name} · {payment.billing==='YEARLY'?'Yıllık':'Aylık'}</h5><small className="text-muted">iyzico ödeme öncesi fatura bilgileri</small></div><button className="btn-close" onClick={()=>setPayment(null)}/></div><div className="modal-body"><div className="row g-3"><div className="col-12"><label className="form-label">TCKN / VKN</label><input className="form-control" value={buyer.identityNumber} onChange={e=>setBuyer(x=>({...x,identityNumber:e.target.value}))} inputMode="numeric"/></div><div className="col-12"><label className="form-label">Telefon</label><input className="form-control" value={buyer.phone} onChange={e=>setBuyer(x=>({...x,phone:e.target.value}))}/></div><div className="col-12"><label className="form-label">Fatura adresi</label><textarea className="form-control" rows={2} value={buyer.address} onChange={e=>setBuyer(x=>({...x,address:e.target.value}))}/></div><div className="col-md-7"><label className="form-label">Şehir</label><input className="form-control" value={buyer.city} onChange={e=>setBuyer(x=>({...x,city:e.target.value}))}/></div><div className="col-md-5"><label className="form-label">Posta kodu</label><input className="form-control" value={buyer.zipCode} onChange={e=>setBuyer(x=>({...x,zipCode:e.target.value}))}/></div></div></div><div className="modal-footer"><button className="btn btn-light" onClick={()=>setPayment(null)}>Vazgeç</button><button className="btn btn-primary" onClick={()=>void startPayment()} disabled={!!busy||!buyer.identityNumber||!buyer.phone||!buyer.address}>{busy?'iyzico açılıyor…':'Güvenli Ödemeye Geç'}</button></div></div></div></div>}
 </div>;
}
