'use client';
import {FormEvent,useState} from 'react';
import {Icon} from '@iconify/react';

export default function SeoStudio({data,sid,req,reload}:{data:any;sid:string;req:(p:string,o?:any)=>Promise<any>;reload:()=>Promise<void>}){
  const initial=data?.settings||{};const[settings,setSettings]=useState<any>(initial);const[saving,setSaving]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  const set=(path:string,value:any)=>setSettings((cur:any)=>{const next=structuredClone(cur||{});const parts=path.split('.');let x=next;for(let i=0;i<parts.length-1;i++)x=x[parts[i]]||(x[parts[i]]={});x[parts.at(-1)!]=value;return next});
  async function save(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');setErr('');try{await req('/admin/seo/settings',{method:'PATCH',body:JSON.stringify({storeId:sid,settings})});setMsg('SEO ve takip ayarları kaydedildi.');await reload()}catch(e:any){setErr(e.message||'Kaydedilemedi')}finally{setSaving(false)}}
  const t=settings.tracking||{};const social=settings.social||{};const technical=settings.technical||{};const schema=settings.schema||{};
  return <form onSubmit={save} className="seo-studio">
    {msg&&<div className="alert alert-success">{msg}</div>}{err&&<div className="alert alert-danger">{err}</div>}
    <div className="row g-3 mb-3">{[['Ürün',data.products],['Kategori',data.categories],['Sayfa',data.pages],['Blog',data.blogPosts],['Yönlendirme',data.redirects?.length||0]].map(([a,b])=><div className="col-md"><div className="card h-100"><div className="card-body"><small className="text-muted">{a as string}</small><h3 className="mb-0 mt-1">{String(b??0)}</h3></div></div></div>)}</div>
    <div className="row g-3"><div className="col-xl-8">
      <div className="card"><div className="card-header"><h4 className="card-title mb-1">Genel SEO</h4><p className="text-muted mb-0">Arama motoru, paylaşım ve index ayarları.</p></div><div className="card-body pt-0"><div className="row g-3">
        <div className="col-md-6"><label className="form-label">Varsayılan site başlığı</label><input className="form-control" value={settings.defaultTitle||''} onChange={e=>set('defaultTitle',e.target.value)} maxLength={70}/><div className="form-text">Öneri: 50–60 karakter.</div></div>
        <div className="col-md-6"><label className="form-label">Başlık şablonu</label><input className="form-control" value={settings.titleTemplate||'{{page}} | {{store}}'} onChange={e=>set('titleTemplate',e.target.value)}/></div>
        <div className="col-12"><label className="form-label">Varsayılan meta açıklama</label><textarea className="form-control" rows={3} value={settings.defaultDescription||''} onChange={e=>set('defaultDescription',e.target.value)} maxLength={180}/></div>
        <div className="col-md-6"><label className="form-label">Canonical ana adres</label><input className="form-control" placeholder="https://magaza.com" value={technical.canonicalBase||''} onChange={e=>set('technical.canonicalBase',e.target.value)}/></div>
        <div className="col-md-6"><label className="form-label">Robots</label><select className="form-select" value={technical.robots||'index,follow'} onChange={e=>set('technical.robots',e.target.value)}><option>index,follow</option><option>noindex,follow</option><option>noindex,nofollow</option></select></div>
        <div className="col-md-4"><div className="form-check form-switch mt-4"><input className="form-check-input" type="checkbox" checked={technical.sitemap!==false} onChange={e=>set('technical.sitemap',e.target.checked)}/><label className="form-check-label">Sitemap açık</label></div></div>
        <div className="col-md-4"><div className="form-check form-switch mt-4"><input className="form-check-input" type="checkbox" checked={technical.productSchema!==false} onChange={e=>set('technical.productSchema',e.target.checked)}/><label className="form-check-label">Product schema</label></div></div>
        <div className="col-md-4"><div className="form-check form-switch mt-4"><input className="form-check-input" type="checkbox" checked={technical.breadcrumbSchema!==false} onChange={e=>set('technical.breadcrumbSchema',e.target.checked)}/><label className="form-check-label">Breadcrumb schema</label></div></div>
      </div></div></div>
      <div className="card"><div className="card-header"><h4 className="card-title mb-1">Sosyal Paylaşım</h4></div><div className="card-body pt-0"><div className="row g-3"><div className="col-md-6"><label className="form-label">Open Graph görseli</label><input className="form-control" value={social.ogImage||''} onChange={e=>set('social.ogImage',e.target.value)}/></div><div className="col-md-6"><label className="form-label">Twitter kart tipi</label><select className="form-select" value={social.twitterCard||'summary_large_image'} onChange={e=>set('social.twitterCard',e.target.value)}><option value="summary_large_image">summary_large_image</option><option value="summary">summary</option></select></div></div></div></div>
      <div className="card"><div className="card-header"><h4 className="card-title mb-1">Yapısal Veri / Kurum</h4></div><div className="card-body pt-0"><div className="row g-3"><div className="col-md-6"><label className="form-label">Organization adı</label><input className="form-control" value={schema.organizationName||''} onChange={e=>set('schema.organizationName',e.target.value)}/></div><div className="col-md-6"><label className="form-label">Logo URL</label><input className="form-control" value={schema.logoUrl||''} onChange={e=>set('schema.logoUrl',e.target.value)}/></div><div className="col-md-6"><label className="form-label">Telefon</label><input className="form-control" value={schema.phone||''} onChange={e=>set('schema.phone',e.target.value)}/></div><div className="col-md-6"><label className="form-label">E-posta</label><input className="form-control" value={schema.email||''} onChange={e=>set('schema.email',e.target.value)}/></div></div></div></div>
    </div><div className="col-xl-4">
      <div className="card"><div className="card-header"><h4 className="card-title mb-1">Analytics & Dönüşüm</h4><p className="text-muted mb-0">ID girildiğinde storefront'ta otomatik etkinleşir.</p></div><div className="card-body pt-0"><div className="mb-3"><label className="form-label">Google Tag Manager</label><input className="form-control" placeholder="GTM-XXXXXXX" value={t.gtmId||''} onChange={e=>set('tracking.gtmId',e.target.value)}/></div><div className="mb-3"><label className="form-label">Google Analytics 4</label><input className="form-control" placeholder="G-XXXXXXXXXX" value={t.ga4Id||''} onChange={e=>set('tracking.ga4Id',e.target.value)}/></div><div className="mb-3"><label className="form-label">Meta / Facebook Pixel</label><input className="form-control" placeholder="Pixel ID" value={t.metaPixelId||''} onChange={e=>set('tracking.metaPixelId',e.target.value)}/></div><div className="mb-3"><label className="form-label">Google Ads Conversion ID</label><input className="form-control" placeholder="AW-XXXXXXXXX" value={t.googleAdsId||''} onChange={e=>set('tracking.googleAdsId',e.target.value)}/></div><div className="mb-0"><label className="form-label">Google Ads Satın Alma Etiketi</label><input className="form-control" placeholder="AbCdEf..." value={t.googleAdsPurchaseLabel||''} onChange={e=>set('tracking.googleAdsPurchaseLabel',e.target.value)}/><div className="form-text">Satın alma eventinde AW-ID/etiket olarak gönderilir.</div></div></div></div>
      <div className="card"><div className="card-header"><h4 className="card-title mb-1">Özel Head Alanı</h4><p className="text-muted mb-0">Doğrulama meta etiketleri ve özel kodlar.</p></div><div className="card-body pt-0"><textarea className="form-control font-monospace" rows={8} placeholder="<meta ...>" value={settings.customHeadHtml||''} onChange={e=>set('customHeadHtml',e.target.value)}/><div className="form-text">Storefront head katmanında yalnızca mağaza sahibinin eklediği kod olarak işlenir.</div></div></div>
    </div></div>
    <div className="card mt-3"><div className="card-header"><h4 className="card-title mb-0">SEO Kuralları ve Yönlendirmeler</h4></div><div className="card-body pt-0"><div className="table-responsive"><table className="table"><thead><tr><th>Kaynak/Hedef</th><th>Detay</th><th>Durum</th></tr></thead><tbody>{(data.redirects||[]).map((r:any)=><tr key={r.id}><td>{r.fromPath} → {r.toPath}</td><td>{r.statusCode}</td><td>{r.enabled?'Aktif':'Kapalı'}</td></tr>)}{!(data.redirects||[]).length&&<tr><td colSpan={3} className="text-muted">Henüz yönlendirme yok.</td></tr>}</tbody></table></div></div></div>
    <div className="settings-sticky-actions"><button className="btn btn-primary px-4" disabled={saving}><Icon icon="iconoir:floppy-disk" className="me-2"/>{saving?'Kaydediliyor…':'SEO Ayarlarını Kaydet'}</button></div>
  </form>
}
