'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import ProductCard from '../components/ProductCard';
import {api,STORE,getCurrency,getLocale} from '../../../lib/api';
import {useStorefrontTheme} from '../../../components/StorefrontThemeContext';

function ProductList(){
  const sp=useSearchParams();const theme=useStorefrontTheme();const ps=theme.design?.products||{};const template=Math.max(1,Math.min(8,Number(ps.categoryTemplate||1)));const filterMode=String(ps.filterLayout||({1:'sidebar',2:'horizontal',3:'drawer',4:'none',5:'sidebar-right',6:'horizontal',7:'sidebar',8:'none'} as any)[template]||'sidebar');const filtering=ps.enableFiltering!==false&&filterMode!=='none';const dynamicGrid=ps.dynamicGrid!==false;
  const[d,setD]=useState<any>(null);const[view,setView]=useState<'grid'|'list'>(template===8?'list':'grid');const[sort,setSort]=useState('featured');const[brand,setBrand]=useState(sp.get('brand')||'');const[minPrice,setMinPrice]=useState('');const[maxPrice,setMaxPrice]=useState('');const[attrFilters,setAttrFilters]=useState<Record<string,string>>({});const[filtersOpen,setFiltersOpen]=useState(false);const q=sp.get('q')||'';const category=sp.get('category')||'';
  async function load(){api(`/storefront/${STORE}/products?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&limit=60&currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`).then(setD)}
  useEffect(()=>{void load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[q,category]);
  const attributeOptions=useMemo(()=>{const map=new Map<string,Set<string>>();for(const p of d?.items||[])for(const v of p.variants||[])for(const[k,val]of Object.entries(v.attributes||{})){if(val===undefined||val===null||String(val)==='')continue;if(!map.has(k))map.set(k,new Set());map.get(k)!.add(String(val))}return Array.from(map.entries()).filter(([,v])=>v.size>1).slice(0,4)},[d]);
  const items=useMemo(()=>{let rows=[...(d?.items||[])];if(brand)rows=rows.filter((x:any)=>String(x.brand?.slug||x.brand?.name||'')===brand);const mn=Number(minPrice),mx=Number(maxPrice);if(minPrice)rows=rows.filter((x:any)=>Number(x.variants?.[0]?.price||0)>=mn);if(maxPrice)rows=rows.filter((x:any)=>Number(x.variants?.[0]?.price||0)<=mx);for(const[k,val]of Object.entries(attrFilters)){if(!val)continue;rows=rows.filter((p:any)=>(p.variants||[]).some((v:any)=>String(v.attributes?.[k]||'')===val))}if(sort==='price-asc')rows.sort((a:any,b:any)=>Number(a.variants?.[0]?.price||0)-Number(b.variants?.[0]?.price||0));if(sort==='price-desc')rows.sort((a:any,b:any)=>Number(b.variants?.[0]?.price||0)-Number(a.variants?.[0]?.price||0));if(sort==='name')rows.sort((a:any,b:any)=>String(a.title).localeCompare(String(b.title)));return rows},[d,brand,minPrice,maxPrice,attrFilters,sort]);
  const brands=useMemo(()=>Array.from(new Map((d?.items||[]).filter((x:any)=>x.brand).map((x:any)=>[String(x.brand.slug||x.brand.name),x.brand])).entries()),[d]);
  const colsD=Math.max(1,Math.min(6,Number(ps.columnsDesktop||4))),colsT=Math.max(1,Math.min(4,Number(ps.columnsTablet||3))),colsM=Math.max(1,Math.min(2,Number(ps.columnsMobile||2)));
  const filterContent=<><div className="facets__disclosure"><div className="facets__summary h5">Marka</div><div className="facets__display"><label className="facet-checkbox"><input type="radio" checked={!brand} onChange={()=>setBrand('')}/><span>Tümü</span></label>{brands.map(([key,b]:any)=><label className="facet-checkbox" key={key}><input type="radio" checked={brand===key} onChange={()=>setBrand(key)}/><span>{b.name}</span></label>)}</div></div><div className="facets__disclosure"><div className="facets__summary h5">Fiyat</div><div className="wok-price-filter"><input inputMode="decimal" placeholder="Min" value={minPrice} onChange={e=>setMinPrice(e.target.value)}/><span>—</span><input inputMode="decimal" placeholder="Max" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/></div></div>{attributeOptions.map(([name,values])=><div className="facets__disclosure" key={name}><div className="facets__summary h5">{name}</div><div className="facets__display"><label className="facet-checkbox"><input type="radio" checked={!attrFilters[name]} onChange={()=>setAttrFilters(x=>({...x,[name]:''}))}/><span>Tümü</span></label>{Array.from(values).map(value=><label className="facet-checkbox" key={value}><input type="radio" checked={attrFilters[name]===value} onChange={()=>setAttrFilters(x=>({...x,[name]:value}))}/><span>{value}</span></label>)}</div></div>)}</>;
  const gridStyle:any={'--ticarti-grid-desktop':colsD,'--ticarti-grid-tablet':colsT,'--ticarti-grid-mobile':colsM};
  return <main data-section-name="main-collection-product-grid" className={`wok-collection-template-${template} wok-filter-${filterMode}`}><div className="page-width"><div className="breadcrumbs body3 mt20"><a href="/">Anasayfa</a><span> / </span><span>{category||q||'Ürünler'}</span></div><div className="collection-title top-spacing-small"><span className="body3 text-uppercase">{category?'KOLEKSİYON':'KATALOG'}</span><h1 className="h1 mt8">{category?category:q?`“${q}” araması`:'Tüm Ürünler'}</h1></div>
  {filtering&&filterMode==='horizontal'&&<div className="wok-horizontal-filters">{filterContent}</div>}
  <div className="facets-toolbar mb40 toolbar__design_1">{filtering&&<button className="mobile-facets__button body2 strong" onClick={()=>setFiltersOpen(true)}>Filtre</button>}<div className="products_count body3">{items.length} ürün</div>{dynamicGrid&&<div className="grid-selector"><button className={`collection-grid__item ${view==='grid'?'active-d':''}`} onClick={()=>setView('grid')} aria-label="Grid görünümü">▦</button><button className={`collection-grid__item ${view==='list'?'active-d':''}`} onClick={()=>setView('list')} aria-label="Liste görünümü">☷</button></div>}<div className="sorting"><div className="select field"><select className="select__select field__input" aria-label="Sırala" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Önerilen</option><option value="name">Alfabetik</option><option value="price-asc">Fiyat artan</option><option value="price-desc">Fiyat azalan</option></select></div></div></div>
  <div className={`wok-collection-layout ${filterMode==='sidebar-right'?'is-right':''}`}>{filtering&&['sidebar','sidebar-right'].includes(filterMode)&&<aside className="facets facets__vertical wok-desktop-facets">{filterContent}</aside>}<div id="ProductGridContainer" className="product-grid__container"><div className={`collection__container ticarti-dynamic-grid ${view==='list'?'is-list':''}`} style={gridStyle}>{items.map((p:any)=><ProductCard key={p.id} p={p} currency={d?.currency}/>)}</div>{!items.length&&<div className="collection collection--empty text-center top-spacing-small"><h2 className="h3">Ürün bulunamadı</h2></div>}</div></div></div>
  {filtersOpen&&filtering&&<div className="wok-filter-drawer"><button className="popup-modal__overlay" onClick={()=>setFiltersOpen(false)} aria-label="Filtreleri kapat"/><aside className="facets facets__vertical is-open"><div className="wok-filter-drawer-head"><h3>Filtreler</h3><button onClick={()=>setFiltersOpen(false)}>×</button></div>{filterContent}</aside></div>}</main>
}
export default function Products(){return <Suspense fallback={<main className="page-width top-spacing-small">Ürünler yükleniyor…</main>}><ProductList/></Suspense>}
