'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {api,STORE,getCurrency,getLocale,mediaUrl,money} from '../../../lib/api';
import {readSavedIds,writeSavedIds} from '../../../lib/product-lists';

function attrs(p:any){const out:any={};for(const v of p?.variants||[]){for(const [k,val] of Object.entries(v?.attributes||{})){if(val!==undefined&&val!==null&&String(val)!=='')out[k]=Array.from(new Set([...(out[k]||[]),String(val)]))}}return out}
export default function ComparePage(){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 async function load(){const ids=readSavedIds('compare').slice(0,4);if(!ids.length){setItems([]);setLoading(false);return}setLoading(true);try{const r=await api(`/storefront/${STORE}/product-selection?ids=${encodeURIComponent(ids.join(','))}&currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`);setItems(Array.isArray(r?.items)?r.items:[])}catch(e:any){setError(e.message||'Karşılaştırma yüklenemedi')}finally{setLoading(false)}}
 useEffect(()=>{void load();const h=()=>void load();window.addEventListener('ticarti-saved-list-change',h as any);window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('ticarti-saved-list-change',h as any);window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[]);
 const keys=useMemo(()=>Array.from(new Set(items.flatMap(p=>Object.keys(attrs(p))))),[items]);
 function remove(id:string){writeSavedIds('compare',readSavedIds('compare').filter(x=>x!==String(id)))}
 return <main className="wok-customer-page page-width top-spacing-normal"><div className="wok-list-head"><div><span className="body3 text-uppercase">ÜRÜNLER</span><h1 className="mt8">Ürün Karşılaştırma</h1><p>En fazla dört ürünü yan yana karşılaştırın.</p></div>{items.length>0&&<button className="btn btn--border" onClick={()=>writeSavedIds('compare',[])}>Listeyi temizle</button>}</div>{error&&<div className="error">{error}</div>}{loading?<div className="wok-empty-state">Yükleniyor…</div>:!items.length?<div className="wok-empty-state"><h2>Karşılaştırma listeniz boş</h2><p>Ürün kartlarındaki karşılaştırma ikonunu kullanın.</p><Link className="btn" href="/products">Ürünleri görüntüle</Link></div>:<div className="wok-compare-scroll"><table className="wok-compare-table"><tbody><tr><th>Ürün</th>{items.map(p=><td key={p.id}><button className="wok-compare-remove" onClick={()=>remove(p.id)}>×</button><Link href={`/products/${p.slug}`} className="wok-compare-product">{p.images?.[0]?.url&&<img src={mediaUrl(p.images[0].url,'card','webp')} alt={p.title}/>}<strong>{p.title}</strong></Link></td>)}</tr><tr><th>Fiyat</th>{items.map(p=><td key={p.id}>{money(p.variants?.[0]?.price,p.displayCurrency||getCurrency())}</td>)}</tr><tr><th>Marka</th>{items.map(p=><td key={p.id}>{p.brand?.name||'—'}</td>)}</tr><tr><th>Stok</th>{items.map(p=><td key={p.id}>{p.variants?.some((v:any)=>!v.inventory?.trackStock||Number(v.inventory?.onHand||0)>Number(v.inventory?.reserved||0))?'Stokta':'Tükendi'}</td>)}</tr>{keys.map(k=><tr key={k}><th>{k}</th>{items.map(p=><td key={p.id}>{(attrs(p)[k]||[]).join(', ')||'—'}</td>)}</tr>)}</tbody></table></div>}</main>
}
