import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { IntegrationsService } from '../integrations/integrations.service';
import { MediaService } from '../media/media.service';

const DEFAULT_PROMPTS = [
  { id:'brand-character', category:'CHARACTER', name:'Marka Karakteri', prompt:'Markanın karakterini, tonunu ve kaçınılacak ifadeleri dikkate al.' },
  { id:'store-context', category:'STORE', name:'Mağaza Bilgisi', prompt:'Mağaza adı, hedef kitle, değer önerisi, iletişim ve bölgesel ayarları bağlam olarak kullan.' },
  { id:'product-copy', category:'PRODUCT', name:'Ürün İçeriği', prompt:'Ürün adı, teknik özellikler, faydalar, kullanım alanı, SEO ve satış dilini dengeli kullan.' },
  { id:'category-copy', category:'CATEGORY', name:'Kategori İçeriği', prompt:'Kategori kapsamını, anahtar kelimeleri ve ziyaretçi arama niyetini kullan.' },
  { id:'blog-editor', category:'BLOG', name:'Blog Editörü', prompt:'Bilgilendirici, okunabilir ve mağazanın ürünleriyle doğal bağ kuran içerik üret.' },
  { id:'promotion-copy', category:'PROMOTION', name:'Promosyon', prompt:'Kampanya koşullarını açık, kısa ve yanıltıcı olmayan biçimde anlat.' },
];

@Injectable()
export class AiService {
  constructor(private prisma: PrismaService, private integrations: IntegrationsService, private media: MediaService) {}

  private async store(tenantId:string,storeId?:string){
    if(storeId && storeId!==tenantId) throw new ForbiddenException('Site does not belong to tenant');
    const store=await this.prisma.tenant.findUnique({where:{id:tenantId}}); if(!store)throw new NotFoundException(); return store;
  }
  private config(store:any){const settings:any=store.settings||{};return {assistantEnabled:true,translationEnabled:false,imageEnabled:false,providerMode:'WE',assistantName:'WE AI',model:'',ownIntegrationId:'',...(settings.ai||{})};}
  private promptLibrary(store:any){const rows=(store.settings as any)?.aiPromptLibrary;return Array.isArray(rows)&&rows.length?rows:DEFAULT_PROMPTS;}
  private async wallet(tenantId:string){return this.prisma.aiCreditWallet.upsert({where:{tenantId},create:{tenantId,balance:0},update:{}})}
  private async ensureInstalled(tenantId:string){const row=await this.prisma.appInstallation.findFirst({where:{tenantId,enabled:true,status:'ACTIVE',app:{slug:'we-ai-assistant'}}});if(!row)throw new ForbiddenException('WE AI Asistan uygulaması kurulu veya aktif değil');}
  async status(tenantId:string){await this.ensureInstalled(tenantId);const store=await this.store(tenantId);const cfg=this.config(store);const wallet=await this.wallet(tenantId);const own=cfg.ownIntegrationId?await this.integrations.internalConnection(tenantId,String(cfg.ownIntegrationId)):null;return {config:cfg,wallet:{balance:wallet.balance,lifetimePurchased:wallet.lifetimePurchased,lifetimeUsed:wallet.lifetimeUsed},ownProviderConnected:!!own,prompts:this.promptLibrary(store)};}

  async saveSettings(tenantId:string,body:any){
    await this.ensureInstalled(tenantId); const store=await this.store(tenantId); const settings:any=store.settings||{}; const current=this.config(store); let ownIntegrationId=String(body.ownIntegrationId||current.ownIntegrationId||'');
    const creds=body.ownCredentials||{};
    if(body.providerMode==='OWN' && (creds.apiKey||creds.baseUrl)){
      if(ownIntegrationId){await this.integrations.update(tenantId,ownIntegrationId,{name:body.ownName||'Kendi AI Sağlayıcım',enabled:true,credentials:creds,config:{model:body.model||creds.model||''}})}
      else {const row=await this.integrations.create(tenantId,{type:'AI',provider:'openai-compatible',name:body.ownName||'Kendi AI Sağlayıcım',credentials:creds,config:{model:body.model||creds.model||''}});ownIntegrationId=row.id;}
    }
    const ai={...current,...Object.fromEntries(Object.entries(body).filter(([k])=>['assistantEnabled','translationEnabled','imageEnabled','providerMode','assistantName','model'].includes(k))),ownIntegrationId};
    await this.prisma.tenant.update({where:{id:tenantId},data:{settings:{...settings,ai}}});return this.status(tenantId);
  }

  async prompts(tenantId:string){await this.ensureInstalled(tenantId);const store=await this.store(tenantId);return {items:this.promptLibrary(store)};}
  async savePrompts(tenantId:string,body:any){await this.ensureInstalled(tenantId);const store=await this.store(tenantId);const settings:any=store.settings||{};const items=Array.isArray(body.items)?body.items.slice(0,100).map((x:any,i:number)=>({id:String(x.id||`prompt-${i+1}`),category:String(x.category||'CUSTOM'),name:String(x.name||'Prompt').slice(0,120),prompt:String(x.prompt||'').slice(0,8000)})):DEFAULT_PROMPTS;await this.prisma.tenant.update({where:{id:tenantId},data:{settings:{...settings,aiPromptLibrary:items}}});return {items};}

  async credits(tenantId:string){await this.ensureInstalled(tenantId);const wallet=await this.wallet(tenantId);let packages=await this.prisma.aiCreditPackage.findMany({where:{isActive:true},orderBy:{sortOrder:'asc'}});if(!packages.length)packages=[{id:'starter',name:'Başlangıç',code:'AI_1000',credits:1000,price:499 as any,currency:'TRY',isActive:true,sortOrder:10,createdAt:new Date(),updatedAt:new Date()},{id:'growth',name:'Growth',code:'AI_5000',credits:5000,price:1990 as any,currency:'TRY',isActive:true,sortOrder:20,createdAt:new Date(),updatedAt:new Date()},{id:'scale',name:'Scale',code:'AI_15000',credits:15000,price:4990 as any,currency:'TRY',isActive:true,sortOrder:30,createdAt:new Date(),updatedAt:new Date()}] as any;const ledger=await this.prisma.aiCreditLedger.findMany({where:{walletId:wallet.id},orderBy:{createdAt:'desc'},take:50});return {wallet,packages,ledger};}
  async purchase(tenantId:string,body:any){await this.ensureInstalled(tenantId);await this.store(tenantId);const code=String(body.packageCode||'');const pkg=await this.prisma.aiCreditPackage.findUnique({where:{code}});const virtual:any={AI_1000:{credits:1000,price:499,currency:'TRY'},AI_5000:{credits:5000,price:1990,currency:'TRY'},AI_15000:{credits:15000,price:4990,currency:'TRY'}}[code];const p:any=pkg||virtual;if(!p)throw new BadRequestException('AI credit package not found');const base=String(process.env.AI_CREDIT_CHECKOUT_URL||'').trim();if(!base)throw new BadRequestException('AI kredi ödeme bağlantısı henüz yapılandırılmadı');const u=new URL(base);u.searchParams.set('tenant',tenantId);u.searchParams.set('package',code);return {checkoutUrl:u.toString(),credits:Number(p.credits),price:Number(p.price),currency:p.currency||'TRY'};}

  private async provider(tenantId:string){const store=await this.store(tenantId);const cfg=this.config(store);if(cfg.providerMode==='OWN'){const row=await this.integrations.internalConnection(tenantId,String(cfg.ownIntegrationId||''));if(!row)throw new BadRequestException('Kendi AI sağlayıcınızı önce AI Asistan ayarlarından bağlayın');const c:any=row.credentials||{};return {kind:'OWN',baseUrl:String(c.baseUrl||'https://api.openai.com/v1').replace(/\/$/,''),apiKey:String(c.apiKey||''),model:String(cfg.model||c.model||(row.config as any)?.model||'gpt-4.1-mini'),imageModel:String(c.imageModel||(row.config as any)?.imageModel||'gpt-image-1')};}const key=String(process.env.WE_AI_API_KEY||'');if(!key)throw new BadRequestException('WE AI servisi henüz sunucu tarafında yapılandırılmadı');return {kind:'WE',baseUrl:String(process.env.WE_AI_BASE_URL||'https://api.openai.com/v1').replace(/\/$/,''),apiKey:key,model:String(cfg.model||process.env.WE_AI_MODEL||'gpt-4.1-mini'),imageModel:String(process.env.WE_AI_IMAGE_MODEL||'gpt-image-1')};}
  private async charge(tenantId:string,amount:number,source:string,description:string){if(amount<=0)return;const wallet=await this.wallet(tenantId);if(wallet.balance<amount)throw new BadRequestException('Yetersiz AI kredisi');await this.prisma.$transaction(async tx=>{const fresh=await tx.aiCreditWallet.findUnique({where:{id:wallet.id}});if(!fresh||fresh.balance<amount)throw new BadRequestException('Yetersiz AI kredisi');const balance=fresh.balance-amount;await tx.aiCreditWallet.update({where:{id:fresh.id},data:{balance,lifetimeUsed:{increment:amount}}});await tx.aiCreditLedger.create({data:{walletId:fresh.id,amount:-amount,type:'USAGE',source,description,balanceAfter:balance}});});}
  private async complete(tenantId:string,messages:any[],temperature=.3){const p=await this.provider(tenantId);if(p.kind==='WE'){const w=await this.wallet(tenantId);if(w.balance<1)throw new BadRequestException('Yetersiz AI kredisi');}const r=await fetch(p.baseUrl+'/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${p.apiKey}`},body:JSON.stringify({model:p.model,messages,temperature})});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new BadRequestException(j?.error?.message||'AI provider request failed');const text=String(j?.choices?.[0]?.message?.content||'').trim();if(p.kind==='WE')await this.charge(tenantId,1,'assistant','AI metin işlemi');return text;}
  private json(text:string){const clean=text.replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();try{return JSON.parse(clean)}catch{return null}}
  private localAction(message:string){const m=message.trim();const lower=m.toLocaleLowerCase('tr-TR');let x;if((x=lower.match(/(?:kategori ekle|kategori oluştur)\s+(.+)/)))return{type:'ADD_CATEGORY',label:`Kategori oluştur: ${x[1]}`,payload:{name:x[1]}};if((x=lower.match(/(?:ürün ekle|ürün oluştur)\s+(.+)/)))return{type:'ADD_PRODUCT',label:`Taslak ürün oluştur: ${x[1]}`,payload:{title:x[1]}};if((x=lower.match(/(?:promosyon ekle|promosyon oluştur)\s+(.+)/)))return{type:'ADD_PROMOTION',label:`Taslak promosyon oluştur: ${x[1]}`,payload:{name:x[1]}};if((x=lower.match(/(?:blog yazısı ekle|blog yazısı oluştur)\s+(.+)/)))return{type:'ADD_BLOG_POST',label:`Taslak blog yazısı oluştur: ${x[1]}`,payload:{title:x[1]}};if(['ürün ekle','ürün oluştur'].includes(lower))return{type:'NAVIGATE',label:'Ürün ekleme ekranını aç',payload:{href:'/catalog'}};if(['kategori ekle','kategori oluştur'].includes(lower))return{type:'NAVIGATE',label:'Kategori ekleme ekranını aç',payload:{href:'/catalog'}};if(['promosyon ekle','promosyon oluştur'].includes(lower))return{type:'NAVIGATE',label:'Promosyon ekranını aç',payload:{href:'/promotions'}};if(['blog yazısı ekle','blog yazısı oluştur'].includes(lower))return{type:'NAVIGATE',label:'Blog yazıları ekranını aç',payload:{href:'/blog/posts'}};if(lower.includes('ayarları aç')||lower==='ayarlar')return{type:'NAVIGATE',label:'Ayarları aç',payload:{href:'/settings'}};return null;}
  async chat(tenantId:string,body:any){await this.ensureInstalled(tenantId);const store=await this.store(tenantId,body.storeId);const cfg=this.config(store);if(!cfg.assistantEnabled)throw new BadRequestException('AI Asistan kapalı');const msg=String(body.message||'').trim();if(!msg)throw new BadRequestException('Mesaj gerekli');const local=this.localAction(msg);if(local)return{message:'İşlemi hazırladım. Uygulamadan önce aşağıdaki işlemi onaylayabilirsiniz.',action:local};const context={store:{name:store.name,companyName:store.companyName,currency:store.currency,locale:store.locale},allowedActions:['ADD_PRODUCT','ADD_CATEGORY','ADD_PROMOTION','ADD_BLOG_POST','NAVIGATE','NONE']};const text=await this.complete(tenantId,[{role:'system',content:`Sen ${cfg.assistantName||'WE AI'} adlı e-ticaret yönetim asistanısın. Türkçe, kısa ve eylem odaklı cevap ver. Kullanıcı bir yönetim işlemi isterse yalnız JSON döndür: {"message":"...","action":{"type":"ADD_PRODUCT|ADD_CATEGORY|ADD_PROMOTION|ADD_BLOG_POST|NAVIGATE","label":"...","payload":{...}}}. İşlem yoksa {"message":"...","action":null}. Bağlam: ${JSON.stringify(context)}`},{role:'user',content:msg}],.2);return this.json(text)||{message:text,action:null};}
  async execute(tenantId:string,body:any){await this.ensureInstalled(tenantId);const store=await this.store(tenantId,body.storeId);if(!this.config(store).assistantEnabled)throw new BadRequestException('AI Asistan kapalı');const a=body.action||{};const type=String(a.type||'');const p=a.payload||{};const slug=(v:any)=>String(v||'').trim().toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(type==='ADD_CATEGORY'){const name=String(p.name||'Yeni kategori').trim();const row=await this.prisma.category.create({data:{storeId:tenantId,name,slug:slug(p.slug||name),description:p.description||null,isActive:false}});return{ok:true,resource:'category',id:row.id,href:'/catalog'};}if(type==='ADD_PRODUCT'){const title=String(p.title||'Yeni ürün').trim();const row=await this.prisma.product.create({data:{storeId:tenantId,title,slug:slug(p.slug||title),description:p.description||null,status:'DRAFT',variants:{create:[{title:'Standart',sku:`AI-${Date.now()}`,price:Number(p.price||0),inventory:{create:{onHand:0}}}]}}});return{ok:true,resource:'product',id:row.id,href:'/catalog'};}if(type==='ADD_PROMOTION'){const name=String(p.name||'Yeni promosyon').trim();const value=Number(p.percentage||0);const row=await this.prisma.promotion.create({data:{storeId:tenantId,name,status:'DRAFT',activation:'AUTOMATIC',conditions:{operator:'AND',conditions:[]},actions:value?[{type:'percentage_discount',value}]:[]}});return{ok:true,resource:'promotion',id:row.id,href:'/promotions'};}if(type==='ADD_BLOG_POST'){const title=String(p.title||'Yeni blog yazısı').trim();const row=await this.prisma.blogPost.create({data:{storeId:tenantId,title,slug:slug(p.slug||title),excerpt:p.excerpt||null,body:String(p.body||''),status:'DRAFT',tags:Array.isArray(p.tags)?p.tags.map(String):[]}});return{ok:true,resource:'blogPost',id:row.id,href:'/blog/posts'};}if(type==='NAVIGATE')return{ok:true,href:String(p.href||'/dashboard')};throw new BadRequestException('Desteklenmeyen AI işlemi');}

  async translate(tenantId:string,body:any){await this.ensureInstalled(tenantId);const store=await this.store(tenantId,body.storeId);const cfg=this.config(store);if(!cfg.translationEnabled)throw new BadRequestException('AI Çeviri kapalı');const fields=body.fields&&typeof body.fields==='object'?body.fields:{};const emptyOnly=body.emptyOnly!==false;const target=String(body.targetLocale||'');if(!target)throw new BadRequestException('Hedef dil gerekli');const prompt=`Aşağıdaki e-ticaret alanlarını ${body.sourceLocale||store.locale} dilinden ${target} diline çevir. Marka adları, SKU, URL ve değişken ifadelerini {{...}} koru. Yalnız JSON döndür. ${emptyOnly?'Hedefte dolu olabilecek alanları değiştirmemek için yalnız verilen alanları çevir.':''}\n${JSON.stringify(fields)}`;const text=await this.complete(tenantId,[{role:'system',content:'Profesyonel e-ticaret yerelleştirme uzmanısın. JSON anahtarlarını değiştirme.'},{role:'user',content:prompt}],.15);const result=this.json(text);if(!result)throw new BadRequestException('AI geçerli çeviri JSON döndürmedi');return{fields:result};}

  private imagePrompt(body:any,store:any){const styles:any={STUDIO:'Temiz premium e-ticaret stüdyo fotoğrafı, nötr arka plan, ürün net ve gerçekçi.',LIFESTYLE:'Ürünü gerçek kullanım bağlamında doğal lifestyle fotoğrafı olarak göster.',DETAIL:'Ürünün malzeme, doku ve önemli detaylarına odaklanan yakın plan ürün fotoğrafı.',HERO:'Ana sayfa veya kategori hero alanına uygun geniş kompozisyon, metin için negatif alan bırak.',CATEGORY:'Kategori kimliğini temsil eden sade, premium e-ticaret görseli.',BLOG:'Editoryal blog kapak görseli, doğal ve profesyonel.',SOCIAL:'Sosyal medya kampanyasına uygun güçlü ama doğal kompozisyon.'};return `${styles[String(body.useCase||'STUDIO')]||styles.STUDIO} Mağaza: ${store.name}. ${String(body.prompt||'').trim()}`.trim();}
  async image(tenantId:string,body:any){await this.ensureInstalled(tenantId);const store=await this.store(tenantId,body.storeId);const cfg=this.config(store);if(!cfg.imageEnabled)throw new BadRequestException('AI Görsel kapalı');const p=await this.provider(tenantId);if(p.kind==='WE'){const w=await this.wallet(tenantId);if(w.balance<20)throw new BadRequestException('Görsel üretimi için yetersiz AI kredisi');}const prompt=this.imagePrompt(body,store);let r:Response;if(body.sourceImageUrl){const src=await fetch(String(body.sourceImageUrl));if(!src.ok)throw new BadRequestException('Referans görsel alınamadı');const buf=await src.arrayBuffer();const form=new FormData();form.set('model',p.imageModel);form.set('prompt',prompt);form.set('size',String(body.size||'1024x1024'));form.set('image',new Blob([buf],{type:src.headers.get('content-type')||'image/png'}),'reference.png');r=await fetch(p.baseUrl+'/images/edits',{method:'POST',headers:{authorization:`Bearer ${p.apiKey}`},body:form});}else r=await fetch(p.baseUrl+'/images/generations',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${p.apiKey}`},body:JSON.stringify({model:p.imageModel,prompt,size:String(body.size||'1024x1024')})});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new BadRequestException(j?.error?.message||'AI image provider request failed');const item=j?.data?.[0];let data:Buffer;let mime='image/png';if(item?.b64_json)data=Buffer.from(String(item.b64_json),'base64');else if(item?.url){const img=await fetch(String(item.url));if(!img.ok)throw new BadRequestException('Generated image could not be downloaded');data=Buffer.from(await img.arrayBuffer());mime=(img.headers.get('content-type')||'image/png').split(';')[0];}else throw new BadRequestException('AI provider returned no image');const asset=await this.media.saveGenerated(tenantId,tenantId,data,mime,'ai-generated.png',String(body.alt||''),{aiGenerated:true,useCase:body.useCase||'STUDIO',prompt,provider:p.kind});if(p.kind==='WE')await this.charge(tenantId,20,'image','AI görsel üretimi');return{asset};}
}
