import {BadRequestException, Injectable, NotFoundException, UnauthorizedException} from '@nestjs/common';
import {PrismaService} from '../prisma/prisma.service';
import {randomUUID} from 'crypto';
const Iyzipay:any=require('iyzipay');

@Injectable()
export class BillingService{
  constructor(private prisma:PrismaService){}
  private client(){const apiKey=String(process.env.IYZICO_API_KEY||'');const secretKey=String(process.env.IYZICO_SECRET_KEY||'');if(!apiKey||!secretKey)throw new BadRequestException('iyzico henüz yapılandırılmadı. IYZICO_API_KEY ve IYZICO_SECRET_KEY gerekli.');return new Iyzipay({apiKey,secretKey,uri:String(process.env.IYZICO_URI||'https://api.iyzipay.com')})}
  private callCreate(method:any,request:any){return new Promise<any>((resolve,reject)=>method.create(request,(err:any,result:any)=>err?reject(err):resolve(result)))}
  private callRetrieve(method:any,request:any){return new Promise<any>((resolve,reject)=>method.retrieve(request,(err:any,result:any)=>err?reject(err):resolve(result)))}
  async start(tenantId:string,userId:string,planId:string,body:any,ip:string){
    const [tenant,user,plan]=await Promise.all([this.prisma.tenant.findUnique({where:{id:tenantId}}),this.prisma.user.findUnique({where:{id:userId}}),this.prisma.plan.findFirst({where:{id:planId,isActive:true}})]);if(!tenant||!user||!plan)throw new NotFoundException('Mağaza, kullanıcı veya paket bulunamadı');
    const billing=String(body?.billing||'MONTHLY').toUpperCase()==='YEARLY'?'YEARLY':'MONTHLY';const amount=Number(billing==='YEARLY'?(plan.yearlyPrice??plan.monthlyPrice):plan.monthlyPrice);if(!(amount>0))throw new BadRequestException('Bu paket için online ödeme gerekmiyor.');
    const buyer=body?.buyer||{};const identity=String(buyer.identityNumber||tenant.taxNumber||'').replace(/\D/g,'');if(![10,11].includes(identity.length))throw new BadRequestException('Ödeme için 10 haneli VKN veya 11 haneli TCKN girin.');
    const full=String(buyer.name||user.name||tenant.companyName||tenant.name||'Müşteri').trim().split(/\s+/);const name=full.shift()||'Müşteri';const surname=full.join(' ')||'-';const phone=String(buyer.phone||tenant.phone||'').trim();const address=String(buyer.address||tenant.addressText||'').trim();const city=String(buyer.city||'Istanbul').trim();const zip=String(buyer.zipCode||'34000').trim();if(!phone||!address)throw new BadRequestException('Ödeme için telefon ve fatura adresi gerekli.');
    const conversationId=randomUUID();const attempt=await this.prisma.planPayment.create({data:{tenantId,planId,userId,billing,amount,currency:plan.currency||'TRY',conversationId}});
    const callbackBase=String(process.env.PUBLIC_API_URL||'https://dev.ticarti.com').replace(/\/$/,'');
    const request:any={locale:Iyzipay.LOCALE.TR,conversationId,price:amount.toFixed(2),paidPrice:amount.toFixed(2),currency:Iyzipay.CURRENCY.TRY,basketId:`PLAN-${attempt.id}`,paymentGroup:(Iyzipay.PAYMENT_GROUP?.SUBSCRIPTION||Iyzipay.PAYMENT_GROUP?.PRODUCT||'PRODUCT'),callbackUrl:`${callbackBase}/v1/billing/iyzico/callback?attempt=${encodeURIComponent(attempt.id)}`,enabledInstallments:[1],buyer:{id:user.id,name,surname,gsmNumber:phone,email:user.email,identityNumber:identity,lastLoginDate:new Date().toISOString().slice(0,19).replace('T',' '),registrationDate:user.createdAt.toISOString().slice(0,19).replace('T',' '),registrationAddress:address,ip:ip||'127.0.0.1',city,country:String(buyer.country||'Turkey'),zipCode:zip},shippingAddress:{contactName:`${name} ${surname}`,city,country:String(buyer.country||'Turkey'),address,zipCode:zip},billingAddress:{contactName:`${name} ${surname}`,city,country:String(buyer.country||'Turkey'),address,zipCode:zip},basketItems:[{id:plan.id,name:`Ticarti ${plan.name} - ${billing==='YEARLY'?'Yıllık':'Aylık'}`,category1:'SaaS',itemType:Iyzipay.BASKET_ITEM_TYPE.VIRTUAL,price:amount.toFixed(2)}]};
    const result=await this.callCreate(this.client().checkoutFormInitialize,request).catch(async(e:any)=>{await this.prisma.planPayment.update({where:{id:attempt.id},data:{status:'FAILED',raw:{error:String(e?.message||e)}}});throw new BadRequestException('iyzico ödeme ekranı başlatılamadı.');});
    if(result?.status!=='success'||!result?.checkoutFormContent){await this.prisma.planPayment.update({where:{id:attempt.id},data:{status:'FAILED',raw:result||{}}});throw new BadRequestException(result?.errorMessage||'iyzico ödeme ekranı başlatılamadı.');}
    await this.prisma.planPayment.update({where:{id:attempt.id},data:{token:result.token||null,raw:{checkoutFormContent:result.checkoutFormContent}}});
    return {attemptId:attempt.id,paymentUrl:`${callbackBase}/v1/billing/iyzico/pay/${attempt.id}`};
  }
  async paymentPage(id:string){const row=await this.prisma.planPayment.findUnique({where:{id}});if(!row||row.status!=='PENDING')throw new NotFoundException();const content=(row.raw as any)?.checkoutFormContent;if(!content)throw new NotFoundException();return String(content)}
  async callback(attemptId:string,token:string){
    const row=await this.prisma.planPayment.findUnique({where:{id:attemptId},include:{tenant:true,plan:true}});if(!row)throw new NotFoundException();if(!token)throw new BadRequestException('iyzico token eksik');
    const result=await this.callRetrieve(this.client().checkoutForm,{locale:Iyzipay.LOCALE.TR,conversationId:row.conversationId,token});const success=result?.status==='success'&&result?.paymentStatus==='SUCCESS';
    if(success){const now=new Date();const end=new Date(now);if(row.billing==='YEARLY')end.setFullYear(end.getFullYear()+1);else end.setMonth(end.getMonth()+1);await this.prisma.$transaction(async tx=>{await tx.planPayment.update({where:{id:row.id},data:{status:'PAID',providerPaymentId:String(result.paymentId||''),paidAt:now,raw:result}});await tx.subscription.updateMany({where:{tenantId:row.tenantId,status:{in:['ACTIVE','TRIAL']}},data:{status:'CANCELLED'}});await tx.subscription.create({data:{tenantId:row.tenantId,planId:row.planId,status:'ACTIVE',startsAt:now,currentPeriodStart:now,currentPeriodEnd:end}});await tx.tenant.update({where:{id:row.tenantId},data:{status:'ACTIVE'}})});}else await this.prisma.planPayment.update({where:{id:row.id},data:{status:'FAILED',raw:result||{}}});
    const host=row.tenant.domain||`${row.tenant.publicSlug}.ticarti.com`;return {success,redirect:`https://${host}/admin/plans?payment=${success?'success':'failed'}`};
  }
  async startTheme(tenantId:string,userId:string,themeId:string,body:any,ip:string){
    const [tenant,user,theme,sub]=await Promise.all([
      this.prisma.tenant.findUnique({where:{id:tenantId}}),
      this.prisma.user.findUnique({where:{id:userId}}),
      this.prisma.themeDefinition.findFirst({where:{id:themeId,isActive:true}}),
      this.prisma.subscription.findFirst({where:{tenantId,status:{in:['ACTIVE','TRIAL']}},orderBy:{createdAt:'desc'},select:{planId:true}})
    ]);if(!tenant||!user||!theme)throw new NotFoundException('Mağaza, kullanıcı veya tema bulunamadı');
    const planPrice=sub?.planId?await this.prisma.themePlanPrice.findFirst({where:{themeId,planId:sub.planId,isActive:true}}):null;
    if(planPrice?.included){await this.prisma.themeInstallation.upsert({where:{tenantId_themeId:{tenantId,themeId}},create:{tenantId,themeId,status:'ACTIVE',source:'PLAN',purchasedPrice:0,currency:planPrice.currency||theme.currency},update:{status:'ACTIVE',source:'PLAN'}});return{included:true};}
    const already=await this.prisma.themeInstallation.findUnique({where:{tenantId_themeId:{tenantId,themeId}}});if(already?.status==='ACTIVE')return{owned:true};
    const amount=Number(planPrice?.price??theme.basePrice??0);if(!(amount>0)){await this.prisma.themeInstallation.upsert({where:{tenantId_themeId:{tenantId,themeId}},create:{tenantId,themeId,status:'ACTIVE',source:'FREE',purchasedPrice:0,currency:theme.currency},update:{status:'ACTIVE'}});return{owned:true};}
    const buyer=body?.buyer||{};const identity=String(buyer.identityNumber||tenant.taxNumber||'').replace(/\D/g,'');if(![10,11].includes(identity.length))throw new BadRequestException('Ödeme için 10 haneli VKN veya 11 haneli TCKN girin.');
    const full=String(buyer.name||user.name||tenant.companyName||tenant.name||'Müşteri').trim().split(/\s+/);const name=full.shift()||'Müşteri';const surname=full.join(' ')||'-';const phone=String(buyer.phone||tenant.phone||'').trim();const address=String(buyer.address||tenant.addressText||'').trim();const city=String(buyer.city||'Istanbul').trim();const zip=String(buyer.zipCode||'34000').trim();if(!phone||!address)throw new BadRequestException('Ödeme için telefon ve fatura adresi gerekli.');
    const conversationId=randomUUID();const attempt=await this.prisma.themePayment.create({data:{tenantId,themeId,userId,amount,currency:planPrice?.currency||theme.currency||'TRY',conversationId}});
    const callbackBase=String(process.env.PUBLIC_API_URL||'https://dev.ticarti.com').replace(/\/$/,'');const currency=String(planPrice?.currency||theme.currency||'TRY');
    const request:any={locale:Iyzipay.LOCALE.TR,conversationId,price:amount.toFixed(2),paidPrice:amount.toFixed(2),currency:(Iyzipay.CURRENCY?.[currency]||currency),basketId:`THEME-${attempt.id}`,paymentGroup:(Iyzipay.PAYMENT_GROUP?.PRODUCT||'PRODUCT'),callbackUrl:`${callbackBase}/v1/billing/iyzico/theme-callback?attempt=${encodeURIComponent(attempt.id)}`,enabledInstallments:[1],buyer:{id:user.id,name,surname,gsmNumber:phone,email:user.email,identityNumber:identity,lastLoginDate:new Date().toISOString().slice(0,19).replace('T',' '),registrationDate:user.createdAt.toISOString().slice(0,19).replace('T',' '),registrationAddress:address,ip:ip||'127.0.0.1',city,country:String(buyer.country||'Turkey'),zipCode:zip},shippingAddress:{contactName:`${name} ${surname}`,city,country:String(buyer.country||'Turkey'),address,zipCode:zip},billingAddress:{contactName:`${name} ${surname}`,city,country:String(buyer.country||'Turkey'),address,zipCode:zip},basketItems:[{id:theme.id,name:`Ticarti Tema - ${theme.name}`,category1:'Theme',itemType:Iyzipay.BASKET_ITEM_TYPE.VIRTUAL,price:amount.toFixed(2)}]};
    const result=await this.callCreate(this.client().checkoutFormInitialize,request).catch(async(e:any)=>{await this.prisma.themePayment.update({where:{id:attempt.id},data:{status:'FAILED',raw:{error:String(e?.message||e)}}});throw new BadRequestException('iyzico ödeme ekranı başlatılamadı.');});
    if(result?.status!=='success'||!result?.checkoutFormContent){await this.prisma.themePayment.update({where:{id:attempt.id},data:{status:'FAILED',raw:result||{}}});throw new BadRequestException(result?.errorMessage||'iyzico ödeme ekranı başlatılamadı.');}
    await this.prisma.themePayment.update({where:{id:attempt.id},data:{token:result.token||null,raw:{checkoutFormContent:result.checkoutFormContent}}});return{attemptId:attempt.id,paymentUrl:`${callbackBase}/v1/billing/iyzico/theme-pay/${attempt.id}`};
  }
  async themePaymentPage(id:string){const row=await this.prisma.themePayment.findUnique({where:{id}});if(!row||row.status!=='PENDING')throw new NotFoundException();const content=(row.raw as any)?.checkoutFormContent;if(!content)throw new NotFoundException();return String(content)}
  async themeCallback(attemptId:string,token:string){
    const row=await this.prisma.themePayment.findUnique({where:{id:attemptId},include:{tenant:true,theme:true}});if(!row)throw new NotFoundException();if(!token)throw new BadRequestException('iyzico token eksik');
    const result=await this.callRetrieve(this.client().checkoutForm,{locale:Iyzipay.LOCALE.TR,conversationId:row.conversationId,token});const success=result?.status==='success'&&result?.paymentStatus==='SUCCESS';
    if(success){const now=new Date();await this.prisma.$transaction(async tx=>{await tx.themePayment.update({where:{id:row.id},data:{status:'PAID',providerPaymentId:String(result.paymentId||''),paidAt:now,raw:result}});await tx.themeInstallation.upsert({where:{tenantId_themeId:{tenantId:row.tenantId,themeId:row.themeId}},create:{tenantId:row.tenantId,themeId:row.themeId,status:'ACTIVE',source:'PURCHASED',purchasedPrice:row.amount,currency:row.currency,installedAt:now},update:{status:'ACTIVE',source:'PURCHASED',purchasedPrice:row.amount,currency:row.currency}})})}else await this.prisma.themePayment.update({where:{id:row.id},data:{status:'FAILED',raw:result||{}}});
    const host=row.tenant.domain||`${row.tenant.publicSlug}.ticarti.com`;return{success,redirect:`https://${host}/admin/design-content?themePayment=${success?'success':'failed'}`};
  }

}
