import Link from 'next/link';
import PlatformPlans from './PlatformPlans';
import PlatformAccount from '../components/PlatformAccount';

export default function TicartiHome(){return <div className="ticarti-site">
  <header className="ticarti-nav"><Link className="ticarti-logo" href="/">ticarti<span>.</span></Link><nav><Link href="/paketler">Paketler</Link><span>Çözümler</span><a href="https://app.ticarti.com/">Uygulamalar</a><span>Kaynaklar</span></nav><div className="ticarti-nav-actions"><PlatformAccount/><Link className="ticarti-btn primary" href="/ucretsiz-dene">Ücretsiz Dene</Link></div></header>
  <main>
    <section className="ticarti-hero"><div className="ticarti-kicker">TÜRKİYE İÇİN MODERN E-TİCARET ALTYAPISI</div><h1>E-ticaretini kur.<br/><em>Büyümeye odaklan.</em></h1><p>Mağaza, sipariş, ürün, kampanya, entegrasyon ve yapay zekâ araçlarını tek bir güçlü platformda yönetin.</p><div className="ticarti-hero-actions"><Link className="ticarti-btn primary large" href="/ucretsiz-dene">Ücretsiz Dene</Link><Link className="ticarti-btn large" href="/paketler">Paketleri İncele</Link></div><div className="ticarti-trust"><span>✓ Kredi kartı gerekmez</span><span>✓ Hızlı kurulum</span><span>✓ Türkiye odaklı altyapı</span></div></section>
    <section className="ticarti-mock"><div className="ticarti-mockbar"><i/><i/><i/><b>ticarti yönetim paneli</b></div><div className="ticarti-mockbody"><aside><strong>Genel Bakış</strong><span>Siparişler</span><span>Ürünler</span><span>Müşteriler</span><span>Kampanyalar</span><span>Tasarım</span></aside><div><div className="ticarti-metrics"><article><small>Bugünkü satış</small><b>₺84.920</b><em>+18.4%</em></article><article><small>Siparişler</small><b>126</b><em>+12.1%</em></article><article><small>Dönüşüm</small><b>%4,8</b><em>+0.7%</em></article></div><div className="ticarti-chart"><span/><span/><span/><span/><span/><span/><span/><span/><span/></div></div></div></section>
    <section className="ticarti-feature-section"><div className="ticarti-section-head"><span>TEK PLATFORM</span><h2>E-ticaret operasyonunun her noktası birbiriyle konuşur.</h2></div><div className="ticarti-features"><article><b>01</b><h3>Satış kanalları</h3><p>Pazaryeri ve mağaza siparişlerini merkezi yapıda yönetin.</p></article><article><b>02</b><h3>Akıllı yönetim</h3><p>Canlı takip, raporlar ve operasyon araçlarıyla anlık görünürlük kazanın.</p></article><article><b>03</b><h3>Esnek tasarım</h3><p>Mağazanızı modüler tasarım editörüyle markanıza göre şekillendirin.</p></article></div></section>
    <section className="ticarti-pricing-section"><div className="ticarti-section-head"><span>PAKETLER</span><h2>İhtiyacınız kadar başlayın, büyüdükçe geliştirin.</h2><Link href="/paketler">Tüm paketleri gör →</Link></div><PlatformPlans compact/></section>
    <section className="ticarti-cta"><div><span>BUGÜN BAŞLAYIN</span><h2>Yeni mağazanızı ticarti ile büyütün.</h2></div><Link className="ticarti-btn light large" href="/ucretsiz-dene">Mağazanı Aç</Link></section>
  </main>
  <footer className="ticarti-footer"><Link className="ticarti-logo" href="/">ticarti<span>.</span></Link><p>Türkiye için yeni nesil e-ticaret altyapısı.</p><div><Link href="/paketler">Paketler</Link><a href="https://login.ticarti.com/">Giriş</a></div><small>© {new Date().getFullYear()} Ticarti. Tüm hakları saklıdır.</small></footer>
</div>}
