'use client';
import Link from 'next/link';

const storeLinks=[['NEW!','/products?category=lingerie'],['Bras','/products?category=bras'],['Panties','/products?category=panties'],['Sleep','/products?category=sleep'],['Lingerie','/products?category=lingerie'],['Apparel','/products?category=apparel'],['Swim','/products?category=swim'],['SALE','/products?category=sale']];
const infoLinks=[['About','/pages/about'],['Our Blog','/blog'],['Shipping & Returns','/pages/shipping-returns'],['Payment','/pages/payment'],['Warranty','/pages/warranty'],['Location','/pages/location'],['Contacts','/pages/contacts-us']];
const socialLinks=[['Facebook','#'],['Instagram','#'],['Pinterest','#']];
function LinkColumn({title,items}:{title:string;items:string[][]}){return <div className="footer__block-item"><div className="footer__block-heading link-list__block-heading"><h2 className="h5 mt0 mb0">{title}</h2></div><div className="footer__accordion__content link-list__block-item"><ul className="unstyle-ul">{items.map(([label,href])=><li key={label}><Link className="font-inherit footer-link__item link link-hover-span link__base-to_accent-color link--medium" href={href}><span>{label}</span></Link></li>)}</ul></div></div>}
export default function Footer({boot}:{boot:any}){const store=boot?.store||{};return <>
  <section id="theme-section-sections--15772574416978__newsletter_signup_nqURNF" className="top-spacing-normal section-background section-background--medium" data-section-name="newsletter-signup"><div className="page-width"><div className="section-header__container text-left"><div className="section-header__item"><div className="body3 text-uppercase">Newsletter Signup</div><h2 className="h2 mt8 mb0">Exclusive Offers &amp; Style Inspiration</h2></div></div><form className="newsletter-form mt20" onSubmit={e=>e.preventDefault()}><div className="field field-with-icon"><input className="field__input" placeholder="Email" aria-label="Email" type="email"/><button className="field__icon" aria-label="Subscribe">→</button></div></form><div className="rte body3 mt15"><p>By clicking the button you agree to the <Link href="/pages/privacy">Privacy Policy</Link> and <Link href="/pages/terms">Terms and Conditions</Link>.</p></div></div></section>
  <footer id="theme-section-sections--15772574416978__footer" className="footer top-spacing-none section-sections--15772574416978__footer section-background section-background--medium" data-section-name="wokiee-footer"><div className="page-width"><div className="footer-blocks__content"><div className="page-grid-sp-1 page-grid-st-2 page-grid-md-2 page-grid-4 footer__block__items page-vertical-gap-40 footer__accordion"><LinkColumn title="Store" items={storeLinks}/><LinkColumn title="Information" items={infoLinks}/><LinkColumn title="Social" items={socialLinks}/><div className="footer__block-item"><div className="footer__block-heading"><h2 className="h5 mt0 mb0">Contacts</h2></div><div className="footer__accordion__content"><div className="rte body3 mt10"><h4>T: 555-555-1000</h4></div><div className="rte body3 mt10"><p>Open daily from 9:00 AM – 7:00 PM</p><p>Address:123 Madison Avenue, Suite 456<br/>New York, NY 10010, USA</p></div></div></div></div></div></div><div className="page-width"><div className="footer__content-bottom footer__content-bottom--space-between"><div className="footer__content-bottom--left"><div className="footer__copyright body3"><span className="copyright__content">© {new Date().getFullYear()} {String(store.name||'Ticarti')}. All Rights Reserved</span></div></div><div className="footer__content-bottom--right"><div className="footer__payment"><ul className="unstyle-ul list-payment" role="list"><li className="list-payment__item">VISA</li><li className="list-payment__item">MC</li><li className="list-payment__item">AMEX</li></ul></div></div></div></div></footer>
</>}
