'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import ProductCard from '../../components/ProductCard';
import {api,STORE,getCurrency,getLocale} from '../../lib/api';
const A='/signature-assets/';
function I({name}:{name:string}){return <img className="theme-icon" width="20" height="20" src={`${A}${name}.svg`} alt="" aria-hidden="true"/>}
function ProductList(){
  const sp=useSearchParams();const[d,setD]=useState<any>(null);const[sort,setSort]=useState('featured');const[brand,setBrand]=useState('');const[filtersOpen,setFiltersOpen]=useState(false);const[grid,setGrid]=useState(4);
  const q=sp.get('q')||'';const category=sp.get('category')||'';
  async function load(){api(`/storefront/${STORE}/products?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}&limit=48`).then(setD)}
  useEffect(()=>{void load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[q,category]);
  const items=useMemo(()=>{let rows=[...(d?.items||[])];if(brand)rows=rows.filter((x:any)=>String(x.brand?.slug||x.brand?.name||'')===brand);if(sort==='price-asc')rows.sort((a:any,b:any)=>Number(a.variants?.[0]?.price||0)-Number(b.variants?.[0]?.price||0));if(sort==='price-desc')rows.sort((a:any,b:any)=>Number(b.variants?.[0]?.price||0)-Number(a.variants?.[0]?.price||0));if(sort==='name')rows.sort((a:any,b:any)=>String(a.title).localeCompare(String(b.title)));return rows},[d,brand,sort]);
  const brands=useMemo(()=>Array.from(new Map((d?.items||[]).filter((x:any)=>x.brand).map((x:any)=>[String(x.brand.slug||x.brand.name),x.brand])).entries()),[d]);
  if(!d)return <main className="page-width top-spacing-normal">Ürünler yükleniyor…</main>;
  return <main id="MainContent" className="content-for-layout focus-none"><section className="top-spacing-normal"><div className="page-width text-center"><div className="body3 text-uppercase">{category?'Koleksiyon':'Katalog'}</div><h1 className="h1 mt8">{category?category:q?`“${q}” araması`:'Tüm Ürünler'}</h1><p className="body2 mt10">{d?.pagination?.total??items.length} ürün</p></div></section><section className="top-spacing-normal"><div className="page-width"><div className="facets-toolbar mb40"><button className="mobile-facets__button body2 strong" onClick={()=>setFiltersOpen(true)}><I name="icon-filter"/> Filtreler</button><div className="grid-selector display-flex"><button className={grid===2?'active':''} onClick={()=>setGrid(2)}>▦</button><button className={grid===3?'active':''} onClick={()=>setGrid(3)}>▦</button><button className={grid===4?'active':''} onClick={()=>setGrid(4)}>▦</button></div><div className="sorting"><div className="select field"><select className="field__input" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Önerilen</option><option value="name">İsme göre</option><option value="price-asc">Fiyat: düşükten yükseğe</option><option value="price-desc">Fiyat: yüksekten düşüğe</option></select><span className="field__icon field__icon--select">⌄</span></div></div></div><div className="page-grid-1 no-row-gap"><div className="product-grid__container"><div className={`page-grid-${grid} page-grid-st-3 page-grid-sp-2 collection__container page-vertical-gap-40`}>{items.map((p:any)=><ProductCard key={p.id} p={p} currency={d?.currency}/>)}</div></div></div></div></section>
  {filtersOpen&&<div className="popup-modal popup-modal__left active"><button className="popup-modal__overlay" onClick={()=>setFiltersOpen(false)} aria-label="Filtreleri kapat"/><div className="popup-modal__content popup-modal__content__f-height"><button className="popup-modal__toggle" onClick={()=>setFiltersOpen(false)}><I name="icon-close"/></button><div className="popup-modal__content__data custom__scrollbar page-width"><h3 className="h5 mt40">Filtreler</h3><div className="facets__display mt30"><div className="facets__header"><span className="body2 strong">Marka</span></div><ul className="facets__list unstyle-ul mt15"><li><label className="facet-checkbox body2"><input type="radio" checked={!brand} onChange={()=>setBrand('')}/> Tümü</label></li>{brands.map(([key,b]:any)=><li key={key}><label className="facet-checkbox body2"><input type="radio" checked={brand===key} onChange={()=>setBrand(key)}/> {b.name}</label></li>)}</ul></div><button className="btn w-full mt30" onClick={()=>setFiltersOpen(false)}>Sonuçları göster</button></div></div></div>}
  </main>;
}
export default function Products(){return <Suspense fallback={<main className="page-width top-spacing-normal">Ürünler yükleniyor…</main>}><ProductList/></Suspense>}
