'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import ProductCard from '../components/ProductCard';
import {api,STORE,getCurrency,getLocale,mediaUrl,money} from '../../../lib/api';
import {sourceHomePreset} from '../config/home-preset';
function take(v:any,n=8){return (Array.isArray(v)?v:[]).slice(0,n)}
function normalizeType(v:any){return String(v||'').replaceAll('_','-').toLowerCase()}
function mergeSourcePreset(saved:any[]){
  const source=sourceHomePreset();
  if(!Array.isArray(saved)||!saved.length)return source;
  const used=new Set<number>();
  return source.map((base:any)=>{
    const baseType=normalizeType(base.sectionType);
    let idx=saved.findIndex((x:any,i:number)=>!used.has(i)&&String(x?.id||'')===String(base.id||''));
    if(idx<0)idx=saved.findIndex((x:any,i:number)=>!used.has(i)&&normalizeType(x?.sectionType)===baseType);
    if(idx<0)return base;
    used.add(idx);
    const x=saved[idx]||{};
    return {...base,...x,id:base.id,sectionType:base.sectionType,settings:{...(base.settings||{}),...(x.settings||{})}};
  });
}
function draftSectionsFromEvent(detail:any){
  if(detail?.kind==='sections'&&Array.isArray(detail.sections))return detail.sections;
  if(detail?.kind==='design'){
    if(Array.isArray(detail?.design?.sections))return detail.design.sections;
    if(Array.isArray(detail?.design?.home?.sections))return detail.design.home.sections;
  }
  return null;
}
export default function Home(){
  const[d,setD]=useState<any>(null);const[e,setE]=useState('');const[draftSections,setDraftSections]=useState<any[]|null>(null);
  async function load(){api('/storefront/'+STORE+'?currency='+encodeURIComponent(getCurrency())+'&locale='+encodeURIComponent(getLocale())).then(setD).catch(x=>setE(x.message))}
  useEffect(()=>{void load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[]);
  useEffect(()=>{const h=(event:any)=>{const detail=event?.detail;const full=draftSectionsFromEvent(detail);if(full){setDraftSections(full);return}if(detail?.kind==='section'&&detail.section)setDraftSections(current=>{const base=current||(Array.isArray(d?.sections)?d.sections:[]);const id=String(detail.section.id||'');const type=normalizeType(detail.section.sectionType);let hit=false;const next=base.map((x:any)=>{if((id&&String(x.id)===id)||(!id&&normalizeType(x.sectionType)===type)){hit=true;return {...x,...detail.section,settings:{...(x.settings||{}),...(detail.section.settings||{})}}}return x});return hit?next:[...next,detail.section]})};window.addEventListener('ticarti-design-draft',h as EventListener);return()=>window.removeEventListener('ticarti-design-draft',h as EventListener)},[d]);
  if(e)return <main className="page-width top-spacing-small"><div className="error">{e}</div></main>;if(!d)return <main className="page-width top-spacing-small">Loading…</main>;const incoming=(draftSections||d.sections||[]).filter((x:any)=>x.enabled!==false);const sections=mergeSourcePreset(incoming).filter((x:any)=>x.enabled!==false);
  return <main>{sections.length?sections.map((section:any)=><div key={section.id} className="design-section-anchor" data-design-target={'section:'+section.id} data-design-label={String(section.settings?.title||section.sectionType||'Section')}><SourceSection section={section} data={d}/></div>):<><Slider s={{}} data={d}/><Featured s={{title:'Featured products'}} data={d}/><Categories s={{title:'Collections'}} data={d}/></>}</main>
}
function SectionHead({s,title}:{s:any;title:string}){return <div className="section-header__container text-center"><div className="section-header__item"><h2 className="h2 mt0 mb0">{s.title||title}</h2>{s.subtitle&&<div className="body2 mt10">{s.subtitle}</div>}</div></div>}
function SourceSection({section,data}:{section:any;data:any}){const s=section.settings||{};const type=String(section.sectionType||'').replaceAll('_','-');if(['slider','video-hero','hero'].includes(type))return <Slider s={s} data={data}/>;if(['featured-collection','featured-collection-row','product-grid','product-list','products','product-slider','recommendations','recently-viewed'].includes(type))return <Featured s={s} data={data}/>;if(['collection-list','popular-categories','categories','category-slider'].includes(type))return <Categories s={s} data={data}/>;if(['banner-collage','banners','banner'].includes(type))return <Banners s={s} data={data}/>;if(['ticker-text','ticker-collection'].includes(type))return <Ticker s={s} data={data}/>;if(type==='featured-product')return <FeaturedProduct s={s} data={data}/>;if(['brands-grid','brands-list','brands'].includes(type))return <Brands s={s} data={data}/>;if(['shop-the-feed','shoppable-feed','gallery','masonry-gallery'].includes(type))return <Gallery s={s} data={data}/>;if(['blog-posts','blog'].includes(type))return <BlogPosts s={s} data={data}/>;if(['wokiee-review','review','reviews'].includes(type))return <Reviews s={s} data={data}/>;return <Banners s={s} data={data}/>}
function Slider({s,data}:{s:any;data:any}){const slides=Array.isArray(s.items)&&s.items.length?s.items:[{title:s.title||data.store?.settings?.homeTitle||data.store?.name,subtitle:s.subtitle,content:s.content,buttonText:s.buttonText||'Explore Now!',linkUrl:s.linkUrl||'/products',imageUrl:s.imageUrl||data.banners?.find((x:any)=>x.position==='home_hero')?.imageUrl||data.categories?.[0]?.imageUrl}];const[i,setI]=useState(0);useEffect(()=>{if(slides.length<2)return;const t=window.setInterval(()=>setI(x=>(x+1)%slides.length),Math.max(3000,Number(s.autoplaySeconds||5)*1000));return()=>window.clearInterval(t)},[slides.length,s.autoplaySeconds]);return <section data-section-name="slider" className="top-spacing-none"><div className="page-fullwidth section-slider__container"><div className="page-grid-1 section-slider__container__page"><div className="section-slider"><div className="swiper swiper-loop"><div className="swiper-wrapper">{slides.map((x:any,n:number)=>{const img=x.imageUrl||data.banners?.[n]?.imageUrl||data.categories?.[n]?.imageUrl;return <div className={`swiper-slide ${n===i?'swiper-slide-active':'hide'}`} key={n}><div className="banner__block-item image-hover-box" style={{minHeight:Number(s.heightDesktop||620),backgroundImage:img?`linear-gradient(90deg,rgba(0,0,0,.35),rgba(0,0,0,.03)),url(${img})`:undefined,backgroundSize:'cover',backgroundPosition:'center'}}><div className="page-width h-full display-flex align-items-center"><div className="banner__block-item__content"><div className="banner__block-item__description"><div className="body2 text-uppercase">{x.subtitle}</div><h1 className="banner__block-item__heading h1 mt10">{x.title}</h1>{x.content&&<p className="body2 mt15">{x.content}</p>}<Link className="btn mt20" href={x.linkUrl||'/products'}><span className="btn__texts"><span className="btn__top-text is-visible">{x.buttonText||'Explore Now!'}</span></span></Link></div></div></div></div></div>})}</div>{slides.length>1&&<div className="swiper-control-container justify-content-center"><button className="internal-swiper-button-prev" onClick={()=>setI((i-1+slides.length)%slides.length)}>‹</button><div className="swiper-pagination">{slides.map((_:any,n:number)=><button className={n===i?'active':''} key={n} onClick={()=>setI(n)}>•</button>)}</div><button className="internal-swiper-button-next" onClick={()=>setI((i+1)%slides.length)}>›</button></div>}</div></div></div></div></section>}
function Featured({s,data}:{s:any;data:any}){const products=take(data.featured,Number(s.count||8));return <section data-section-name="featured-collection" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Featured products"/><div className="page-grid-sp-2 page-grid-st-3 page-grid-4 page-vertical-gap-40 mt30">{products.map((p:any)=><ProductCard key={p.id} p={p} currency={data.store?.currency}/>)}</div><div className="mt40 page-grid-1 text-center"><Link href={s.linkUrl||'/products'} className="btn btn--border btn__transition-text btn-wide">{s.buttonText||'View all'}</Link></div></div></section>}
function Categories({s,data}:{s:any;data:any}){return <section data-section-name="banners" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Collections"/><div className="page-grid-sp-2 page-grid-st-3 page-grid-4 mt30">{take(data.categories,Number(s.count||8)).map((c:any)=><Link className="banner__block-item clear-underline" href={'/products?category='+c.slug} key={c.id}><div className="image-hover-box__container">{c.imageUrl?<img className="image-hover-box" src={mediaUrl(c.imageUrl,'category','webp')} alt={c.name}/>:<div className="image-hover-box"/>}</div><div className="banner__block-item__content text-center mt15"><h3 className="h5">{c.name}</h3></div></Link>)}</div></div></section>}
function Banners({s,data}:{s:any;data:any}){const src=Array.isArray(s.items)&&s.items.length?s.items:take(data.categories,3).map((c:any)=>({title:c.name,imageUrl:c.imageUrl,linkUrl:'/products?category='+c.slug}));return <section data-section-name="banners" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Explore"/><div className="page-grid-sp-1 page-grid-st-3 page-grid-3 mt30">{src.slice(0,6).map((x:any,i:number)=><Link className="banner__block-item" href={x.linkUrl||'/products'} key={i}><div className="image-hover-box__container">{x.imageUrl&&<img className="image-hover-box" src={x.imageUrl} alt={x.title||''}/>}</div><div className="banner__block-item__content"><div className="banner__block-item__description"><h3 className="h3">{x.title||'Collection'}</h3>{x.subtitle&&<p>{x.subtitle}</p>}</div></div></Link>)}</div></div></section>}
function Ticker({s,data}:{s:any;data:any}){const items=Array.isArray(s.items)&&s.items.length?s.items:take(data.categories,8).map((x:any)=>({text:x.name}));return <section data-section-name="ticker-text" className="top-spacing-small"><div className="ticker-section__container"><div className="ticker-text"><div className="ticker"><div className="ticker__container ticker__container--js ticker-text__container">{[...items,...items].map((x:any,i:number)=><div className="ticker-text__text" key={i}><p className="mt0 h2">{x.text||x.title}</p></div>)}</div></div></div></div></section>}
function FeaturedProduct({s,data}:{s:any;data:any}){const p=data.featured?.[0];if(!p)return null;const v=p.variants?.[0];const img=s.imageUrl||p.images?.[0]?.url;return <section data-section-name="featured-product" className="top-spacing-small"><div className="page-width"><div className="page-grid-2 page-grid-sp-1 align-items-center">{img&&<Link href={'/products/'+p.slug} className="image-hover-box__container"><img className="image-hover-box" src={mediaUrl(img,'detail','webp')} alt={p.title}/></Link>}<div className="featured-product__content"><div className="body3 text-uppercase">{p.brand?.name}</div><h2 className="h2 mt10">{s.title||p.title}</h2><div className="price h4 mt15">{money(v?.price,p.displayCurrency||data.store?.currency)}</div><p className="body2 mt20">{p.shortDescription||p.description}</p><Link className="btn mt20" href={'/products/'+p.slug}>View product</Link></div></div></div></section>}
function Brands({s,data}:{s:any;data:any}){const brands=Array.from(new Map(take(data.featured,24).filter((p:any)=>p.brand).map((p:any)=>[p.brand.id||p.brand.slug,p.brand])).values()) as any[];return <section data-section-name="brands-grid" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Brands"/><div className="page-grid-sp-2 page-grid-st-4 page-grid-6 mt30">{brands.map((b:any)=><Link className="brands-grid__item text-center" href={'/products?brand='+encodeURIComponent(b.slug||b.name)} key={b.id||b.slug}><span className="h5">{b.name}</span></Link>)}</div></div></section>}
function Gallery({s,data}:{s:any;data:any}){const items=take(data.featured,8).filter((p:any)=>p.images?.[0]);return <section data-section-name="gallery" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Gallery"/><div className="section-gallery page-grid-sp-2 page-grid-st-4 page-grid-4 mt30">{items.map((p:any)=><Link className="section-gallery__item wokiee-masonry__item image-hover-box" href={'/products/'+p.slug} key={p.id}><div className="image-hover-box__container"><img className="image-hover-box" src={mediaUrl(p.images[0].url,'card','webp')} alt={p.title}/></div></Link>)}</div></div></section>}
function BlogPosts({s,data}:{s:any;data:any}){const posts=take(data.blogPosts||data.posts,3);if(!posts.length)return null;return <section data-section-name="blog-posts" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Blog"/><div className="page-grid-sp-1 page-grid-st-3 page-grid-3 page-vertical-gap-40 mt30">{posts.map((p:any)=><article className="blog-posts__item" key={p.id}><Link href={'/blog/'+p.slug} className="image-hover-box__container">{p.featuredImageUrl&&<img className="image-hover-box" src={p.featuredImageUrl} alt={p.title}/>}</Link><div className="mt15"><div className="body3">{p.publishedAt?new Date(p.publishedAt).toLocaleDateString(getLocale()):''}</div><h3 className="h5 blog-posts__heading mt8"><Link href={'/blog/'+p.slug}>{p.title}</Link></h3><p className="body3">{p.excerpt}</p></div></article>)}</div><div className="mt40 text-center"><Link className="btn btn--border" href="/blog">Get Inspired on Our Blog</Link></div></div></section>}

function Reviews({s,data}:{s:any;data:any}){const source=Array.isArray(s.items)&&s.items.length?s.items:take(data.reviews,6).map((r:any)=>({title:r.title,content:r.body,author:r.authorName,rating:r.rating}));if(!source.length)return null;return <section data-section-name="wokiee-review" className="top-spacing-small"><div className="page-width"><SectionHead s={s} title="Customer Reviews"/><div className="page-grid-sp-1 page-grid-st-2 page-grid-3 page-vertical-gap-40 mt30">{source.map((r:any,i:number)=><article className="review__item" key={i}><div className="review-stars">{'★'.repeat(Math.max(0,Math.min(5,Number(r.rating||5))))}</div>{r.title&&<h3 className="h5">{r.title}</h3>}<p className="body2">{r.content}</p>{r.author&&<div className="body3"><b>{r.author}</b>{r.role&&<span> · {r.role}</span>}</div>}</article>)}</div></div></section>}
