'use client';
import Link from 'next/link';
import {resolveTicartiSkin} from '../config/skin-registry';

const lingerieStoreLinks=[['NEW!','/products?category=lingerie'],['Bras','/products?category=bras'],['Panties','/products?category=panties'],['Sleep','/products?category=sleep'],['Lingerie','/products?category=lingerie'],['Apparel','/products?category=apparel'],['Swim','/products?category=swim'],['SALE','/products?category=sale']];
const infoLinks=[['About','/pages/about'],['Our Blog','/blog'],['Shipping & Returns','/pages/shipping-returns'],['Payment','/pages/payment'],['Warranty','/pages/warranty'],['Location','/pages/location'],['Contacts','/pages/contacts-us']];
const socialLinks=[['Facebook','#'],['Instagram','#'],['Pinterest','#']];
function LinkColumn({title,items}:{title:string;items:string[][]}){return <div className="footer__block-item"><div className="footer__block-heading link-list__block-heading"><h2 className="h5 mt0 mb0">{title}</h2></div><div className="footer__accordion__content link-list__block-item"><ul className="unstyle-ul">{items.map(([label,href])=><li key={label}><Link className="font-inherit footer-link__item link link-hover-span link__base-to_accent-color link--medium" href={href}><span>{label}</span></Link></li>)}</ul></div></div>}
export default function Footer({boot}:{boot:any}){
  const store=boot?.store||{};const design=boot?.design||{};const footer=design.footer||{};const skin=resolveTicartiSkin(design);const isLingerie=skin.slug==='lingerie-store';
  const categories=(Array.isArray(boot?.categories)?boot.categories:[]).slice(0,8).map((c:any)=>[String(c.name||c.title||'Collection'),'/products?category='+encodeURIComponent(String(c.slug||c.id||''))]);
  const menus=Array.isArray(boot?.menus)?boot.menus:[];const footerMenu=menus.find((m:any)=>String(m.handle||'').toLowerCase()==='footer-main');const footerMenuLinks=Array.isArray(footerMenu?.items)?footerMenu.items.map((x:any)=>[String(x.label||x.title||'Link'),String(x.url||x.href||'/')]):[];
  const storeLinks=footerMenuLinks.length?footerMenuLinks:(isLingerie?lingerieStoreLinks:(categories.length?categories:[['Shop','/products'],['New','/products?sort=newest'],['Blog','/blog']]));
  const newsletterTitle=isLingerie?'Exclusive Offers & Style Inspiration':String(footer.newsletterTitle||'Stay in the loop');
  const newsletterSub=isLingerie?'Newsletter Signup':String(footer.newsletterSubtitle||'Newsletter');
  const template=Number(footer.template||1);const footerClass=`footer-template-${template}`;
  const footerId=isLingerie?'theme-section-sections--15772574416978__footer':'theme-section-footer';const newsletterId=isLingerie?'theme-section-sections--15772574416978__newsletter_signup_nqURNF':'theme-section-newsletter';
  return <>
  {footer.newsletterEnabled!==false&&<section id={newsletterId} className="top-spacing-normal section-background section-background--medium" data-section-name="newsletter-signup" style={{'--color-section-background':footer.newsletterBackground||undefined} as any}><div className="page-width"><div className="section-header__container text-left"><div className="section-header__item"><div className="body3 text-uppercase">{newsletterSub}</div><h2 className="h2 mt8 mb0">{newsletterTitle}</h2></div></div><form className="newsletter-form mt20" onSubmit={e=>e.preventDefault()}><div className="field field-with-icon"><input className="field__input" placeholder="Email" aria-label="Email" type="email"/><button className="field__icon" aria-label="Subscribe">→</button></div></form><div className="rte body3 mt15"><p>By clicking the button you agree to the <Link href="/pages/privacy">Privacy Policy</Link> and <Link href="/pages/terms">Terms and Conditions</Link>.</p></div></div></section>}
  <footer id={footerId} className={`footer ${footerClass} top-spacing-none section-background section-background--medium`} data-section-name="wokiee-footer" data-theme-skin={skin.slug} style={{'--color-section-background':footer.backgroundColor||undefined} as any}><div className="page-width"><div className="footer-blocks__content"><div className="page-grid-sp-1 page-grid-st-2 page-grid-md-2 page-grid-4 footer__block__items page-vertical-gap-40 footer__accordion"><LinkColumn title={isLingerie?'Store':'Collections'} items={storeLinks}/><LinkColumn title="Information" items={infoLinks}/><LinkColumn title="Social" items={socialLinks}/><div className="footer__block-item"><div className="footer__block-heading"><h2 className="h5 mt0 mb0">Contacts</h2></div><div className="footer__accordion__content"><div className="rte body3 mt10"><h4>{String(store.phone||'T: 555-555-1000')}</h4></div><div className="rte body3 mt10"><p>{String(store.address||'Open daily from 9:00 AM – 7:00 PM')}</p></div></div></div></div></div></div><div className="page-width"><div className="footer__content-bottom footer__content-bottom--space-between"><div className="footer__content-bottom--left"><div className="footer__copyright body3"><span className="copyright__content">{String(footer.copyright||'© {{year}} {{store_name}}. Tüm hakları saklıdır.').replace(/\{\{year\}\}/g,String(new Date().getFullYear())).replace(/\{\{store_name\}\}/g,String(store.name||'Ticarti'))}</span></div></div><div className="footer__content-bottom--right"><div className="footer__payment"><ul className="unstyle-ul list-payment" role="list"><li className="list-payment__item">VISA</li><li className="list-payment__item">MC</li><li className="list-payment__item">AMEX</li></ul></div></div></div></div></footer>
</>}
