'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,getCartToken,getCurrency,setCurrency,getLocale,setLocale,STORE,mediaUrl,money} from '../../../lib/api';
import headerPreset from '../config/header-preset.json';
import {resolveTicartiSkin} from '../config/skin-registry';

type MenuNode={id?:string;label:string;href:string;children:MenuNode[]};
function Icon({name}:{name:'search'|'user'|'heart'|'compare'|'cart'|'menu'|'close'|'chevron'|'trash'}){const paths:any={search:<><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></>,user:<><circle cx="12" cy="8" r="3.5"/><path d="M4.5 20c.7-4.1 3.3-6.2 7.5-6.2s6.8 2.1 7.5 6.2"/></>,heart:<path d="M12 20.5 4.8 13.7C.7 9.8 2.8 4 7.5 4c2 0 3.4 1 4.5 2.4C13.1 5 14.5 4 16.5 4c4.7 0 6.8 5.8 2.7 9.7L12 20.5Z"/>,compare:<><path d="M7 4v16M17 4v16"/><path d="m3.5 7 3.5-3 3.5 3M13.5 17l3.5 3 3.5-3"/></>,cart:<><path d="M3 4h2l2.2 10.2h9.7L20 7H6.2"/><circle cx="9" cy="19" r="1.2"/><circle cx="17" cy="19" r="1.2"/></>,menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>,close:<><path d="m6 6 12 12M18 6 6 18"/></>,chevron:<path d="m9 6 6 6-6 6"/>,trash:<><path d="M5 7h14M9 7V4h6v3M7 7l1 13h8l1-13"/></>};return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
function menuTree(raw:any[],categories:any[],lingerie=false):MenuNode[]{const lingerieFallback=[{label:'NEW!',href:'/products?category=lingerie',children:[]},{label:'Bras',href:'/products?category=bras',children:[{label:'Collections',href:'/products?category=bras',children:[{label:'Midnight Lace',href:'/products?category=sleep',children:[]},{label:'Velvet Dreams',href:'/products?category=activewear',children:[]},{label:'Eternal Romance',href:'/products?category=beauty',children:[]},{label:'Whisper Touch',href:'/products?category=apparel',children:[]},{label:'Pure Desire',href:'/products?category=swim',children:[]},{label:'Secret Allure',href:'/products?category=sale',children:[]}]},{label:'Styles',href:'/products?category=bras',children:[{label:'T-shirt Bra',href:'/products?category=bras',children:[]},{label:'Push-Up Bra',href:'/products?category=bras',children:[]},{label:'Balconette Bra',href:'/products?category=bras',children:[]},{label:'Plunge Bra',href:'/products?category=bras',children:[]},{label:'Bralette',href:'/products?category=bras',children:[]}]}]},{label:'Panties',href:'/products?category=panties',children:[]},{label:'Sleep',href:'/products?category=sleep',children:[]},{label:'Lingerie',href:'/products?category=lingerie',children:[]},{label:'Apparel',href:'/products?category=apparel',children:[]},{label:'Swim',href:'/products?category=swim',children:[]},{label:'SALE',href:'/products?category=sale',children:[]}];const genericFallback=(categories||[]).slice(0,8).map((c:any)=>({label:String(c.name||c.title||'Collection'),href:'/products?category='+encodeURIComponent(String(c.slug||c.id||'')),children:[]}));const fallback=lingerie?lingerieFallback:(genericFallback.length?genericFallback:[{label:'Shop',href:'/products',children:[]},{label:'New',href:'/products?sort=newest',children:[]},{label:'Blog',href:'/blog',children:[]}]);if(!raw.length)return fallback;const normalize=(x:any):MenuNode=>({id:String(x.id||''),label:x.label||x.title||x.name||'Menu',href:x.href||x.url||x.path||'/',children:Array.isArray(x.children)?x.children.map(normalize):[]});const rows=raw.map(normalize);if(rows.some((x:any)=>x.children.length))return rows;const byId=new Map(rows.map(x=>[x.id,x]));const roots:MenuNode[]=[];raw.forEach((source:any,i:number)=>{const item=rows[i];const parent=byId.get(String(source.parentId||source.parentItemId||''));if(parent)parent.children.push(item);else roots.push(item)});return roots.length?roots:fallback}

export default function Header({boot}:{boot:any}){
  const router=useRouter();const[count,setCount]=useState(0);const[currency,setCur]=useState(getCurrency());const[locale,setLoc]=useState(getLocale());const[searchOpen,setSearchOpen]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);const[cartOpen,setCartOpen]=useState(false);const[q,setQ]=useState('');const[results,setResults]=useState<any[]>([]);const[searchBusy,setSearchBusy]=useState(false);const[cart,setCart]=useState<any>(null);const[cartBusy,setCartBusy]=useState(false);
  const store=boot?.store||{};const currencies=store.currencies||[];const locales=store.locales||[];const header=boot?.design?.header||{};const categories=Array.isArray(boot?.categories)?boot.categories:[];const skin=resolveTicartiSkin(boot?.design);const isLingerie=skin.slug==='lingerie-store';
  const hp:any=headerPreset;const headerId=(hp.order||[]).find((id:string)=>hp.sections?.[id]?.type==='header');const sourceHeader=headerId?hp.sections?.[headerId]:null;const hs:any=sourceHeader?.settings||{};
  const menuItems=useMemo(()=>{const menus=Array.isArray(boot?.menus)?boot.menus:[];const requested=String(header.menuHandle||header.menu||hs.menu||'header-main').toLowerCase();const menu=menus.find((m:any)=>String(m.handle||'').toLowerCase()===requested)||menus.find((m:any)=>['header-main','header','main','primary','main-menu'].includes(String(m.handle||'').toLowerCase()))||menus[0];return menuTree(Array.isArray(menu?.items)?menu.items:[],categories,isLingerie)},[boot?.menus,categories,header.menuHandle,header.menu,hs.menu,isLingerie]);
  async function sync(){const t=getCartToken();if(!t){setCount(0);setCart(null);return}try{const c=await api('/storefront/carts/'+t);setCart(c);setCount(c.items?.reduce((a:number,x:any)=>a+x.quantity,0)||0);if(c.currency){setCur(c.currency);if(c.currency!==getCurrency())setCurrency(c.currency)}}catch{setCount(0);setCart(null)}}
  useEffect(()=>{setCur(getCurrency());setLoc(getLocale());void sync();const onCart=()=>void sync();window.addEventListener('cart-change',onCart);return()=>window.removeEventListener('cart-change',onCart)},[]);
  useEffect(()=>{if(!searchOpen||q.trim().length<2){setResults([]);setSearchBusy(false);return}setSearchBusy(true);const timer=window.setTimeout(()=>{api(`/storefront/${STORE}/products?q=${encodeURIComponent(q.trim())}&limit=6&currency=${encodeURIComponent(currency)}&locale=${encodeURIComponent(locale)}`).then(x=>setResults(x.items||[])).catch(()=>setResults([])).finally(()=>setSearchBusy(false))},220);return()=>window.clearTimeout(timer)},[q,searchOpen,currency,locale]);
  function changeLocale(code:string){setLoc(code);setLocale(code)}async function changeCurrency(code:string){setCur(code);setCurrency(code);const t=getCartToken();if(t){try{await api('/storefront/carts/'+t+'/currency',{method:'PATCH',body:JSON.stringify({currency:code})});window.dispatchEvent(new Event('cart-change'))}catch{}}}
  function submitSearch(e:React.FormEvent){e.preventDefault();const term=q.trim();setSearchOpen(false);router.push(term?'/products?q='+encodeURIComponent(term):'/products')}
  async function updateCart(itemId:string,quantity:number){const token=getCartToken();if(!token||cartBusy)return;setCartBusy(true);try{const next=await api(`/storefront/carts/${token}/items/${itemId}`,{method:'PATCH',body:JSON.stringify({quantity})});setCart(next);setCount(next.items?.reduce((a:number,x:any)=>a+x.quantity,0)||0);window.dispatchEvent(new Event('cart-change'))}finally{setCartBusy(false)}}
  async function openCart(){setCartOpen(true);await sync()}
  const sourceSticky=String(header.enable__sticky_header||'').toLowerCase();const effectiveSticky=header.sticky!==undefined?header.sticky:!['disable','disabled','none','false'].includes(sourceSticky);const template=Number(header.template||1);const layoutClass=template===2?'header-layout-center':template===3?'header-layout-wide':template===4?'header-layout-compact':template===5?'header-layout-split':template===6?'header-layout-minimal':'header-layout-classic';const promoText=String(header.topbarText|| (isLingerie?'FREE Shipping on All US Orders Over $149':''));const promoId=isLingerie?'theme-section-sections--15772574613586__promo_header_pwwYTU':'theme-section-promo-header';const headerDomId=isLingerie?'theme-section-sections--15772574613586__header_9GztDw':'theme-section-header';
  const sourceLogo=typeof header.logo==='string'?header.logo:(header.logo?.url||'');const logoUrl=String(header.logoUrl||sourceLogo||store.logoUrl||'');const logoWidth=Number(header.logoWidth||header.logo_max_width||hs.logo_max_width||130);
  const logo=<Link className="header__heading-link header__logo-link clear-underline" href="/" aria-label={store.name||'Home'} style={{maxWidth:logoWidth}}>{logoUrl?<img className="header__heading-logo" src={logoUrl} alt={store.name||'Logo'} decoding="async" fetchPriority="high"/>:<span className="h4">{store.name||'Store'}</span>}</Link>;
  const menu=<nav className="desktop-main-menu list-menu--classic" aria-label="Menu"><ul className="list-menu list-menu--inline unstyle-ul">{menuItems.map((x,i)=><li className="list-menu__item" key={x.id||i}><Link className="header__menu-item link animation-underline" href={x.href}>{x.label}{x.children.length>0&&<span aria-hidden="true">⌄</span>}</Link>{x.children.length>0&&<div className="header__submenu list-menu__submenu"><div className="page-width"><div className="page-grid-4">{x.children.map((child,j)=><div key={child.id||j}><Link className="h5 clear-underline" href={child.href}>{child.label}</Link>{child.children.length>0&&<ul className="unstyle-ul mt10">{child.children.map((leaf,k)=><li key={leaf.id||k}><Link className="link link__base-to_accent-color" href={leaf.href}>{leaf.label}</Link></li>)}</ul>}</div>)}</div></div></div>}</li>)}</ul></nav>;
  const tools=<div className="header__icons header__user-icons display-flex align-items-center">{header.showSearch!==false&&<button className="header__icon header__icon--search" type="button" aria-label="Search" onClick={()=>setSearchOpen(true)}><Icon name="search"/></button>}{header.showAccount!==false&&<Link className="header__icon header__icon--account" href="/account" aria-label="Account"><Icon name="user"/></Link>}{header.showWishlist!==false&&<Link className="header__icon header__icon--wishlist" href="/account?tab=wishlist" aria-label="Wishlist"><Icon name="heart"/></Link>}{header.showCart!==false&&<button className="header__icon header__icon--cart" type="button" onClick={()=>void openCart()} aria-label={`Cart, ${count} items`}><Icon name="cart"/>{count>0&&<span className="cart-count-bubble">{count}</span>}</button>}<button className="header__icon header__icon--menu hide-desktop" type="button" onClick={()=>setMobileOpen(true)} aria-label="Menu"><Icon name="menu"/></button></div>;
  return <>
    {(header.topbarEnabled!==false&&promoText)&&<section id={promoId} className="promo-header__container top-spacing-none section-background" data-section-name="promo-header"><div className="page-width text-center body3">{header.topbarLink?<Link href={header.topbarLink}>{promoText}</Link>:promoText}</div></section>}
    <header id={headerDomId} data-section-name={layoutClass} className={`section-header ${layoutClass}`} data-theme-skin={skin.slug} style={{marginTop:Number(hs.header_top_spacing_normal||0),'--color-section-background':header.backgroundColor|| (hs.color_background&&hs.color_background!=='rgba(0,0,0,0)'?hs.color_background:undefined)} as any}>
      <div className="header__mobile section-background"><div className="page-width header-mobile__container display-flex align-items-center"><button className="header__icon" type="button" onClick={()=>setMobileOpen(true)} aria-label="Menu"><Icon name="menu"/></button>{logo}<div className="header-mobile__icons">{tools}</div></div></div>
      <div className={`header__desktop header__desktop__shadow ${(header.sticky===false||hs.enable__sticky_header==='none')?'':'sticky-header'}`}>
        {header.topbarEnabled&&<div className="header__topbar section-background"><div className="page-width text-center body3">{header.topbarLink?<Link href={header.topbarLink}>{header.topbarText||''}</Link>:<span>{header.topbarText||''}</span>}</div></div>}
        <div className={`header__main ${layoutClass} section-background`}><div className="page-width"><div className={`header logo-to-left ${header.menuAlign==='left'?'top-menu-to-left':header.menuAlign==='right'?'top-menu-to-right':'top-menu-to-center'}`}>{logo}{menu}{tools}</div></div></div>
      </div>
    </header>
    {searchOpen&&<div className="popup-modal predictive-search-modal" role="dialog" aria-modal="true" aria-label="Search"><div className="popup-modal__overlay" onClick={()=>setSearchOpen(false)}/><div className="popup-modal__content"><button className="popup-modal__close" type="button" aria-label="Close" onClick={()=>setSearchOpen(false)}><Icon name="close"/></button><form className="predictive-search__form" onSubmit={submitSearch}><div className="field field-with-icon"><input className="field__input" autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Find What You’re Looking for"/><button className="field__icon" aria-label="Search"><Icon name="search"/></button></div></form><div className="predictive-search__results">{searchBusy&&<p>Searching…</p>}{results.map((p:any)=><Link className="predictive-search__item" onClick={()=>setSearchOpen(false)} href={'/products/'+p.slug} key={p.id}>{p.images?.[0]?.url&&<img src={mediaUrl(p.images[0].url,'thumb','webp')} alt=""/>}<span><b>{p.title}</b><small>{money(p.variants?.[0]?.price,p.displayCurrency||currency)}</small></span></Link>)}</div></div></div>}
    {mobileOpen&&<div className="popup-modal popup-modal__left mobile-menu-modal" role="dialog" aria-modal="true"><div className="popup-modal__overlay" onClick={()=>setMobileOpen(false)}/><div className="popup-modal__content popup-modal__content__f-height"><div className="popup-modal__content__header"><b>Menu</b><button onClick={()=>setMobileOpen(false)} aria-label="Close"><Icon name="close"/></button></div><div className="popup-modal__content__data custom__scrollbar"><ul className="unstyle-ul mobile-menu__list">{menuItems.map((x,i)=><li key={x.id||i}><Link onClick={()=>setMobileOpen(false)} href={x.href}>{x.label}</Link>{x.children.length>0&&<ul className="unstyle-ul">{x.children.map((c,j)=><li key={c.id||j}><Link onClick={()=>setMobileOpen(false)} href={c.href}>{c.label}</Link></li>)}</ul>}</li>)}</ul><div className="mobile-menu__selectors">{locales.length>1&&<select aria-label="Language" value={locale} onChange={e=>changeLocale(e.target.value)}>{locales.map((l:any)=><option key={l.locale} value={l.locale}>{l.label}</option>)}</select>}{currencies.length>1&&<select aria-label="Currency" value={currency} onChange={e=>void changeCurrency(e.target.value)}>{currencies.map((c:any)=><option key={c.code} value={c.code}>{c.code}</option>)}</select>}</div></div></div></div>}
    {cartOpen&&<div className="popup-modal popup-modal__right cart-drawer-modal" role="dialog" aria-modal="true"><div className="popup-modal__overlay" onClick={()=>setCartOpen(false)}/><div className="popup-modal__content popup-modal__content__f-height"><div className="popup-modal__content__header"><h2 className="h4">Cart</h2><button onClick={()=>setCartOpen(false)} aria-label="Close"><Icon name="close"/></button></div><div className="popup-modal__content__data custom__scrollbar">{cart?.items?.length?cart.items.map((i:any)=><div className="cart-item" key={i.id}><div className="cart-item__media">{i.variant?.product?.images?.[0]?.url&&<img src={i.variant.product.images[0].url} alt=""/>}</div><div className="cart-item__details"><Link href={`/products/${i.variant.product.slug}`} onClick={()=>setCartOpen(false)}>{i.variant.product.title}</Link><small>{i.variant.title}</small><div className="quantity field"><button className="quantity__button" disabled={cartBusy||i.quantity<=1} onClick={()=>void updateCart(i.id,i.quantity-1)}>−</button><span className="quantity__input">{i.quantity}</span><button className="quantity__button" disabled={cartBusy} onClick={()=>void updateCart(i.id,i.quantity+1)}>+</button></div></div><div className="cart-item__totals">{money(Number(i.variant.price)*i.quantity,cart.currency||currency)}<button aria-label="Remove" disabled={cartBusy} onClick={()=>void updateCart(i.id,0)}><Icon name="trash"/></button></div></div>):<div className="cart__warnings text-center"><p className="h4">Your Cart is Empty</p></div>}</div><div className="cart-drawer__footer"><Link className="btn btn-card-width" href="/cart" onClick={()=>setCartOpen(false)}>View Cart</Link></div></div></div>}
  </>;
}
