'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import ProductCard from '../../components/ProductCard';
import {api,STORE,getCurrency,getLocale} from '../../lib/api';

function ProductList(){
  const sp=useSearchParams();const[d,setD]=useState<any>(null);const[view,setView]=useState<'grid'|'list'>('grid');const[sort,setSort]=useState('featured');const[brand,setBrand]=useState('');const[filtersOpen,setFiltersOpen]=useState(false);const q=sp.get('q')||'';const category=sp.get('category')||'';
  async function load(){api(`/storefront/${STORE}/products?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`).then(setD)}
  useEffect(()=>{void load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[q,category]);
  const items=useMemo(()=>{let rows=[...(d?.items||[])];if(brand)rows=rows.filter((x:any)=>String(x.brand?.slug||x.brand?.name||'')===brand);if(sort==='price-asc')rows.sort((a:any,b:any)=>Number(a.variants?.[0]?.price||0)-Number(b.variants?.[0]?.price||0));if(sort==='price-desc')rows.sort((a:any,b:any)=>Number(b.variants?.[0]?.price||0)-Number(a.variants?.[0]?.price||0));if(sort==='name')rows.sort((a:any,b:any)=>String(a.title).localeCompare(String(b.title)));return rows},[d,brand,sort]);
  const brands=useMemo(()=>Array.from(new Map((d?.items||[]).filter((x:any)=>x.brand).map((x:any)=>[String(x.brand.slug||x.brand.name),x.brand])).entries()),[d]);
  return <main id="theme-section-ticarti-collection" data-section-name="main-collection-product-grid"><div className="page-width"><div className="breadcrumbs body3 mt20"><a href="/">Anasayfa</a><span> / </span><span>{category||q||'Ürünler'}</span></div><div className="collection-title top-spacing-small"><span className="body3 text-uppercase">{category?'Koleksiyon':'Katalog'}</span><h1 className="h1 mt8">{category?category:q?`“${q}” araması`:'Tüm Ürünler'}</h1></div><div className="facets-toolbar mb40 toolbar__design_1"><button className="mobile-facets__button body2 strong" onClick={()=>setFiltersOpen(true)}>Filtreler</button><div className="products_count body3">{d?.pagination?.total??items.length} ürün</div><div className="grid-selector"><button className={`collection-grid__item ${view==='grid'?'active-d':''}`} onClick={()=>setView('grid')} aria-label="Grid görünüm">▦</button><button className={`collection-grid__item ${view==='list'?'active-d':''}`} onClick={()=>setView('list')} aria-label="Liste görünüm">☷</button></div><div className="sorting"><div className="select field"><select className="select__select field__input" aria-label="Sıralama" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Önerilen</option><option value="name">İsme göre</option><option value="price-asc">Fiyat: düşükten yükseğe</option><option value="price-desc">Fiyat: yüksekten düşüğe</option></select></div></div></div><div className="page-grid__collection-sidebar"><aside className={`facets facets__vertical ${filtersOpen?'is-open':''}`}><button className="hide-desktop facets__close" onClick={()=>setFiltersOpen(false)}>×</button><div className="facets__disclosure"><div className="facets__summary h5">Marka</div><div className="facets__display"><label className="facet-checkbox"><input type="radio" checked={!brand} onChange={()=>setBrand('')}/><span>Tümü</span></label>{brands.map(([key,b]:any)=><label className="facet-checkbox" key={key}><input type="radio" checked={brand===key} onChange={()=>setBrand(key)}/><span>{b.name}</span></label>)}</div></div></aside><div id="ProductGridContainer" className="product-grid__container"><div className={`collection__container ${view==='list'?'page-grid-1':'page-grid-4 page-grid-st-3 page-grid-sp-2'}`}>{items.map((p:any)=><ProductCard key={p.id} p={p} currency={d?.currency}/>)}</div>{!items.length&&<div className="collection collection--empty text-center top-spacing-small"><h2 className="h3">Ürün bulunamadı</h2></div>}</div></div></div>{filtersOpen&&<button className="popup-modal__overlay hide-desktop" onClick={()=>setFiltersOpen(false)} aria-label="Filtreleri kapat"/>}</main>
}
export default function Products(){return <Suspense fallback={<main className="page-width top-spacing-small">Ürünler yükleniyor…</main>}><ProductList/></Suspense>}
