'use client';
import Link from 'next/link';
import footerPreset from '../config/footer-preset.json';

function cleanHtml(v:any){return String(v||'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/\son\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/javascript\s*:/gi,'')}
function menuFor(boot:any,handle:any){const menus=Array.isArray(boot?.menus)?boot.menus:[];return menus.find((m:any)=>String(m.handle||'').toLowerCase()===String(handle||'').toLowerCase())||menus.find((m:any)=>['footer','main-menu','main'].includes(String(m.handle||'').toLowerCase()))||menus[0]}
function sectionStyle(s:any){const style:any={};if(s?.background==='color'&&s?.color_background&&String(s.color_background).replace(/\s/g,'')!=='rgba(0,0,0,0)')style['--color-section-background']=s.color_background;if(s?.color_base&&String(s.color_base).replace(/\s/g,'')!=='rgba(0,0,0,0)')style['--color-base-block']=s.color_base;if(s?.color_accent&&String(s.color_accent).replace(/\s/g,'')!=='rgba(0,0,0,0)')style['--color-accent-block']=s.color_accent;if(s?.color_lines&&String(s.color_lines).replace(/\s/g,'')!=='rgba(0,0,0,0)')style['--color-lines']=s.color_lines;return style}
function SectionHeading({s}:{s:any}){if(!s?.main_heading&&!s?.main_subheading&&!s?.main_desc)return null;return <div className={`section-header__container ${s.heading_aligment||'text-center'}`}><div className="section-header__item">{s.main_subheading&&<div className="body3 text-uppercase">{s.main_subheading}</div>}{s.main_heading&&<h2 className="h2 mt8 mb0">{s.main_heading}</h2>}{s.main_desc&&<div className="body2 mt10" dangerouslySetInnerHTML={{__html:cleanHtml(s.main_desc)}}/>}</div></div>}

export default function Footer({boot}:{boot:any}){
  const group:any=footerPreset;const sections=group.sections||{};const order=group.order||[];const footerId=order.find((id:string)=>sections[id]?.type==='footer');const footer=footerId?sections[footerId]:null;const fs=footer?.settings||{};const store=boot?.store||{};
  const blocks=footer?((footer.block_order||Object.keys(footer.blocks||{})).map((id:string)=>({id,...(footer.blocks?.[id]||{})}))):[];
  const copyright=`© ${new Date().getFullYear()} ${String(store.name||'Ticarti')}. All Rights Reserved`;
  return <>
    {order.filter((id:string)=>id!==footerId).map((id:string)=>{const sec=sections[id];if(!sec||sec.disabled)return null;const s=sec.settings||{};const bs=(sec.block_order||Object.keys(sec.blocks||{})).map((bid:string)=>({id:bid,...(sec.blocks?.[bid]||{})}));if(sec.type==='text-columns-with-icons-type-2')return <section id={`theme-section-${id}`} className={`section-background top-spacing-${s.top_spacing||'small'}`} style={sectionStyle(s)} key={id}><div className={s.width==='fullwidth'?'page-fullwidth':'page-width'}><SectionHeading s={s}/><div className={`${s.grid_tablet||'page-grid-st-3'} ${s.grid||'page-grid-3'} page-grid-sp-1 mt30`}>{bs.map((b:any)=><div className="text-columns-with-icons__item text-center" key={b.id}><div className="dynamic-block__icon">{b.settings?.icon_name||'◌'}</div><h3 className={s.heading_size||'h5'}>{b.settings?.heading_text||''}</h3>{b.settings?.desc&&<div className="rte body2" dangerouslySetInnerHTML={{__html:cleanHtml(b.settings.desc)}}/>}</div>)}</div></div></section>;
    if(sec.type==='newsletter-signup')return <section id={`theme-section-${id}`} className={`section-background top-spacing-${s.top_spacing||'small'}`} style={sectionStyle(s)} key={id}><div className={s.width==='fullwidth'?'page-fullwidth':'page-width'}><SectionHeading s={s}/>{s.show_newsletter&&<form className="newsletter-form mt20" onSubmit={e=>e.preventDefault()}><div className="field field-with-icon"><input className="field__input" type="email" placeholder="Email address" aria-label="Email"/><button className="field__icon" aria-label="Subscribe">→</button></div></form>}</div></section>;
    return null})}
    {footer&&<footer id={`theme-section-${footerId}`} className={`footer section-background top-spacing-${fs.top_spacing||'none'}`} style={sectionStyle(fs)} data-section-name="footer"><div className={fs.width==='fullwidth'?'page-fullwidth':'page-width'}><div className="footer-blocks__content"><div className={`page-grid-sp-1 ${fs.grid_tablet||'page-grid-st-2'} ${fs.grid||'page-grid-4'} footer__block__items page-vertical-gap-40${fs.enable_accordion?' footer__accordion':''}`}>{blocks.map((b:any)=>{const s=b.settings||{};if(b.type==='link_list'){const m=menuFor(boot,s.menu);return <div id={`theme-block-${b.id}`} className="footer__block-item" key={b.id}><div className="footer__block-heading link-list__block-heading"><h2 className="h5 mt0 mb0">{s.heading_text||m?.title||m?.name||'Links'}</h2></div><div className="footer__accordion__content link-list__block-item"><ul className="unstyle-ul">{(m?.items||[]).map((x:any,i:number)=><li key={x.id||i}><Link className="font-inherit footer-link__item link link-hover-span link__base-to_accent-color link--medium" href={x.href||x.url||x.path||'/'}><span>{x.label||x.title||x.name}</span></Link></li>)}</ul></div></div>}
    if(b.type==='banner')return <div id={`theme-block-${b.id}`} className="footer__block-item" key={b.id}><Link href={s.url||'/products'} className="banner__block-item image-hover-box clear-underline"><div className="banner__block-item__content"><div className={`banner__block-item__description ${s.text_align||'text-center'}`}>{s.heading_after_description&&s.desc&&<div className="rte body2" dangerouslySetInnerHTML={{__html:cleanHtml(s.desc)}}/>}<h3 className="h4">{s.heading_text}</h3>{!s.heading_after_description&&s.desc&&<div className="rte body2" dangerouslySetInnerHTML={{__html:cleanHtml(s.desc)}}/>}</div></div></Link></div>;
    if(b.type==='media_with_text')return <div id={`theme-block-${b.id}`} className="footer__block-item" key={b.id}><div className="footer__block-heading"><h2 className="h5 mt0 mb0">{s.heading_text}</h2></div><div className="footer__accordion__content">{[1,2,3,4,5].map(n=>s[`description_${n}`]?<div className="rte body3 mt10" key={n} dangerouslySetInnerHTML={{__html:cleanHtml(s[`description_${n}`])}}/>:null)}</div></div>;
    if(b.type==='social')return <div id={`theme-block-${b.id}`} className="footer__block-item" key={b.id}><div className="footer__block-heading"><h2 className={s.heading_size||'h5'}>{s.heading_text}</h2></div><div className="footer__accordion__content footer-social__container">{s.show_newsletter&&<form className="newsletter-form" onSubmit={e=>e.preventDefault()}><div className="field field-with-icon"><input className="field__input" type="email" placeholder="Email address" aria-label="Email"/><button className="field__icon" aria-label="Subscribe">→</button></div></form>}{s.desc2&&<div className="rte body3 mt15" dangerouslySetInnerHTML={{__html:cleanHtml(s.desc2)}}/>}</div></div>;
    return null})}</div></div></div>{fs.show_lines_bottom!==false&&<div className="background__horizontal-line"/>}<div className={fs.width==='fullwidth'?'page-fullwidth':'page-width'}><div className={`footer__content-bottom footer__content-bottom--${fs.copyright_aligment||'space-between'}`}><div className="footer__content-bottom--left"><div className="footer__copyright body3"><span className="copyright__content">{copyright}</span></div></div>{fs.payment_enable!==false&&<div className="footer__content-bottom--right"><div className="footer__payment"><ul className="unstyle-ul list-payment" role="list"><li className="list-payment__item">VISA</li><li className="list-payment__item">MC</li><li className="list-payment__item">AMEX</li></ul></div></div>}</div></div></footer>}
  </>;
}
