'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {api,STORE,money,getLocale} from '../../lib/api';

type Tab='overview'|'orders'|'addresses'|'wishlist'|'returns'|'reviews'|'questions'|'privacy';
type Geo={id:string;name:string};

export default function Account(){
  const searchParams=useSearchParams();const mode=searchParams.get('mode')||'both';const requestedReturn=searchParams.get('return')||'';const returnTo=requestedReturn.startsWith('/')&&!requestedReturn.startsWith('//')?requestedReturn:'';
  const[token,setToken]=useState('');const[tab,setTab]=useState<Tab>('overview');const[me,setMe]=useState<any>(null);const[orders,setOrders]=useState<any[]>([]);const[wishlist,setWishlist]=useState<any[]>([]);const[returns,setReturns]=useState<any[]>([]);const[reviews,setReviews]=useState<any[]>([]);const[questions,setQuestions]=useState<any[]>([]);const[privacyRows,setPrivacyRows]=useState<any[]>([]);const[consents,setConsents]=useState<any[]>([]);const[err,setErr]=useState('');const[msg,setMsg]=useState('');
  const[country,setCountry]=useState('TR');const[admin1,setAdmin1]=useState('');const[admin1Rows,setAdmin1Rows]=useState<Geo[]>([]);const[admin2,setAdmin2]=useState('');const[admin2Rows,setAdmin2Rows]=useState<Geo[]>([]);const[locality,setLocality]=useState('');const[localityRows,setLocalityRows]=useState<Geo[]>([]);const[neighborhoodRows,setNeighborhoodRows]=useState<Geo[]>([]);const[refs,setRefs]=useState<any>({countries:[]});
  useEffect(()=>{api('/storefront/reference-data').then(setRefs).catch(()=>{});void restore()},[]);
  async function restore(){try{const j=await api('/storefront/customer/refresh',{method:'POST',credentials:'include',body:'{}'});if(j.accessToken){setToken(j.accessToken);await load(j.accessToken)}}catch{}}
  async function load(t:string){try{setErr('');const h={authorization:`Bearer ${t}`};const[m,o,w,r,rv,q,p,c]=await Promise.all([api('/storefront/customer/me',{headers:h}),api('/storefront/customer/orders',{headers:h}),api('/storefront/customer/wishlist',{headers:h}),api('/storefront/customer/returns',{headers:h}),api('/storefront/customer/reviews',{headers:h}),api('/storefront/customer/questions',{headers:h}),api('/storefront/customer/privacy-requests',{headers:h}),api('/storefront/customer/consents',{headers:h})]);setMe(m);setOrders(o);setWishlist(w);setReturns(r);setReviews(rv);setQuestions(q);setPrivacyRows(p);setConsents(c);const co=m.addresses?.[0]?.country||'TR';setCountry(co);await loadAdmin1(co)}catch(e:any){setErr(e.message)}}
  async function auth(path:string,options:any={}){return api(path,{...options,headers:{authorization:`Bearer ${token}`,...(options.headers||{})}})}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const j=await api(`/storefront/${STORE}/customers/login`,{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});setToken(j.accessToken);await load(j.accessToken);if(returnTo)window.location.href=returnTo}catch(e:any){setErr(e.message)}}
  async function register(e:FormEvent<HTMLFormElement>){e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));try{const j=await api(`/storefront/${STORE}/customers/register`,{method:'POST',body:JSON.stringify({...f,consents:{terms:!!f.terms,privacy:!!f.privacy,kvkkNotice:!!f.kvkkNotice,emailMarketing:!!f.emailMarketing},consentVersions:{terms:'1.0',privacy:'1.0',kvkkNotice:'1.0'}})});setToken(j.accessToken);await load(j.accessToken);if(returnTo)window.location.href=returnTo}catch(e:any){setErr(e.message)}}
  async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));try{await auth('/storefront/customer/me',{method:'PATCH',body:JSON.stringify(f)});setMsg('Profil güncellendi.');await load(token)}catch(e:any){setErr(e.message)}}
  async function privacy(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/storefront/${STORE}/privacy-requests`,{method:'POST',body:JSON.stringify({email:me?.email,type:f.get('type'),requestData:{note:f.get('note')}})});setMsg('KVKK/GDPR talebiniz kaydedildi.');await load(token)}catch(e:any){setErr(e.message)}}
  async function loadAdmin1(code:string){setAdmin1('');setAdmin2('');setLocality('');setAdmin2Rows([]);setLocalityRows([]);setNeighborhoodRows([]);try{setAdmin1Rows(await api(`/storefront/${STORE}/locations?countryCode=${encodeURIComponent(code)}&level=ADMIN1`))}catch{setAdmin1Rows([])}}
  async function changeCountry(code:string){setCountry(code);await loadAdmin1(code)}
  async function changeAdmin1(id:string){setAdmin1(id);setAdmin2('');setLocality('');setLocalityRows([]);setNeighborhoodRows([]);try{setAdmin2Rows(id?await api(`/storefront/${STORE}/locations?parentId=${encodeURIComponent(id)}&level=ADMIN2`):[])}catch{setAdmin2Rows([])}}
  async function changeAdmin2(id:string){setAdmin2(id);setLocality('');setNeighborhoodRows([]);try{setLocalityRows(id?await api(`/storefront/${STORE}/locations?parentId=${encodeURIComponent(id)}&level=LOCALITY`):[])}catch{setLocalityRows([])}}
  async function changeLocality(id:string){setLocality(id);try{setNeighborhoodRows(id?await api(`/storefront/${STORE}/locations?parentId=${encodeURIComponent(id)}&level=NEIGHBORHOOD`):[])}catch{setNeighborhoodRows([])}}
  const geoNames=useMemo(()=>({state:admin1Rows.find(x=>x.id===admin1)?.name||'',district:admin2Rows.find(x=>x.id===admin2)?.name||'',locality:localityRows.find(x=>x.id===locality)?.name||''}),[admin1,admin2,locality,admin1Rows,admin2Rows,localityRows]);
  async function addAddress(e:FormEvent<HTMLFormElement>){e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));try{await auth('/storefront/customer/addresses',{method:'POST',body:JSON.stringify({...f,country,state:geoNames.state,city:geoNames.state||f.cityManual,district:geoNames.district||geoNames.locality||f.districtManual,admin1Id:admin1||null,admin2Id:admin2||null,localityId:locality||null,neighborhoodId:f.neighborhoodId||null,isDefault:f.isDefault==='true'})});setMsg('Adres eklendi.');e.currentTarget.reset();await load(token)}catch(e:any){setErr(e.message)}}
  async function askQuestion(e:FormEvent<HTMLFormElement>){e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));try{await auth('/storefront/customer/questions',{method:'POST',body:JSON.stringify({type:f.type,productId:f.type==='PRODUCT'?f.relatedId:undefined,orderId:f.type==='ORDER'?f.relatedId:undefined,subject:f.subject,question:f.question})});setMsg('Sorunuz iletildi.');await load(token)}catch(e:any){setErr(e.message)}}
  if(!token||!me){const suffix=returnTo?`&return=${encodeURIComponent(returnTo)}`:'';return <main className="container"><div className="page-title"><h1>{mode==='register'?'Üye ol':'Hesabım'}</h1><p className="muted">{returnTo?'Ödeme işlemine devam etmek için hesabınızı kullanın.':'Siparişlerinizi, adreslerinizi ve alışveriş bilgilerinizi yönetin.'}</p></div>{err&&<div className="error">{err}</div>}<div className={mode==='both'?'checkout-grid':'account-auth-single'}>{mode!=='register'&&<form className="account-auth-card" onSubmit={login}><h2>Giriş yap</h2><p className="muted">Mevcut hesabınızla devam edin.</p><label className="field">E-posta<input name="email" type="email" autoComplete="email" required/></label><label className="field">Şifre<input name="password" type="password" autoComplete="current-password" required/></label><button className="btn account-auth-submit">Giriş yap</button>{mode==='login'&&<p className="account-auth-switch">Hesabınız yok mu? <Link href={`/account?mode=register${suffix}`}>Üye olun</Link></p>}</form>}{mode!=='login'&&<form className="account-auth-card" onSubmit={register}><h2>Yeni hesap</h2><p className="muted">Siparişlerinizi takip etmek ve adreslerinizi saklamak için hesap oluşturun.</p><div className="form-grid"><label>Ad<input name="firstName" required/></label><label>Soyad<input name="lastName" required/></label><label className="full">E-posta<input name="email" type="email" required/></label><label className="full">Telefon<input name="phone"/></label><label className="full">Şifre<input name="password" type="password" minLength={10} required placeholder="En az 10 karakter, büyük/küçük harf ve rakam"/></label></div><label className="consent"><input type="checkbox" name="terms" required/> Kullanım koşullarını kabul ediyorum.</label><label className="consent"><input type="checkbox" name="privacy" required/> Gizlilik politikasını okudum.</label><label className="consent"><input type="checkbox" name="kvkkNotice" required/> KVKK aydınlatma metnini okudum.</label><label className="consent"><input type="checkbox" name="emailMarketing"/> E-posta kampanyalarına izin veriyorum.</label><button className="btn account-auth-submit">Hesap oluştur</button>{mode==='register'&&<p className="account-auth-switch">Zaten hesabınız var mı? <Link href={`/account?mode=login${suffix}`}>Giriş yapın</Link></p>}</form>}</div></main>;}
  const tabs:[Tab,string][]=[['overview','Genel'],['orders','Siparişler'],['addresses','Adresler'],['wishlist','Favoriler'],['returns','İadeler'],['reviews','Yorumlar'],['questions','Sorular'],['privacy','KVKK & Gizlilik']];
  return <main className="container account-dashboard"><div className="page-title"><div><h1>Merhaba {me.firstName||me.email}</h1><p className="muted">Üyelik panelinizden tüm alışveriş işlemlerinizi yönetin.</p></div><button className="btn alt" onClick={async()=>{try{await api('/storefront/customer/logout',{method:'POST',credentials:'include',body:'{}'})}catch{}setToken('');setMe(null)}}>Çıkış</button></div>{err&&<div className="error">{err}</div>}{msg&&<div className="notice">{msg}</div>}<div className="account-tabs">{tabs.map(([k,l])=><button type="button" key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>
  {tab==='overview'&&<div className="account-grid"><div className="panel"><h2>Profil</h2><form className="form-grid" onSubmit={saveProfile}><label>Ad<input name="firstName" defaultValue={me.firstName||''}/></label><label>Soyad<input name="lastName" defaultValue={me.lastName||''}/></label><label>Telefon<input name="phone" defaultValue={me.phone||''}/></label><label>E-posta<input value={me.email} disabled/></label><div className="full"><button className="btn">Profili kaydet</button></div></form></div><div className="panel"><h2>Özet</h2><div className="metric-list"><span><b>{orders.length}</b> sipariş</span><span><b>{wishlist.length}</b> favori</span><span><b>{me.loyaltyAccount?.points||0}</b> sadakat puanı</span><span><b>{questions.filter(x=>x.status!=='CLOSED').length}</b> açık soru</span></div></div></div>}
  {tab==='orders'&&<section className="panel"><h2>Siparişlerim</h2>{orders.length?orders.map(o=><div className="account-order" key={o.id}><b>#{o.number}</b><span>{o.status}</span><strong>{money(o.grandTotal,o.currency)}</strong><div className="muted">{new Date(o.createdAt).toLocaleString(getLocale())}</div></div>):<p>Henüz siparişiniz yok.</p>}</section>}
  {tab==='addresses'&&<div className="account-grid"><section className="panel"><h2>Kayıtlı adresler</h2>{me.addresses?.length?me.addresses.map((a:any)=><div className="address-card" key={a.id}><b>{a.title||'Adres'}</b><p>{a.address1}<br/>{a.district} {a.city}<br/>{a.country}</p>{a.isDefault&&<small>Varsayılan</small>}</div>):<p>Adres eklenmemiş.</p>}</section><section className="panel"><h2>Adres ekle</h2><form className="form-grid" onSubmit={addAddress}><label>Başlık<input name="title" placeholder="Ev / İş"/></label><label>Ad<input name="firstName" defaultValue={me.firstName||''} required/></label><label>Soyad<input name="lastName" defaultValue={me.lastName||''} required/></label><label>Telefon<input name="phone" defaultValue={me.phone||''}/></label><label className="full">Adres<input name="address1" required/></label><label>Ülke<select value={country} onChange={e=>void changeCountry(e.target.value)}>{refs.countries?.map((c:string)=><option key={c} value={c}>{new Intl.DisplayNames([getLocale()],{type:'region'}).of(c)||c}</option>)}</select></label><label>İl / Eyalet{admin1Rows.length?<select value={admin1} onChange={e=>void changeAdmin1(e.target.value)} required><option value="">Seçiniz</option>{admin1Rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<input name="cityManual" required/>}</label><label>İlçe{admin2Rows.length?<select value={admin2} onChange={e=>void changeAdmin2(e.target.value)}><option value="">Seçiniz</option>{admin2Rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<input name="districtManual"/>}</label><label>Semt{localityRows.length?<select value={locality} onChange={e=>void changeLocality(e.target.value)}><option value="">Seçiniz</option>{localityRows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<input name="localityManual"/>}</label><label>Mahalle{neighborhoodRows.length?<select name="neighborhoodId"><option value="">Seçiniz</option>{neighborhoodRows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<input name="neighborhoodManual"/>}</label><label>Posta kodu<input name="postalCode"/></label><label>Varsayılan<select name="isDefault"><option value="false">Hayır</option><option value="true">Evet</option></select></label><div className="full"><button className="btn">Adresi ekle</button></div></form></section></div>}
  {tab==='wishlist'&&<section className="panel"><h2>Favorilerim</h2><div className="grid">{wishlist.map((w:any)=><Link href={'/products/'+w.product.slug} key={w.id} className="product-card"><div className="product-image product-image-wrap">{w.product.images?.[0]&&<><img src={w.product.images[0].url} alt={w.product.title}/>{w.product.images[0].aiGenerated&&<span className="product-ai-badge" title="AI ile oluşturuldu">AI</span>}</>}</div><h3>{w.product.title}</h3></Link>)}</div>{!wishlist.length&&<p>Favori ürününüz yok.</p>}</section>}
  {tab==='returns'&&<section className="panel"><h2>İade taleplerim</h2>{returns.length?returns.map((r:any)=><div className="account-order" key={r.id}><b>#{r.order?.number}</b><span>{r.status}</span><span>{r.reason||'İade'}</span><div className="muted">{new Date(r.createdAt).toLocaleDateString(getLocale())}</div></div>):<p>İade talebiniz yok.</p>}</section>}
  {tab==='reviews'&&<section className="panel"><h2>Yorumlarım</h2>{reviews.length?reviews.map((r:any)=><div className="review-row" key={r.id}><b>{r.product?.title}</b><span>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><p>{r.body}</p><small>{r.status}{r.verifiedPurchase?' · Doğrulanmış alışveriş':''}</small></div>):<p>Henüz yorumunuz yok.</p>}</section>}
  {tab==='questions'&&<div className="account-grid"><section className="panel"><h2>Sorularım</h2>{questions.length?questions.map((q:any)=><div className="review-row" key={q.id}><b>{q.type==='PRODUCT'?'Ürün sorusu':'Sipariş sorusu'} · {q.status}</b><p>{q.question}</p>{q.answer&&<p><strong>Yanıt:</strong> {q.answer}</p>}</div>):<p>Henüz sorunuz yok.</p>}</section><section className="panel"><h2>Yeni soru</h2><form className="form-grid" onSubmit={askQuestion}><label>Tür<select name="type"><option value="ORDER">Sipariş sorusu</option><option value="PRODUCT">Ürün sorusu</option></select></label><label>İlgili kayıt<select name="relatedId">{orders.map((o:any)=><option key={o.id} value={o.id}>Sipariş #{o.number}</option>)}</select></label><label className="full">Konu<input name="subject"/></label><label className="full">Soru<textarea name="question" required/></label><div className="full"><button className="btn">Soruyu gönder</button></div></form><small className="muted">Ürün sorusu için ürün detay sayfasından soru gönderme alanı da kullanılabilir.</small></section></div>}
  {tab==='privacy'&&<div className="account-grid"><section className="panel"><h2>KVKK / GDPR taleplerim</h2><form className="form-grid" onSubmit={privacy}><label>Talep türü<select name="type"><option value="ACCESS">Verilerime erişim</option><option value="RECTIFY">Düzeltme</option><option value="PORTABILITY">Veri taşınabilirliği</option><option value="RESTRICT">İşlemeyi kısıtlama</option><option value="OBJECT">İtiraz</option><option value="DELETE">Silme</option></select></label><label>Not<input name="note"/></label><div className="full"><button className="btn alt">Talep oluştur</button></div></form>{privacyRows.map((p:any)=><div className="account-order" key={p.id}><b>{p.type}</b><span>{p.status}</span><span>{new Date(p.createdAt).toLocaleDateString(getLocale())}</span></div>)}</section><section className="panel"><h2>İzin geçmişi</h2>{consents.map((c:any)=><div className="account-order" key={c.id}><b>{c.type}</b><span>{c.granted?'İzin verildi':'İzin verilmedi'}</span><span>{c.documentVersion||'-'}</span></div>)}</section></div>}
  </main>
}
