'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import ProductCard from '../../../components/ProductCard';
import {api,STORE,getCartToken,setCartToken,money,getCurrency,getLocale,mediaUrl,track} from '../../../lib/api';
const A='/signature-assets/';
function I({name}:{name:string}){return <img className="theme-icon" width="20" height="20" src={`${A}${name}.svg`} alt="" aria-hidden="true"/>}
export default function Product(){
  const {slug}=useParams<{slug:string}>();const[p,setP]=useState<any>(null);const[v,setV]=useState('');const[err,setErr]=useState('');const[qty,setQty]=useState(1);const[activeImage,setActiveImage]=useState(0);const[busy,setBusy]=useState(false);const[liked,setLiked]=useState(false);const[tab,setTab]=useState<'description'|'details'|'reviews'>('description');const[lightbox,setLightbox]=useState(false);const[sizeChart,setSizeChart]=useState(false);const[related,setRelated]=useState<any[]>([]);
  async function load(){api(`/storefront/${STORE}/products/${slug}?currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`).then((x:any)=>{setP(x);setV(old=>old&&x.variants?.some((z:any)=>z.id===old)?old:(x.variants?.[0]?.id||''));track('view_item',{item_id:x.id,item_name:x.title,value:Number(x.variants?.[0]?.price||0),currency:x.displayCurrency});try{const a=JSON.parse(localStorage.getItem('ticarti-wishlist')||'[]');setLiked(a.includes(String(x.id)));const recent=JSON.parse(localStorage.getItem('ticarti-recent')||'[]').filter((id:string)=>id!==String(x.id));localStorage.setItem('ticarti-recent',JSON.stringify([String(x.id),...recent].slice(0,12)))}catch{};api(`/storefront/${STORE}/products?limit=8&currency=${encodeURIComponent(getCurrency())}&locale=${encodeURIComponent(getLocale())}`).then((r:any)=>setRelated((r.items||[]).filter((item:any)=>item.id!==x.id).slice(0,4))).catch(()=>{})}).catch(x=>setErr(x.message))}
  useEffect(()=>{void load();const h=()=>void load();window.addEventListener('currency-change',h);window.addEventListener('locale-change',h);return()=>{window.removeEventListener('currency-change',h);window.removeEventListener('locale-change',h)}},[slug]);
  const variant=p?.variants?.find((x:any)=>x.id===v)||p?.variants?.[0];const stock=Math.max(0,(variant?.inventory?.onHand||0)-(variant?.inventory?.reserved||0));const average=useMemo(()=>{const a=p?.reviews||[];return a.length?a.reduce((n:number,r:any)=>n+Number(r.rating||0),0)/a.length:0},[p?.reviews]);const meta=p?.metadata?.signature||p?.metadata||{};
  async function add(){if(!v||busy)return;setBusy(true);try{let t=getCartToken();if(!t){const c=await api(`/storefront/${STORE}/carts`,{method:'POST',body:JSON.stringify({currency:getCurrency()})});t=c.token;setCartToken(t)}await api(`/storefront/carts/${t}/items`,{method:'POST',body:JSON.stringify({variantId:v,quantity:qty})});track('add_to_cart',{item_id:p?.id,item_name:p?.title,variant_id:v,value:Number(variant?.price||0),currency:p?.displayCurrency,quantity:qty});window.dispatchEvent(new Event('cart-change'))}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  function toggleLike(){if(!p)return;let arr:string[]=[];try{arr=JSON.parse(localStorage.getItem('ticarti-wishlist')||'[]')}catch{};arr=arr.includes(String(p.id))?arr.filter(x=>x!==String(p.id)):[...arr,String(p.id)];localStorage.setItem('ticarti-wishlist',JSON.stringify(arr));setLiked(arr.includes(String(p.id)))}
  if(err&&!p)return <main className="page-width top-spacing-normal"><div className="color-error">{err}</div></main>;if(!p)return <main className="page-width top-spacing-normal">Ürün yükleniyor…</main>;const images=Array.isArray(p.images)?p.images:[];
  return <main id="MainContent" className="content-for-layout focus-none"><div className="page-width breadcrumbs body3"><Link href="/">Anasayfa</Link><span> / </span><Link href="/products">Ürünler</Link><span> / </span><span>{p.title}</span></div><section className="top-spacing-normal"><div className="page-width"><div className="main-product__container product--thumbnail_slider">
    <div className="product__column product__left-column"><div className="product__media-sticky"><div className="product__media-gallery page-grid-1"><div className="product__media-list">{images.map((x:any,i:number)=><button key={x.id||i} className={`product__media-item image-hover-box__container ${activeImage===i?'active':''}`} onClick={()=>{setActiveImage(i);setLightbox(true)}}><div className="image-hover-box image-hover-box__small-radius"><img src={mediaUrl(x.url,'detail','webp')} alt={x.alt||p.title}/></div></button>)}</div><div className="product__media-thumbnails display-flex mt15">{images.map((x:any,i:number)=><button key={x.id||i} className={`product__media-thumbnail ${activeImage===i?'active':''}`} onClick={()=>setActiveImage(i)}><img src={mediaUrl(x.url,'thumb','webp')} alt=""/></button>)}</div></div></div></div>
    <div className="product__column product__right-column"><div className="product__column__content product__right-column-sticky mt-first-child-0">{p.brand?.name&&<div className="body3 text-uppercase">{p.brand.name}</div>}<h1 className="h2 mt8">{p.title}</h1>{p.reviews?.length>0&&<button className="review-stars mt10 clear-underline" onClick={()=>setTab('reviews')}><span>{'★'.repeat(Math.round(average))}{'☆'.repeat(5-Math.round(average))}</span> <span className="body3">{p.reviews.length} değerlendirme</span></button>}<div className="price price--large h3 mt16"><div className="price__container"><div className="price__regular"><span className="price-item price-item--regular">{money(variant?.price,p.displayCurrency)}</span></div>{variant?.comparePrice&&Number(variant.comparePrice)>Number(variant.price)&&<div className="price__sale"><span className="price-item price-item--sale price-item--last">{money(variant.price,p.displayCurrency)}</span><s className="price-item price-item--regular">{money(variant.comparePrice,p.displayCurrency)}</s></div>}</div></div><div className="body2 mt20">{p.shortDescription||meta.smallDescription||p.description}</div>
    {p.variants?.length>1&&<div className="product-form__input mt30"><div className="display-flex justify-content-between"><label className="form__label strong">Seçenek</label><button className="link body3" onClick={()=>setSizeChart(true)}>Ölçü rehberi</button></div><div className="product-form__input--pill mt10">{p.variants.map((x:any)=><button className={`button-swatches ${v===x.id?'active':''}`} key={x.id} onClick={()=>setV(x.id)}>{x.title}</button>)}</div></div>}
    <div className="body3 mt20"><span className={stock>0?'color-success':'color-error'}>{stock>0?`Stokta · ${stock} adet`:'Stokta yok'}</span></div><div className="product-form__buttons mt20"><div className="display-flex"><div className="field quantity"><button className="quantity__button" onClick={()=>setQty(Math.max(1,qty-1))}><I name="icon-minus"/></button><input className="field__input quantity__input" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/><button className="quantity__button" onClick={()=>setQty(qty+1)}><I name="icon-plus"/></button></div><button className="product-form__submit btn btn__transition-text flex-1" disabled={busy||stock<1} onClick={()=>void add()}><span className="btn__texts"><span className="btn__top-text is-visible"><I name="icon-cart"/>{busy?'Ekleniyor…':'Sepete ekle'}</span></span></button></div></div>
    <div className="display-flex mt20"><button className="link body2" onClick={toggleLike}><I name="icon-heart"/>{liked?'Favorilerden çıkar':'Favorilere ekle'}</button><button className="link body2 ml20" onClick={()=>navigator.share?.({title:p.title,url:location.href})}><I name="icon-share"/>Paylaş</button></div>
    <div className="accordion mt30"><details open><summary className="h6">Teslimat ve iade</summary><div className="body2 mt10"><p>Hızlı teslimat seçenekleri ödeme adımında gösterilir.</p><p>İade koşulları mağaza politikasına göre uygulanır.</p></div></details></div>
    </div></div></div></div></section>
    <section className="top-spacing-normal"><div className="page-width"><div className="featured-tabs"><div className="featured-tabs__buttons display-flex justify-content-center"><button className={`btn btn--border ${tab==='description'?'active':''}`} onClick={()=>setTab('description')}>Açıklama</button><button className={`btn btn--border ${tab==='details'?'active':''}`} onClick={()=>setTab('details')}>Ürün bilgileri</button><button className={`btn btn--border ${tab==='reviews'?'active':''}`} onClick={()=>setTab('reviews')}>Değerlendirmeler</button></div><div className="featured-tabs__content mt30 body2">{tab==='description'&&<div dangerouslySetInnerHTML={{__html:String(p.description||p.shortDescription||'')}}/>}{tab==='details'&&<div className="page-grid-2"><div><b>Marka</b><p>{p.brand?.name||'—'}</p></div><div><b>Varyant</b><p>{variant?.title||'Standart'}</p></div><div><b>Stok</b><p>{stock}</p></div><div><b>SKU</b><p>{variant?.sku||p.sku||'—'}</p></div></div>}{tab==='reviews'&&<div>{p.reviews?.length?p.reviews.map((r:any)=><article className="review-item mt20" key={r.id}><div className="review-stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><p>{r.body}</p><small>{r.authorName||'Müşteri'}</small></article>):<p>Henüz değerlendirme yok.</p>}</div>}</div></div></div></section>
    {related.length>0&&<section className="top-spacing-normal"><div className="page-width"><div className="text-center"><div className="body3 text-uppercase">Sizin için</div><h2 className="h2 mt8">Bunları da beğenebilirsiniz</h2></div><div className="page-grid-4 page-grid-st-2 page-grid-sp-2 mt30">{related.map((item:any)=><ProductCard key={item.id} p={item} currency={p.displayCurrency}/>)}</div></div></section>}
    {lightbox&&<div className="popup-modal active" role="dialog" aria-modal="true"><button className="popup-modal__overlay" onClick={()=>setLightbox(false)} aria-label="Kapat"/><div className="popup-modal__content"><button className="popup-modal__toggle" onClick={()=>setLightbox(false)}><I name="icon-close"/></button><img className="width-100" src={mediaUrl(images[activeImage]?.url,'hero','webp')} alt={images[activeImage]?.alt||p.title}/></div></div>}
    {sizeChart&&<div className="popup-modal popup-modal__right active" role="dialog" aria-modal="true"><button className="popup-modal__overlay" onClick={()=>setSizeChart(false)} aria-label="Kapat"/><div className="popup-modal__content popup-modal__content__f-height"><button className="popup-modal__toggle" onClick={()=>setSizeChart(false)}><I name="icon-close"/></button><div className="popup-modal__content__data custom__scrollbar page-width"><h2 className="h4 mt40">Ölçü rehberi</h2><table className="mt20"><tbody>{p.variants.map((x:any)=><tr key={x.id}><td>{x.title}</td><td>Ürün açıklamasındaki ölçüleri kontrol edin</td></tr>)}</tbody></table></div></div></div>}
  </main>;
}
