import manifest from './skin-manifest.json';
import skin0 from './skins/demo-1.json';
import skin1 from './skins/demo-2.json';
import skin2 from './skins/demo-3.json';
import skin3 from './skins/demo-4.json';
import skin4 from './skins/demo-5.json';
import skin5 from './skins/demo-6.json';
import skin6 from './skins/demo-7.json';
import skin7 from './skins/demo-8.json';
import skin8 from './skins/demo-9.json';
import skin9 from './skins/demo-10.json';
import skin10 from './skins/demo-11.json';
import skin11 from './skins/demo-12.json';
import skin12 from './skins/demo-13.json';
import skin13 from './skins/demo-14.json';
import skin14 from './skins/demo-15.json';
import skin15 from './skins/demo-16.json';
import skin16 from './skins/demo-17.json';
import skin17 from './skins/demo-18.json';
import skin18 from './skins/demo-19.json';
import skin19 from './skins/demo-20.json';
import skin20 from './skins/demo-21.json';
import skin21 from './skins/demo-22.json';
import skin22 from './skins/american-gear-football-store.json';
import skin23 from './skins/baby-care-store.json';
import skin24 from './skins/baseball-gear-store.json';
import skin25 from './skins/basketball-gear-store.json';
import skin26 from './skins/beers-store.json';
import skin27 from './skins/bicycle-store-1.json';
import skin28 from './skins/bicycle-store-2.json';
import skin29 from './skins/books-store-1.json';
import skin30 from './skins/books-store-2.json';
import skin31 from './skins/cakes-and-pastries-store-catalog.json';
import skin32 from './skins/cars-store.json';
import skin33 from './skins/christmas-store.json';
import skin34 from './skins/clothes-store.json';
import skin35 from './skins/coffee-store.json';
import skin36 from './skins/comic-books-store.json';
import skin37 from './skins/cookware-store.json';
import skin38 from './skins/cosmetics-store.json';
import skin39 from './skins/drones-store.json';
import skin40 from './skins/eco-food-store.json';
import skin41 from './skins/electronics-store-1.json';
import skin42 from './skins/flowers-store.json';
import skin43 from './skins/food-delivery-store-restaurant.json';
import skin44 from './skins/furniture-store-1.json';
import skin45 from './skins/furniture-store-2.json';
import skin46 from './skins/glasses-store.json';
import skin47 from './skins/gothic-and-rock-clothing.json';
import skin48 from './skins/handmade-store-sculptor.json';
import skin49 from './skins/jewelry-store.json';
import skin50 from './skins/kids-clothes-store.json';
import skin51 from './skins/kids-toys-store.json';
import skin52 from './skins/lifestyle-store.json';
import skin53 from './skins/lingerie-store.json';
import skin54 from './skins/medical-store.json';
import skin55 from './skins/olives-store.json';
import skin56 from './skins/phone-cases-store.json';
import skin57 from './skins/phones-store.json';
import skin58 from './skins/plants-store.json';
import skin59 from './skins/single-product-store-1.json';
import skin60 from './skins/single-product-store-2.json';
import skin61 from './skins/single-product-store-3.json';
import skin62 from './skins/skin-care-store.json';
import skin63 from './skins/snowboards-store.json';
import skin64 from './skins/t-shirt-store.json';
import skin65 from './skins/tea-store.json';
import skin66 from './skins/tools-store-1.json';
import skin67 from './skins/tools-store-2.json';
import skin68 from './skins/wallets-store.json';
import skin69 from './skins/watches-store.json';
import skin70 from './skins/weapons-store.json';
import skin71 from './skins/yoga-gear-store.json';
import skin72 from './skins/antiques-store.json';
import skin73 from './skins/electronics-store-2.json';
import skin74 from './skins/food-and-drinks-store.json';
import skin75 from './skins/food-delivery-store.json';
import skin76 from './skins/hookah-store.json';
import skin77 from './skins/organic-store.json';
import skin78 from './skins/pets-supplies-1.json';
import skin79 from './skins/pets-supplies-2.json';
import skin80 from './skins/shoes-store.json';
import skin81 from './skins/sport-nutrition-store.json';
import skin82 from './skins/start-up-store.json';
import skin83 from './skins/tattoo-store.json';

type AnyMap=Record<string,any>;
export type TicartiSkin={slug:string;name:string;group?:string;category?:string;sortOrder?:number;previewImageUrl?:string;design:AnyMap;homePreset:any[];verifiedFromDemo?:boolean;aliases?:string[]};
const meta:any=manifest;
const loaded:any[]=[skin0,skin1,skin2,skin3,skin4,skin5,skin6,skin7,skin8,skin9,skin10,skin11,skin12,skin13,skin14,skin15,skin16,skin17,skin18,skin19,skin20,skin21,skin22,skin23,skin24,skin25,skin26,skin27,skin28,skin29,skin30,skin31,skin32,skin33,skin34,skin35,skin36,skin37,skin38,skin39,skin40,skin41,skin42,skin43,skin44,skin45,skin46,skin47,skin48,skin49,skin50,skin51,skin52,skin53,skin54,skin55,skin56,skin57,skin58,skin59,skin60,skin61,skin62,skin63,skin64,skin65,skin66,skin67,skin68,skin69,skin70,skin71,skin72,skin73,skin74,skin75,skin76,skin77,skin78,skin79,skin80,skin81,skin82,skin83];
export const TICARTI_DEFAULT_SKIN=String(meta.defaultSkin||'demo-1');
export const TICARTI_SKINS:TicartiSkin[]=loaded as TicartiSkin[];
const aliasMap=new Map<string,string>();
for(const skin of TICARTI_SKINS){aliasMap.set(String(skin.slug).toLowerCase(),skin.slug);aliasMap.set(String(skin.name||'').toLowerCase(),skin.slug);for(const a of skin.aliases||[])aliasMap.set(String(a).toLowerCase(),skin.slug)}
export function normalizeSkinSlug(value:any){const raw=String(value||'').trim().toLowerCase();if(!raw)return TICARTI_DEFAULT_SKIN;return aliasMap.get(raw)||raw.replace(/\s+/g,'-')}
export const normalizeTicartiSkinSlug=normalizeSkinSlug;
export function getTicartiSkinPreset(value:any):TicartiSkin{const slug=normalizeSkinSlug(value);return TICARTI_SKINS.find(x=>x.slug===slug)||TICARTI_SKINS.find(x=>x.slug===TICARTI_DEFAULT_SKIN)||TICARTI_SKINS[0]}
export function ticartiSkinCatalog(){return TICARTI_SKINS}
