'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
const tabs=['Genel Bakış','Firmalar','Paketler','Temalar','Alan Adları','Uygulamalar','Kullanıcılar','Döviz','Destek'];
const tabRoutes:Record<string,string>={'Genel Bakış':'/','Firmalar':'/tenants','Paketler':'/plans','Temalar':'/themes','Alan Adları':'/domains','Uygulamalar':'/apps','Kullanıcılar':'/users','Döviz':'/currency','Destek':'/support'};

export default function SuperAdminApp({initialTab='Genel Bakış'}:{initialTab?:string}){
  const router=useRouter(); const [restoring,setRestoring]=useState(true);
  const [token,setToken]=useState(''); const [tab,setTab]=useState(initialTab);
  useEffect(()=>{setTab(initialTab)},[initialTab]); const [data,setData]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{void restore()},[]);
  async function restore(){try{const r=await fetch(API+'/superadmin-auth/refresh',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-auth-client':'superadmin'},body:'{}'});if(!r.ok)return;const j=await r.json();if(j.accessToken)setToken(j.accessToken)}catch{}finally{setRestoring(false)}}
  useEffect(()=>{if(!restoring&&!token)router.replace('/login')},[restoring,token,router]);
  async function req(path:string,o:any={}){let r=await fetch(API+path,{...o,credentials:'include',headers:{'content-type':'application/json','authorization':`Bearer ${token}`,...o.headers}});if(r.status===401){const rr=await fetch(API+'/superadmin-auth/refresh',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-auth-client':'superadmin'},body:'{}'});if(rr.ok){const x=await rr.json();setToken(x.accessToken);r=await fetch(API+path,{...o,credentials:'include',headers:{'content-type':'application/json','authorization':`Bearer ${x.accessToken}`,...o.headers}})}}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Array.isArray(j.message)?j.message.join(', '):(j.message||'İşlem başarısız'));return j}

  useEffect(()=>{if(token)void load()},[token,tab]);
  async function load(){try{setError('');setData(null);let p='/superadmin/dashboard';if(tab==='Firmalar')p='/superadmin/tenants';if(tab==='Paketler')p='/superadmin/plans';if(tab==='Temalar')p='/superadmin/themes';if(tab==='Alan Adları')p='/superadmin/reserved-subdomains';if(tab==='Uygulamalar')p='/superadmin/apps';if(tab==='Kullanıcılar')p='/superadmin/users';if(tab==='Döviz')p='/superadmin/currency-rates';if(tab==='Destek')p='/superadmin/support/tickets';setData(await req(p))}catch(e:any){setError(e.message)}}
  if(restoring||!token)return <div className="login"><div className="login-card"><h1>Super Admin</h1><p className="muted">Güvenli oturum kontrol ediliyor…</p></div></div>;
  return <div className="app"><aside className="sidebar"><div className="brand">Commerce HQ</div><div className="nav">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>router.push(tabRoutes[x]||'/')} key={x}>{x}</button>)}</div></aside><main className="content"><div className="topbar"><div><h1 style={{margin:0}}>{tab}</h1><div className="muted">SaaS platform yönetimi</div></div><button className="btn secondary" onClick={async()=>{try{await fetch(API+'/superadmin-auth/logout',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-auth-client':'superadmin'},body:'{}'})}catch{}setToken('')}}>Çıkış</button></div>{error&&<div className="error">{error}</div>}<View tab={tab} data={data} req={req} reload={load}/></main></div>
}

function View({tab,data,req,reload}:any){
  if(!data)return <div className="panel">Yükleniyor…</div>;
  const list=Array.isArray(data)?data:[];
  if(tab==='Genel Bakış')return <><div className="cards">{[['Firma / Site',data.metrics?.tenants],['Aktif firma',data.metrics?.activeTenants],['Ürün',data.metrics?.products],['Açık destek',data.metrics?.openTickets]].map(([a,b])=><div className="card" key={a as string}><div className="muted">{a}</div><div className="metric">{b}</div></div>)}</div><div className="panel"><h3>Platform GMV</h3><div className="metric">₺{Number(data.metrics?.gmV||0).toLocaleString('tr-TR')}</div><h3>Yeni firmalar</h3><Table rows={data.recentTenants||[]} cols={[['name','Firma / Site'],['status','Durum'],['_count.products','Ürün'],['createdAt','Kayıt']]}/></div></>;
  if(tab==='Firmalar')return <><TenantControl tenants={list} req={req} reload={reload}/><div className="panel"><Table rows={list} cols={[['name','Firma / Site'],['domain','Domain'],['status','Durum'],['_count.products','Ürün'],['_count.memberships','Kullanıcı'],['subscriptions.0.plan.name','Paket'],['createdAt','Kayıt']]}/></div></>;
  if(tab==='Paketler')return <><PlanForm req={req} reload={reload}/><div className="panel"><Table rows={list} cols={[['name','Paket'],['code','Kod'],['monthlyPrice','Aylık'],['maxStaff','Personel'],['maxProducts','Ürün'],['maxOrdersPerMonth','Aylık Sipariş'],['isActive','Aktif']]}/></div></>;
  if(tab==='Temalar')return <ThemeControl themes={list} req={req} reload={reload}/>;
  if(tab==='Alan Adları')return <ReservedSubdomainControl rows={list} req={req} reload={reload}/>;
  if(tab==='Uygulamalar')return <AppControl apps={list} req={req} reload={reload}/>;
  if(tab==='Kullanıcılar')return <div className="panel"><Table rows={list} cols={[['email','E-posta'],['name','Ad'],['createdAt','Kayıt']]}/></div>;
  if(tab==='Döviz')return <CurrencyControl data={data} req={req} reload={reload}/>;
  if(tab==='Destek')return <><SupportControl tickets={list} req={req} reload={reload}/><div className="panel"><Table rows={list} cols={[['subject','Konu'],['tenant.name','Firma'],['priority','Öncelik'],['status','Durum'],['messages.length','Mesaj'],['updatedAt','Güncelleme']]}/></div></>;
  return null;
}


function ThemeControl({themes,req,reload}:any){
  themes=Array.isArray(themes)?themes:[];
  const[plans,setPlans]=useState<any[]>([]);const[tenants,setTenants]=useState<any[]>([]);const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[edit,setEdit]=useState<any|null>(null);const[defaultsTheme,setDefaultsTheme]=useState<any|null>(null);
  useEffect(()=>{Promise.all([req('/superadmin/plans'),req('/superadmin/tenants')]).then(([p,t])=>{setPlans(Array.isArray(p)?p:[]);setTenants(Array.isArray(t)?t:[])}).catch((e:any)=>setErr(e.message))},[]);
  async function run(fn:()=>Promise<any>,ok:string){setMsg('');setErr('');try{await fn();setMsg(ok);await reload();return true}catch(e:any){setErr(e.message||'İşlem başarısız');return false}}
  return <>{msg&&<div className="success">{msg}</div>}{err&&<div className="error">{err}</div>}
    <div className="panel"><div className="toolbar"><div><h3 style={{margin:'0 0 6px'}}>Tema kataloğu</h3><p className="muted" style={{margin:0}}>Temayı aktif/pasif yapın, pakete dahil edin veya düşük paketlerde ayrıca satın alınabilir bırakın.</p></div><button className="btn" onClick={()=>setEdit({})}>Yeni tema</button></div></div>
    <div className="panel"><h3>Paket erişimi ve fiyatı</h3><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/themes/'+f.themeId+'/plan-pricing',{method:'POST',body:JSON.stringify({planId:f.planId,price:f.price===''?null:Number(f.price),currency:f.currency,included:f.included==='true',isActive:true})}),'Tema paket fiyatı kaydedildi.')}}><label>Tema<select name="themeId" required>{themes.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Paket<select name="planId" required>{plans.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Fiyat<input name="price" type="number" min="0" step="0.01" placeholder="Boş = tema temel fiyatı"/></label><label>Para birimi<select name="currency"><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Pakete dahil<select name="included"><option value="false">Hayır, ayrıca sat</option><option value="true">Evet, ücretsiz dahil</option></select></label><div className="full"><button className="btn">Kaydet</button></div></form></div>
    <div className="panel"><h3>Tema modüllerini aç / kapat</h3><p className="muted">Kapattığınız modül müşterinin tasarım kütüphanesinde görünmez. Mevcut mağazada eklenmiş içerik silinmez.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/themes/'+f.themeId+'/module-toggle',{method:'POST',body:JSON.stringify({type:f.type,enabled:f.enabled==='true'})}),'Modül erişimi güncellendi.')}}><label>Tema<select name="themeId" required>{themes.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Modül tipi<input name="type" placeholder="lookbook" required/></label><label>Durum<select name="enabled"><option value="true">Açık</option><option value="false">Kapalı</option></select></label><div className="full"><button className="btn">Uygula</button></div></form></div>
    <div className="panel"><h3>Mağazaya tema tanımla</h3><p className="muted">Ödeme kontrolünü atlayarak seçili mağazaya temayı lisanslar. Tema otomatik aktif edilmez.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/tenants/'+f.tenantId+'/themes/'+f.themeId+'/grant',{method:'POST',body:'{}'}),'Tema mağazaya tanımlandı.')}}><label>Mağaza<select name="tenantId" required>{tenants.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Tema<select name="themeId" required>{themes.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><div className="full"><button className="btn">Tema ver</button></div></form></div>
    <div className="panel"><table><thead><tr><th>Tema</th><th>Kategori</th><th>Temel fiyat</th><th>Paket kuralları</th><th>Kurulum</th><th>Durum</th><th></th></tr></thead><tbody>{themes.map((t:any)=><tr key={t.id}><td><div className="sa-theme-cell">{t.previewImageUrl?<img src={t.previewImageUrl} alt=""/>:<span className="sa-theme-fallback">THEME</span>}<div><b>{t.name}</b><div className="muted">{t.slug}</div></div></div></td><td>{t.category}</td><td>{Number(t.basePrice||0).toLocaleString('tr-TR')} {t.currency}</td><td>{t.planPrices?.length||0}</td><td>{t._count?.installations||0}</td><td>{t.isActive?'Aktif':'Pasif'}{t.isDefault?' · Varsayılan':''}</td><td><div className="sa-table-actions"><button className="btn secondary" onClick={()=>setEdit(t)}>Düzenle</button><button className="btn secondary" onClick={()=>setDefaultsTheme(t)}>Varsayılan ayarlar</button><button className="btn secondary" onClick={()=>void run(()=>req('/superadmin/themes/'+t.id,{method:'PATCH',body:JSON.stringify({isActive:!t.isActive})}),t.isActive?'Tema kapatıldı.':'Tema açıldı.')}>{t.isActive?'Kapat':'Aç'}</button></div></td></tr>)}</tbody></table></div>
    {defaultsTheme&&<ThemeDefaultsModal theme={defaultsTheme} req={req} onClose={()=>setDefaultsTheme(null)} onSaved={()=>{setMsg('Tema varsayılan ayarları kaydedildi.');void reload()}}/>}
    {edit!==null&&<div className="sa-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><div className="sa-modal"><div className="sa-modal-head"><div><h2>{edit?.id?'Temayı düzenle':'Yeni tema'}</h2><p className="muted">Müşterinin göreceği isim ve ticari ayarlar.</p></div><button className="btn secondary" onClick={()=>setEdit(null)}>Kapat</button></div><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));const payload={name:f.name,slug:f.slug,category:f.category,description:f.description,previewImageUrl:f.previewImageUrl,basePrice:Number(f.basePrice||0),currency:f.currency,billingType:'ONE_TIME',isFeatured:f.isFeatured==='true',isDefault:f.isDefault==='true',isActive:true,sortOrder:Number(f.sortOrder||0)};const ok=await run(()=>edit?.id?req('/superadmin/themes/'+edit.id,{method:'PATCH',body:JSON.stringify(payload)}):req('/superadmin/themes',{method:'POST',body:JSON.stringify(payload)}),edit?.id?'Tema güncellendi.':'Tema eklendi.');if(ok)setEdit(null)}}><label>Tema adı<input name="name" defaultValue={edit?.name||''} required/></label><label>Slug<input name="slug" defaultValue={edit?.slug||''} required={!edit?.id} readOnly={!!edit?.id}/></label><label>Kategori<input name="category" defaultValue={edit?.category||'GENEL'}/></label><label>Temel fiyat<input name="basePrice" type="number" min="0" step="0.01" defaultValue={edit?.basePrice??0}/></label><label>Preview görseli URL<input name="previewImageUrl" defaultValue={edit?.previewImageUrl||''} placeholder="https://..."/></label><label>Para birimi<select name="currency" defaultValue={edit?.currency||'TRY'}><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Öne çıkan<select name="isFeatured" defaultValue={String(!!edit?.isFeatured)}><option value="false">Hayır</option><option value="true">Evet</option></select></label><label>Varsayılan<select name="isDefault" defaultValue={String(!!edit?.isDefault)}><option value="false">Hayır</option><option value="true">Evet</option></select></label><label>Sıra<input name="sortOrder" type="number" defaultValue={edit?.sortOrder??0}/></label><label className="full">Açıklama<textarea name="description" defaultValue={edit?.description||''}/></label><div className="full sa-modal-actions"><button type="button" className="btn secondary" onClick={()=>setEdit(null)}>Vazgeç</button><button className="btn">Kaydet</button></div></form></div></div>}
  </>;
}

function ThemeDefaultsModal({theme,req,onClose,onSaved}:any){
  const LANGS=[['tr-TR','TR'],['en-US','EN'],['de-DE','DE'],['fr-FR','FR'],['ar-SA','AR']];
  const[rows,setRows]=useState<any[]>([]);const[skin,setSkin]=useState('');const[designText,setDesignText]=useState('{}');const[presetText,setPresetText]=useState('[]');const[name,setName]=useState('');const[category,setCategory]=useState('');const[previewImageUrl,setPreviewImageUrl]=useState('');const[err,setErr]=useState('');const[busy,setBusy]=useState(false);const[lang,setLang]=useState('tr-TR');const[langDrafts,setLangDrafts]=useState<Record<string,string>>({});
  useEffect(()=>{req('/superadmin/themes/'+theme.id+'/skin-defaults').then((x:any)=>{const list=Array.isArray(x)?x:[];setRows(list);if(list[0])selectRow(list[0])}).catch((e:any)=>setErr(e.message))},[theme.id]);
  function extractLocale(homePreset:any[]){const out:Record<string,any>={};for(const section of homePreset||[]){const sid=String(section?.sourceId||section?.settings?.__sourceId||'');if(!sid)continue;const map=section?.settings?._i18n||{};for(const [locale,value] of Object.entries(map)){out[locale]=out[locale]||{};out[locale][sid]=value}}return out}
  function selectRow(row:any){const preset=Array.isArray(row.homePreset)?row.homePreset:[];setSkin(row.slug);setName(row.name||'');setCategory(row.category||'');setPreviewImageUrl(row.previewImageUrl||'');setDesignText(JSON.stringify(row.design||{},null,2));setPresetText(JSON.stringify(preset,null,2));const loc=extractLocale(preset);const drafts:Record<string,string>={};for(const[l]of LANGS)drafts[l]=JSON.stringify(loc[l]||{},null,2);setLangDrafts(drafts);setErr('')}
  function applyLocaleDrafts(homePreset:any[]){const parsed:Record<string,any>={};for(const[l]of LANGS)parsed[l]=JSON.parse(langDrafts[l]||'{}');return homePreset.map((section:any)=>{const sid=String(section?.sourceId||section?.settings?.__sourceId||'');const settings={...(section.settings||{})};const i18n:any={...(settings._i18n||{})};for(const[l]of LANGS){if(parsed[l]?.[sid]&&typeof parsed[l][sid]==='object'&&Object.keys(parsed[l][sid]).length)i18n[l]=parsed[l][sid];else delete i18n[l]}return {...section,settings:{...settings,...(Object.keys(i18n).length?{_i18n:i18n}:{})}}})}
  async function save(){setErr('');setBusy(true);try{const design=JSON.parse(designText);let homePreset=JSON.parse(presetText);homePreset=applyLocaleDrafts(homePreset);await req('/superadmin/themes/'+theme.id+'/skin-defaults/'+encodeURIComponent(skin),{method:'PATCH',body:JSON.stringify({name,category,previewImageUrl,design,homePreset})});const raw=await req('/superadmin/themes/'+theme.id+'/skin-defaults');const next=Array.isArray(raw)?raw:[];setRows(next);const row=next.find((x:any)=>x.slug===skin);if(row)selectRow(row);onSaved()}catch(e:any){setErr(e.message||'JSON veya kayıt hatası')}finally{setBusy(false)}}
  async function reset(){if(!window.confirm('Bu skin DB kaydı silinsin mi? Silinirse tema seçiminde görünmez; dosyadan otomatik geri gelmez.'))return;setBusy(true);setErr('');try{await req('/superadmin/themes/'+theme.id+'/skin-defaults/'+encodeURIComponent(skin),{method:'DELETE'});const raw=await req('/superadmin/themes/'+theme.id+'/skin-defaults');const next=Array.isArray(raw)?raw:[];setRows(next);if(next[0])selectRow(next[0]);else setSkin('');onSaved()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  return <div className="sa-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="sa-modal sa-theme-defaults-modal"><div className="sa-modal-head"><div><h2>Tema DB kaynağı</h2><p className="muted">Bu ekran tema demosu ve yeni mağaza kurulumlarının merkezi kaynağıdır. Runtime dosya presetine fallback yapmaz.</p></div><button className="btn secondary" onClick={onClose}>Kapat</button></div>{err&&<div className="error">{err}</div>}<div className="sa-theme-defaults-grid"><aside><label>Skin<select value={skin} onChange={e=>{const row=rows.find((x:any)=>x.slug===e.target.value);if(row)selectRow(row)}}>{rows.map((x:any)=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></label><label>Görünen ad<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Kategori<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Preview görseli URL<input value={previewImageUrl} onChange={e=>setPreviewImageUrl(e.target.value)}/></label>{previewImageUrl&&<img className="sa-theme-preview" src={previewImageUrl} alt=""/>}<p className="muted">Kaynak: Genel sistem DB · ThemeDefinition.config.skinDefaults</p></aside><div><label>Design JSON<textarea className="sa-json-editor" value={designText} onChange={e=>setDesignText(e.target.value)}/></label><label>Home preset JSON<textarea className="sa-json-editor" value={presetText} onChange={e=>setPresetText(e.target.value)}/></label><div className="sa-lang-tabs">{LANGS.map(([code,label])=><button type="button" key={code} className={lang===code?'active':''} onClick={()=>setLang(code)}>{label}</button>)}</div><label>Dil içeriği · {lang}<textarea className="sa-json-editor" value={langDrafts[lang]||'{}'} onChange={e=>setLangDrafts(d=>({...d,[lang]:e.target.value}))}/></label><p className="muted">Format: {`{ "section-source-id": { "title": "...", "buttonText": "..." } }`}. Görsel/link/teknik ayarlar ortak kalır.</p></div></div><div className="sa-modal-actions"><button className="btn secondary" disabled={busy||!skin} onClick={()=>void reset()}>DB kaydını sil</button><button className="btn" disabled={busy||!skin} onClick={()=>void save()}>{busy?'Kaydediliyor…':'DB kaynağını kaydet'}</button></div></div></div>
}


function ReservedSubdomainControl({rows,req,reload}:any){
  const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  async function run(fn:()=>Promise<any>,ok:string){setMsg('');setErr('');try{await fn();setMsg(ok);await reload()}catch(e:any){setErr(e.message||'İşlem başarısız')}}
  return <>
    {msg&&<div className="success">{msg}</div>}{err&&<div className="error">{err}</div>}
    <div className="panel"><h3>Blokeli alt alan adları</h3><p className="muted">Bu listedeki adlar mağazalar tarafından <b>xxxx.ticarti.com</b> olarak seçilemez. Kilitli sistem kayıtları kapatılamaz.</p>
      <form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/reserved-subdomains',{method:'POST',body:JSON.stringify({value:f.value,reason:f.reason,isActive:true})}),'Alt alan adı bloke edildi.');e.currentTarget.reset()}}>
        <label>Alt alan adı<input name="value" placeholder="kampanya" required minLength={2} maxLength={63}/></label><label>Açıklama<input name="reason" placeholder="Platform kullanımı"/></label><div className="full"><button className="btn">Listeye ekle</button></div>
      </form>
    </div>
    <div className="panel"><table><thead><tr><th>Alt alan adı</th><th>Açıklama</th><th>Durum</th><th>Tür</th><th></th></tr></thead><tbody>{(rows||[]).map((x:any)=><tr key={x.id}><td><b>{x.value}.ticarti.com</b></td><td>{x.reason||'-'}</td><td>{x.isActive?'Blokeli':'Serbest'}</td><td>{x.locked?'Sistem':'Özel'}</td><td><div className="sa-table-actions"><button className="btn secondary" disabled={x.locked} onClick={()=>void run(()=>req('/superadmin/reserved-subdomains/'+x.id,{method:'PATCH',body:JSON.stringify({isActive:!x.isActive})}),x.isActive?'Alt alan adı serbest bırakıldı.':'Alt alan adı bloke edildi.')}>{x.isActive?'Serbest bırak':'Bloke et'}</button>{!x.locked&&<button className="btn secondary" onClick={()=>void run(()=>req('/superadmin/reserved-subdomains/'+x.id,{method:'DELETE'}),'Kayıt silindi.')}>Sil</button>}</div></td></tr>)}</tbody></table></div>
  </>;
}

function AppControl({apps,req,reload}:any){
  apps=Array.isArray(apps)?apps:[];
  const[plans,setPlans]=useState<any[]>([]);const[tenants,setTenants]=useState<any[]>([]);const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[editor,setEditor]=useState<any|null>(null);
  useEffect(()=>{Promise.all([req('/superadmin/plans'),req('/superadmin/tenants')]).then(([p,t])=>{setPlans(Array.isArray(p)?p:[]);setTenants(Array.isArray(t)?t:[])}).catch((e:any)=>setErr(e.message))},[]);
  async function run(fn:()=>Promise<any>,ok:string){setErr('');setMsg('');try{await fn();setMsg(ok);await reload();return true}catch(e:any){setErr(e.message);return false}}
  return <>
    {msg&&<div className="success">{msg}</div>}{err&&<div className="error">{err}</div>}
    <div className="panel"><div className="toolbar"><div><h3 style={{margin:'0 0 6px'}}>Uygulama kataloğu</h3><p className="muted" style={{margin:0}}>Uygulama kartı, çok dilli içerik, logo ve ekran görüntülerini platform medya kütüphanesiyle yönetin.</p></div><button className="btn" onClick={()=>setEditor({})}>Yeni uygulama</button></div></div>

    <div className="panel"><h3>Pakete göre fiyat / dahil et</h3><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/apps/'+f.appId+'/plan-pricing',{method:'POST',body:JSON.stringify({planId:f.planId,price:f.price===''?null:Number(f.price),currency:f.currency,billingType:f.billingType,included:f.included==='true',isActive:true})}),'Paket fiyatı kaydedildi.')}}><label>Uygulama<select name="appId" required>{apps.map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Paket<select name="planId" required>{plans.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Fiyat<input name="price" type="number" min="0" step="0.01" placeholder="Boş = uygulama temel fiyatı"/></label><label>Para birimi<select name="currency"><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Ücret tipi<select name="billingType"><option value="MONTHLY">Aylık</option><option value="YEARLY">Yıllık</option><option value="ONE_TIME">Tek sefer</option><option value="FREE">Ücretsiz</option></select></label><label>Pakete dahil<select name="included"><option value="false">Hayır</option><option value="true">Evet</option></select></label><div className="full"><button className="btn">Paket fiyatını kaydet</button></div></form></div>

    <div className="panel"><h3>Mağazaya doğrudan uygulama ekle</h3><p className="muted">Bu işlem ödeme kontrolünü atlar ve uygulamayı doğrudan müşterinin Uygulamalarım ekranına ekler.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));void run(()=>req('/superadmin/tenants/'+f.tenantId+'/apps/'+f.appId+'/grant',{method:'POST',body:'{}'}),'Uygulama mağazaya eklendi.')}}><label>Firma / mağaza<select name="tenantId" required>{tenants.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Uygulama<select name="appId" required>{apps.map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><div className="full"><button className="btn">Uygulamayı ekle</button></div></form></div>

    <div className="panel"><h3>Uygulamalar</h3><table><thead><tr><th>Uygulama</th><th>Kategori</th><th>Temel fiyat</th><th>Paket fiyatları</th><th>Kurulum</th><th>Durum</th><th></th></tr></thead><tbody>{apps.map((a:any)=>{const market=a.settingsSchema?.marketplace||{};return <tr key={a.id}><td><div className="sa-app-cell">{market.logoUrl?<img src={market.logoUrl} alt=""/>:<span className="sa-app-fallback">APP</span>}<div><b>{a.name}</b><div className="muted">{a.slug}</div></div></div></td><td>{a.category}</td><td>{Number(a.basePrice||0).toLocaleString('tr-TR')} {a.currency}</td><td>{(a.planPrices||[]).length?(a.planPrices||[]).map((x:any)=><div key={x.id}>{x.plan?.name}: {x.included?'Dahil':x.price===null||x.price===undefined?'Temel fiyat':`${Number(x.price).toLocaleString('tr-TR')} ${x.currency||a.currency}`}</div>):'-'}</td><td>{a._count?.installs||0}</td><td>{a.isActive?'Aktif':'Pasif'}</td><td><div className="sa-table-actions"><button className="btn secondary" onClick={()=>setEditor(a)}>Düzenle</button><button className="btn secondary" onClick={()=>void run(()=>req('/superadmin/apps/'+a.id,{method:'PATCH',body:JSON.stringify({isActive:!a.isActive})}),a.isActive?'Uygulama pasife alındı.':'Uygulama aktifleştirildi.')}>{a.isActive?'Pasife al':'Aktifleştir'}</button></div></td></tr>})}</tbody></table></div>
    {editor!==null&&<AppEditorModal app={editor} req={req} onClose={()=>setEditor(null)} onSave={async payload=>{const ok=await run(()=>editor.id?req('/superadmin/apps/'+editor.id,{method:'PATCH',body:JSON.stringify(payload)}):req('/superadmin/apps',{method:'POST',body:JSON.stringify(payload)}),editor.id?'Uygulama güncellendi.':'Uygulama mağaza kataloğuna eklendi.');if(ok)setEditor(null)}}/>}
  </>;
}

function AppEditorModal({app,req,onClose,onSave}:any){
  const market=app?.settingsSchema?.marketplace||{};const[busy,setBusy]=useState(false);const[uploading,setUploading]=useState(false);const[locales,setLocales]=useState<any[]>([{locale:'tr',label:'TR'}]);const[activeLocale,setActiveLocale]=useState('tr');const[media,setMedia]=useState<any[]>([]);const[mediaMode,setMediaMode]=useState<'logo'|'screens'>('logo');const[logoUrl,setLogoUrl]=useState(String(market.logoUrl||''));const[screenshots,setScreenshots]=useState<string[]>(Array.isArray(market.screenshots)?market.screenshots:[]);
  const initialTranslations:any={...(market.translations||{})};if(!initialTranslations.tr)initialTranslations.tr={name:app?.name||'',summary:app?.summary||'',description:app?.description||'',usageGuide:market.usageGuide||''};
  const[translations,setTranslations]=useState<any>(initialTranslations);
  useEffect(()=>{Promise.all([req('/superadmin/platform-locales'),req('/superadmin/media')]).then(([l,m]:any[])=>{const list=Array.isArray(l)&&l.length?l:[{locale:'tr',label:'TR'}];setLocales(list);const first=String(list[0]?.locale||'tr');setActiveLocale(first);setTranslations((old:any)=>{const next={...old};for(const row of list){const code=String(row.locale);if(!next[code])next[code]={name:'',summary:'',description:'',usageGuide:''}}return next});setMedia(Array.isArray(m)?m:[])}).catch(()=>{})},[]);
  const current=translations[activeLocale]||{name:'',summary:'',description:'',usageGuide:''};
  function setLang(key:string,value:string){setTranslations((all:any)=>({...all,[activeLocale]:{...(all[activeLocale]||{}),[key]:value}}))}
  function fileToData(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('Dosya okunamadı'));r.readAsDataURL(file)})}
  async function upload(file:File,mode:'logo'|'screens'){setUploading(true);try{const dataBase64=await fileToData(file);const row=await req('/superadmin/media/upload',{method:'POST',body:JSON.stringify({fileName:file.name,mimeType:file.type,dataBase64})});setMedia((x:any[])=>[row,...x]);if(mode==='logo')setLogoUrl(row.publicUrl);else setScreenshots(x=>Array.from(new Set([...x,row.publicUrl])))}finally{setUploading(false)}}
  function chooseMedia(url:string){if(mediaMode==='logo')setLogoUrl(url);else setScreenshots(x=>x.includes(url)?x.filter(v=>v!==url):[...x,url])}
  const defaultLocale=String(locales[0]?.locale||'tr');
  return <div className="sa-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="sa-modal sa-app-editor-modal"><div className="sa-modal-head"><div><h2>{app?.id?'Uygulamayı düzenle':'Yeni uygulama'}</h2><p className="muted">Teknik bilgiler dilden bağımsızdır; mağaza içeriği dil sekmelerinden yönetilir.</p></div><button className="btn secondary" onClick={onClose}>Kapat</button></div><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));const base=translations[defaultLocale]||{};setBusy(true);try{await onSave({name:base.name||app?.name||f.slug,slug:f.slug,category:f.category,summary:base.summary||base.name||f.slug,description:base.description||null,usageGuide:base.usageGuide||null,translations,logoUrl,screenshots,developer:f.developer||'WE DID IT',kind:f.kind,integrationType:f.integrationType||null,provider:f.provider||null,icon:f.icon||'iconoir:puzzle',basePrice:Number(f.basePrice||0),currency:f.currency||'TRY',billingType:f.billingType,isFeatured:f.isFeatured==='true',sortOrder:Number(f.sortOrder||0),isActive:true})}finally{setBusy(false)}}}>
      <label>Slug<input name="slug" defaultValue={app?.slug||''} required={!app?.id} readOnly={!!app?.id} placeholder="ornek-uygulama"/></label><label>Kategori<select name="category" defaultValue={app?.category||'Diğer'}><option>AI</option><option>Pazarlama</option><option>Pazaryeri</option><option>Kargo</option><option>Fatura & Muhasebe</option><option>Ödeme</option><option>CRM</option><option>Analitik</option><option>Diğer</option></select></label>
      <label>Tür<select name="kind" defaultValue={app?.kind||'INTEGRATION'}><option value="INTEGRATION">Entegrasyon</option><option value="AI">AI</option><option value="TOOL">Araç</option></select></label><label>Entegrasyon tipi<select name="integrationType" defaultValue={app?.integrationType||''}><option value="">Yok</option><option>MARKETPLACE</option><option>PAYMENT</option><option>SHIPPING</option><option>INVOICE</option><option>MARKETING</option><option>AI</option><option>SOCIAL</option><option>ANALYTICS</option><option>MESSAGING</option><option>CRM</option></select></label>
      <label>Provider kodu<input name="provider" defaultValue={app?.provider||''} placeholder="trendyol, yurtici, ..."/></label><label>Başlangıç fiyatı<input name="basePrice" type="number" min="0" step="0.01" defaultValue={app?.basePrice??0}/></label><label>Ücret tipi<select name="billingType" defaultValue={app?.billingType||'FREE'}><option value="FREE">Ücretsiz</option><option value="MONTHLY">Aylık</option><option value="YEARLY">Yıllık</option><option value="ONE_TIME">Tek sefer</option></select></label><label>Tema görseli URL<input name="previewImageUrl" defaultValue={app?.previewImageUrl||''} placeholder="https://..."/></label><label>Para birimi<select name="currency" defaultValue={app?.currency||'TRY'}><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Geliştirici<input name="developer" defaultValue={app?.developer||'WE DID IT'}/></label><label>İkon<input name="icon" defaultValue={app?.icon||'iconoir:puzzle'}/></label><label>Öne çıkan<select name="isFeatured" defaultValue={String(!!app?.isFeatured)}><option value="false">Hayır</option><option value="true">Evet</option></select></label><label>Sıra<input name="sortOrder" type="number" defaultValue={app?.sortOrder??0}/></label>
      <div className="full sa-language-tabs">{locales.map((l:any)=><button type="button" key={l.locale} className={activeLocale===l.locale?'active':''} onClick={()=>setActiveLocale(String(l.locale))}>{l.label||String(l.locale).toUpperCase()}</button>)}</div>
      <label className="full">Uygulama adı · {activeLocale.toUpperCase()}<input value={current.name||''} onChange={e=>setLang('name',e.target.value)} required={activeLocale===defaultLocale}/></label><label className="full">Kısa açıklama · {activeLocale.toUpperCase()}<textarea value={current.summary||''} onChange={e=>setLang('summary',e.target.value)} required={activeLocale===defaultLocale}/></label><label className="full">Detaylı açıklama · {activeLocale.toUpperCase()}<textarea rows={5} value={current.description||''} onChange={e=>setLang('description',e.target.value)}/></label><label className="full">Nasıl kullanılır? · {activeLocale.toUpperCase()}<textarea rows={5} value={current.usageGuide||''} onChange={e=>setLang('usageGuide',e.target.value)}/></label>
      <div className="full sa-media-editor"><div className="sa-media-toolbar"><div><b>Platform Medya Kütüphanesi</b><small>Logo ve ekran görüntüleri ortak medya alanında saklanır.</small></div><div><button type="button" className={'btn secondary '+(mediaMode==='logo'?'active':'')} onClick={()=>setMediaMode('logo')}>Logo seç</button><button type="button" className={'btn secondary '+(mediaMode==='screens'?'active':'')} onClick={()=>setMediaMode('screens')}>Ekran görüntüsü seç</button><label className="btn">{uploading?'Yükleniyor…':'Görsel yükle'}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" hidden disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,mediaMode);e.currentTarget.value=''}}/></label></div></div><div className="sa-media-grid">{media.map((m:any)=><button type="button" key={m.id} className={(logoUrl===m.publicUrl||screenshots.includes(m.publicUrl))?'selected':''} onClick={()=>chooseMedia(m.publicUrl)}><img src={m.publicUrl} alt={m.alt||m.originalName||''}/><span>{m.originalName||'Görsel'}</span></button>)}</div></div>
      <div className="full sa-selected-media"><div><b>Logo</b>{logoUrl?<img src={logoUrl} alt="logo"/>:<span className="muted">Seçilmedi</span>}</div><div><b>Ekran görüntüleri ({screenshots.length})</b><div>{screenshots.map(url=><button type="button" key={url} onClick={()=>setScreenshots(x=>x.filter(v=>v!==url))}><img src={url} alt=""/><span>×</span></button>)}</div></div></div>
      <div className="full sa-modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Vazgeç</button><button className="btn" disabled={busy||uploading}>{busy?'Kaydediliyor…':app?.id?'Değişiklikleri Kaydet':'Uygulamayı Ekle'}</button></div>
    </form></div></div>;
}

function TenantControl({tenants,req,reload}:any){tenants=Array.isArray(tenants)?tenants:[];const[plans,setPlans]=useState<any[]>([]);useEffect(()=>{req('/superadmin/plans').then((x:any)=>setPlans(Array.isArray(x)?x:[]))},[]);return <div className="panel"><h3>Firma yönetimi</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));await req('/superadmin/tenants/'+f.tenantId,{method:'PATCH',body:JSON.stringify({status:f.status})});if(f.planId)await req('/superadmin/tenants/'+f.tenantId+'/subscription',{method:'POST',body:JSON.stringify({planId:f.planId,status:'ACTIVE'})});reload()}}><label>Firma<select name="tenantId" required>{tenants.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Durum<select name="status"><option>ACTIVE</option><option>TRIAL</option><option>SUSPENDED</option><option>CANCELLED</option></select></label><label>Paket<select name="planId"><option value="">Değiştirme</option>{plans.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="full"><button className="btn">Uygula</button></div></form></div>}

function PlanForm({req,reload}:any){const features=[['promotions','Gelişmiş promosyon'],['multiCurrency','Çoklu para birimi'],['loyalty','Sadakat'],['marketing','E-posta / SMS / Popup'],['privacy','KVKK / GDPR araçları'],['customDomain','Özel domain'],['api','API erişimi'],['prioritySupport','Öncelikli destek']];return <div className="panel"><h3>Paket oluştur</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const f:any=Object.fromEntries(fd);const enabled=new Set(fd.getAll('features').map(String));const featureMap=Object.fromEntries(features.map(([key])=>[key,enabled.has(key)]));await req('/superadmin/plans',{method:'POST',body:JSON.stringify({name:f.name,code:f.code,monthlyPrice:Number(f.monthlyPrice||0),yearlyPrice:Number(f.yearlyPrice||0),maxStaff:Number(f.maxStaff||3),maxProducts:Number(f.maxProducts||1000),maxOrdersPerMonth:f.maxOrdersPerMonth?Number(f.maxOrdersPerMonth):null,features:{...featureMap,coupons:true,reviews:true,pages:true}})});e.currentTarget.reset();reload()}}><label>Ad<input name="name" required/></label><label>Kod<input name="code" required/></label><label>Aylık fiyat<input name="monthlyPrice" type="number" min="0"/></label><label>Yıllık fiyat<input name="yearlyPrice" type="number" min="0"/></label><label>Personel limiti<input name="maxStaff" type="number" min="1" defaultValue="3"/></label><label>Ürün limiti<input name="maxProducts" type="number" min="1" defaultValue="1000"/></label><label>Aylık sipariş limiti<input name="maxOrdersPerMonth" type="number" min="1"/></label><div className="full"><b>Paket özellikleri</b><div className="feature-grid">{features.map(([key,label])=><label className="feature-check" key={key}><input type="checkbox" name="features" value={key} defaultChecked/>{label}</label>)}</div></div><div className="full"><button className="btn">Paketi oluştur</button></div></form></div>}
function CurrencyControl({data,req,reload}:any){
  const rows=Array.isArray(data?.rates)?data.rates:[];const[busy,setBusy]=useState(false);const[source,setSource]=useState('FRANKFURTER');const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  return <><div className="panel"><div className="toolbar"><div><h3 style={{margin:'0 0 6px'}}>Platform Döviz Yönetimi</h3><p className="muted" style={{margin:0}}>Mağazaların aktif döviz kurlarını topluca yenileyin. Admin tarafından sabitlenen kurlar değiştirilmez.</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><select value={source} onChange={e=>setSource(e.target.value)}><option value="FRANKFURTER">Frankfurter</option><option value="TCMB">TCMB</option></select><button className="btn" disabled={busy} onClick={async()=>{setBusy(true);setMsg('');setErr('');try{const r=await req('/superadmin/currency-rates/refresh',{method:'POST',body:JSON.stringify({source})});setMsg(`${r.updatedStores||0} mağaza, ${r.updatedRates||0} kur güncellendi.`);await reload()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}}>{busy?'Güncelleniyor…':'Tüm Kurları Güncelle'}</button></div></div>{msg&&<div className="success" style={{marginTop:12}}>{msg}</div>}{err&&<div className="error" style={{marginTop:12}}>{err}</div>}</div><div className="panel"><Table rows={rows} cols={[["storeName","Mağaza"],["code","Döviz"],["exchangeRate","Kur"],["pinnedLabel","Sabit"],["updatedAt","Güncelleme"]]}/></div></>;
}

function SupportControl({tickets,req,reload}:any){tickets=Array.isArray(tickets)?tickets:[];return <div className="panel"><h3>Destek talebi yanıtla</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));await req('/superadmin/support/tickets/'+f.ticketId,{method:'PATCH',body:JSON.stringify({status:f.status,message:f.message})});e.currentTarget.reset();reload()}}><label>Talep<select name="ticketId" required>{tickets.map((t:any)=><option key={t.id} value={t.id}>{t.tenant?.name} — {t.subject}</option>)}</select></label><label>Durum<select name="status"><option>IN_PROGRESS</option><option>WAITING_CUSTOMER</option><option>RESOLVED</option><option>CLOSED</option></select></label><label className="full">Yanıt<textarea name="message" required/></label><div className="full"><button className="btn">Yanıtla</button></div></form></div>}

function get(o:any,path:string){return path.split('.').reduce((a,k)=>Array.isArray(a)&&/^\d+$/.test(k)?a[Number(k)]:a?.[k],o)}
function Table({rows,cols}:{rows:any[],cols:[string,string][]}){rows=Array.isArray(rows)?rows:[];return <table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=>{let v=get(r,c[0]);if(c[0].includes('At')&&v)v=new Date(v).toLocaleString('tr-TR');if(typeof v==='boolean')v=v?'Evet':'Hayır';return <td key={c[0]}>{String(v??'-')}</td>})}</tr>)}</tbody></table>}
